// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrh5W9VwbC3qTtSTm8LJbTQeYufRGil5s',
    appId: '1:344682929526:web:5d3732578d6f012ac26e57',
    messagingSenderId: '344682929526',
    projectId: 'sokonimoko-8c171-a8d14',
    authDomain: 'sokonimoko-8c171-a8d14.firebaseapp.com',
    databaseURL: 'https://sokonimoko-8c171-a8d14-default-rtdb.firebaseio.com',
    storageBucket: 'sokonimoko-8c171-a8d14.firebasestorage.app',
    measurementId: 'G-P6VXK4LYMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJ76izS22J-tQ0W90rUG7zd-pGEIzIvk',
    appId: '1:344682929526:android:828e2523b15358a7c26e57',
    messagingSenderId: '344682929526',
    projectId: 'sokonimoko-8c171-a8d14',
    databaseURL: 'https://sokonimoko-8c171-a8d14-default-rtdb.firebaseio.com',
    storageBucket: 'sokonimoko-8c171-a8d14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKCh1yepeS53GvF5EOVER1QKj6rQ5quqQ',
    appId: '1:344682929526:ios:500eba80b1b44e3bc26e57',
    messagingSenderId: '344682929526',
    projectId: 'sokonimoko-8c171-a8d14',
    databaseURL: 'https://sokonimoko-8c171-a8d14-default-rtdb.firebaseio.com',
    storageBucket: 'sokonimoko-8c171-a8d14.firebasestorage.app',
    androidClientId: '344682929526-5ame7l830dt2d2eu3igihfvunaab0v18.apps.googleusercontent.com',
    iosClientId: '344682929526-ecva26lp30ci9qg48onsvnt2ftbanvit.apps.googleusercontent.com',
    iosBundleId: 'com.sokolangu.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKCh1yepeS53GvF5EOVER1QKj6rQ5quqQ',
    appId: '1:344682929526:ios:500eba80b1b44e3bc26e57',
    messagingSenderId: '344682929526',
    projectId: 'sokonimoko-8c171-a8d14',
    databaseURL: 'https://sokonimoko-8c171-a8d14-default-rtdb.firebaseio.com',
    storageBucket: 'sokonimoko-8c171-a8d14.firebasestorage.app',
    androidClientId: '344682929526-5ame7l830dt2d2eu3igihfvunaab0v18.apps.googleusercontent.com',
    iosClientId: '344682929526-ecva26lp30ci9qg48onsvnt2ftbanvit.apps.googleusercontent.com',
    iosBundleId: 'com.sokolangu.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrh5W9VwbC3qTtSTm8LJbTQeYufRGil5s',
    appId: '1:344682929526:web:f84d8004aef375abc26e57',
    messagingSenderId: '344682929526',
    projectId: 'sokonimoko-8c171-a8d14',
    authDomain: 'sokonimoko-8c171-a8d14.firebaseapp.com',
    databaseURL: 'https://sokonimoko-8c171-a8d14-default-rtdb.firebaseio.com',
    storageBucket: 'sokonimoko-8c171-a8d14.firebasestorage.app',
    measurementId: 'G-SNXGXR4R9B',
  );

}