import 'package:flutter/material.dart';

/// Minimal sw/en localization with a structure ready for a third locale.
/// Every key MUST exist in both maps (covered by locale_parity_test).
class AppStrings extends ChangeNotifier {
  String _code = 'sw';
  String get code => _code;
  bool get isSw => _code == 'sw';

  void setLocale(String code) {
    if (code != _code && _dict.containsKey(code)) {
      _code = code;
      notifyListeners();
    }
  }

  String t(String key) => _dict[_code]?[key] ?? _dict['sw']?[key] ?? key;

  /// Key set per locale for the parity test. Not for production use.
  static Set<String> keysFor(String code) =>
      _dict[code]?.keys.toSet() ?? {};

  static AppStrings of(BuildContext context) {
    final s = context
        .dependOnInheritedWidgetOfExactType<AppStringsProvider>()
        ?.strings;
    assert(s != null, 'AppStringsProvider missing above context');
    return s!;
  }

  static const _dict = <String, Map<String, String>>{
    'sw': {
      'doc_title': 'Soko Vibe — Nunua na Uza Bidhaa Tanzania',
      'nav_how': 'Jinsi Inavyofanya Kazi',
      'nav_security': 'Usalama',
      'nav_sellers': 'Kwa Wauzaji',
      'nav_faq': 'Maswali',
      'nav_sell': 'Anza Kuuza',
      'nav_menu': 'Fungua menyu',
      'nav_close': 'Funga menyu',
      'lang_label': 'Lugha',
      'hero_badge': 'Soko la Tanzania · Malipo ya escrow',
      'hero_title_a': 'Nunua kwa uhakika.',
      'hero_title_b': 'Uza kwa ujasiri.',
      'hero_sub':
          'Soko Vibe ni soko la Tanzania la kununua na kuuza bidhaa kwa urahisi, huku malipo yakilindwa kwa escrow mpaka uthibitishe kupokea bidhaa yako.',
      'cta_buy': 'Anza Kununua',
      'cta_sell': 'Anza Kuuza',
      'cta_services': 'Angalia huduma',
      'hero_mock_search': 'Tafuta simu, viatu, samani…',
      'hero_mock_escrow': 'Escrow inalinda malipo',
      'hero_mock_delivery': 'Usafirishaji nchi nzima',
      'trust_line': 'Imetengenezwa kwa wanunuzi na wauzaji wa Tanzania.',
      'card_verified': 'Aliyehakikiwa',
      'card_delivery': 'Usafirishaji',
      'why_eyebrow': 'Kwa nini Soko Vibe?',
      'why_title': 'Ununuzi unaanza kwa kuamini.',
      'why_sub':
          'Kila hatua ya muamala imejengwa kukulinda — kuanzia unapoona bidhaa hadi unapoipokea.',
      'f_escrow_t': 'Escrow inalinda pesa',
      'f_escrow_b':
          'Fedha zinashikiliwa na ClickPesa hadi uthibitishe kupokea bidhaa. Mgogoro ukitokea, timu inashughulikia.',
      'f_kyc_t': 'Wauzaji waliohakikiwa',
      'f_kyc_b': 'Wauzaji huthibitisha utambulisho (KYC) kabla ya kuuza.',
      'f_chat_t': 'Mazungumzo salama',
      'f_chat_b': 'Ongea na muuzaji ndani ya app kabla ya kuamua — maswali, picha na majadiliano ya bei.',
      'f_money_t': 'Mobile money',
      'f_money_b': 'Lipa kwa M-Pesa, Tigo Pesa, Airtel Money, HaloPesa au EzyPesa.',
      'f_otp_t': 'Uthibitisho wa OTP',
      'f_otp_b': 'Unathibitisha kupokea kwa OTP — ndipo muuzaji analipwa.',
      'f_ai_t': 'Utafutaji wa AI',
      'f_ai_b': 'Tafuta kwa kuandika au kwa sauti; msaidizi anakusaidia kupata unachohitaji.',
      'escrow_title': 'Fedha zako hazitoki mpaka upokee.',
      'escrow_sub':
          'Huu ndio mzunguko wa kila malipo — wazi, unaofuatiliwa, na salama kwa pande zote mbili.',
      'esc_pay': 'Mnunuzi analipa',
      'esc_hold': 'Escrow inashikilia',
      'esc_ship': 'Muuzaji anatuma',
      'esc_receive': 'Mnunuzi anapokea',
      'esc_confirm': 'Mnunuzi anathibitisha',
      'esc_release': 'Muuzaji analipwa',
      'buyers_eyebrow': 'Kwa wanunuzi',
      'buyers_title': 'Kila kitu unachohitaji kununua kwa amani.',
      'buyers_1': 'Tafuta na linganisha bidhaa',
      'buyers_2': 'Ongea na muuzaji moja kwa moja',
      'buyers_3': 'Lipa kwa usalama kupitia escrow',
      'buyers_4': 'Fuatilia oda yako',
      'buyers_5': 'Thibitisha kupokea kwa OTP',
      'sellers_eyebrow': 'Kwa wauzaji',
      'sellers_title': 'Duka lako, dashboard yenye nguvu.',
      'sellers_sub': 'Weka bidhaa bure, simamia oda, ongea na wateja na ukuze mauzo.',
      'sellers_1': 'Orodha za bidhaa bila gharama',
      'sellers_2': 'Takwimu za mauzo kwa wakati',
      'sellers_3': 'Boost bidhaa kwa bei nafuu',
      'sellers_4': 'Uthibitisho wa muuzaji (KYC)',
      'sellers_5': 'Usimamizi wa oda na pochi',
      'sellers_chart': 'Mfano wa takwimu',
      'sellers_chart_w1': 'J1',
      'sellers_chart_w2': 'J2',
      'sellers_chart_w3': 'J3',
      'sellers_chart_w4': 'J4',
      'sellers_chart_w5': 'J5',
      'sellers_chart_w6': 'J6',
      'sellers_chart_w7': 'J7',
      'ai_eyebrow': 'Teknolojia',
      'ai_title': 'Tafuta unachotaka kwa njia rahisi.',
      'ai_sub': 'Andika kama unavyoongea — au bonyeza kipaza sauti.',
      'ai_demo_q': 'samani za kisasa',
      'ai_demo_note': 'Mfano wa onesho',
      'ai_suggest': 'Nakupendekeza kategoria zifuatazo:',
      'ai_voice': 'Tafuta kwa sauti',
      'deliver_eyebrow': 'Usafirishaji',
      'deliver_title': 'Unaona kila hatua ya kifurushi chako.',
      'deliver_1t': 'Oda imewekwa',
      'deliver_1b': 'Malipo yanaingia escrow mara moja.',
      'deliver_2t': 'Muuzaji anaandaa',
      'deliver_2b': 'Bidhaa inafungwa na kukabidhiwa msafirishaji.',
      'deliver_3t': 'Njiani',
      'deliver_3b': 'Unafuatilia usafirishaji nchi nzima.',
      'deliver_4t': 'Inakaribia',
      'deliver_4b': 'Unajulishwa kifurushi kinapowasili.',
      'deliver_5t': 'Imepokelewa',
      'deliver_5b': 'Unathibitisha kwa OTP — muuzaji analipwa.',
      'boost_eyebrow': 'Ukuaji wa muuzaji',
      'boost_title': 'Unataka bidhaa yako ionekane zaidi?',
      'boost_sub': 'Kuweka orodha ni bure kila wakati. Unalipa tu unapochagua kupandisha.',
      'boost_bronze_f': 'Mwonekano wa haraka',
      'boost_silver_f': 'Wiki nzima ya mwonekano',
      'boost_gold_f': 'Ufikiaji mkubwa, mwezi mzima',
      'boost_per': 'kwa orodha moja',
      'boost_d3': 'siku 3',
      'boost_d7': 'siku 7',
      'boost_d30': 'siku 30',
      'boost_popular': 'Maarufu',
      'boost_cta': 'Pandisha kwenye app',
      'boost_note': 'Bei zote ni shilingi za Tanzania. Boost unafanya ndani ya app.',
      'sec_eyebrow': 'Usalama',
      'sec_title': 'Tulivu, wazi, salama.',
      'sec_1t': 'Escrow na ClickPesa',
      'sec_1b': 'Fedha zinashikiliwa hadi ununuzi uthibitike.',
      'sec_2t': 'KYC ya wauzaji',
      'sec_2b': 'Utambulisho unahakikiwa kabla ya kuuza.',
      'sec_3t': 'Mchakato wa malalamiko',
      'sec_3b': 'Mgogoro ukitokea kuna njia rasmi ya kutatua.',
      'sec_4t': 'Faragha ya data',
      'sec_4b': 'Tunafuata Sheria ya Ulinzi wa Data ya Tanzania, 2022.',
      'app_eyebrow': 'App',
      'app_title': 'Soko lote mfukoni mwako.',
      'app_sub':
          'App ya Android inapatikana sasa kupitia WhatsApp. Tutumie ujumbe tukupatie link rasmi.',
      'app_cta': 'Pata Soko Vibe',
      'app_store_note': 'Google Play — Inapatikana hivi karibuni',
      'faq_eyebrow': 'Maswali',
      'faq_title': 'Maswali yanayoulizwa mara kwa mara',
      'q1': 'Je, kuweka bidhaa ni bure?',
      'a1': 'Ndiyo. Kufungua orodha haina gharama. Unalipa tu unapochagua ku-boost.',
      'q2': 'Fedha zangu zinalindwaje?',
      'a2': 'Malipo yanaingia escrow kupitia ClickPesa na yanatolewa kwa muuzaji tu baada ya wewe kuthibitisha kupokea.',
      'q3': 'Naweza kuzungumza na muuzaji?',
      'a3': 'Ndiyo — kila orodha ina mazungumzo ya ndani ya app kabla ya kununua.',
      'q4': 'Usafirishaji unafanyaje kazi?',
      'a4': 'Wauzaji hupanga usafirishaji nchi nzima; unathibitisha kupokea kwa OTP.',
      'q5': 'Kuna ada gani?',
      'a5': 'Ada ya jukwaa ya 3.5% kwa mnunuzi wakati wa ununuzi. Muuzaji anapokea bei kamili. Hakuna ada ya orodha.',
      'q6': 'Ninawezaje kupata app?',
      'a6': 'Tutumie ujumbe WhatsApp +255 693 273 241 na tutakupatia link rasmi ya Android.',
      'final_title': 'Karibu kwenye soko linalofuata la Tanzania.',
      'final_sub': 'Nunua kwa uhakika. Uza kwa ujasiri.',
      'final_cta': 'Anza na Soko Vibe',
      'foot_tag': 'Soko la Tanzania la kununua na kuuza kwa usalama.',
      'foot_soko': 'Soko Vibe',
      'foot_how': 'Jinsi Inavyofanya Kazi',
      'foot_safety': 'Usalama',
      'foot_fees': 'Ada',
      'foot_faq': 'Maswali',
      'foot_sellers': 'Kwa Wauzaji',
      'foot_sell': 'Anza Kuuza',
      'foot_tools': 'Zana za Muuzaji',
      'foot_boost': 'Boost',
      'foot_verify': 'Uthibitisho',
      'foot_legal': 'Sheria',
      'foot_privacy': 'Privacy',
      'foot_terms': 'Terms',
      'foot_security': 'Security',
      'foot_contact': 'Mawasiliano',
      'foot_rights': 'Haki zote zimehifadhiwa.',
    },
    'en': {
      'doc_title': 'Soko Vibe — Buy and Sell Products in Tanzania',
      'nav_how': 'How It Works',
      'nav_security': 'Security',
      'nav_sellers': 'For Sellers',
      'nav_faq': 'FAQ',
      'nav_sell': 'Start Selling',
      'nav_menu': 'Open menu',
      'nav_close': 'Close menu',
      'lang_label': 'Language',
      'hero_badge': 'Tanzanian market · Escrow payments',
      'hero_title_a': 'Buy with confidence.',
      'hero_title_b': 'Sell with courage.',
      'hero_sub':
          'Soko Vibe is the Tanzanian market for buying and selling products with ease, while payments stay protected in escrow until you confirm receipt.',
      'cta_buy': 'Start Buying',
      'cta_sell': 'Start Selling',
      'cta_services': 'Explore services',
      'hero_mock_search': 'Search phones, shoes, furniture…',
      'hero_mock_escrow': 'Escrow protects payment',
      'hero_mock_delivery': 'Nationwide delivery',
      'trust_line': 'Built for Tanzanian buyers and sellers.',
      'card_verified': 'Verified',
      'card_delivery': 'Delivery',
      'why_eyebrow': 'Why Soko Vibe?',
      'why_title': 'Buying starts with trust.',
      'why_sub':
          'Every step of the transaction is built to protect you — from discovery to doorstep.',
      'f_escrow_t': 'Escrow-protected money',
      'f_escrow_b':
          'Funds are held by ClickPesa until you confirm receipt. If a dispute arises, the team steps in.',
      'f_kyc_t': 'Verified sellers',
      'f_kyc_b': 'Sellers verify identity (KYC) before selling.',
      'f_chat_t': 'Secure chat',
      'f_chat_b': 'Talk to the seller in-app before deciding — questions, photos, price talk.',
      'f_money_t': 'Mobile money',
      'f_money_b': 'Pay with M-Pesa, Tigo Pesa, Airtel Money, HaloPesa or EzyPesa.',
      'f_otp_t': 'OTP confirmation',
      'f_otp_b': 'You confirm receipt with an OTP — only then is the seller paid.',
      'f_ai_t': 'AI search',
      'f_ai_b': 'Search by typing or voice; the assistant helps you find what you need.',
      'escrow_title': 'Your money never moves until you receive.',
      'escrow_sub':
          'This is the journey of every payment — open, trackable, and safe for both sides.',
      'esc_pay': 'Buyer pays',
      'esc_hold': 'Escrow holds',
      'esc_ship': 'Seller ships',
      'esc_receive': 'Buyer receives',
      'esc_confirm': 'Buyer confirms',
      'esc_release': 'Seller is paid',
      'buyers_eyebrow': 'For buyers',
      'buyers_title': 'Everything you need to buy in peace.',
      'buyers_1': 'Find and compare products',
      'buyers_2': 'Chat directly with sellers',
      'buyers_3': 'Pay securely via escrow',
      'buyers_4': 'Track your order',
      'buyers_5': 'Confirm delivery with OTP',
      'sellers_eyebrow': 'For sellers',
      'sellers_title': 'Your shop, a powerful dashboard.',
      'sellers_sub': 'List for free, manage orders, talk to customers and grow sales.',
      'sellers_1': 'Free product listings',
      'sellers_2': 'Real-time sales stats',
      'sellers_3': 'Affordable product boosts',
      'sellers_4': 'Seller verification (KYC)',
      'sellers_5': 'Orders and wallet management',
      'sellers_chart': 'Sample stats',
      'sellers_chart_w1': 'W1',
      'sellers_chart_w2': 'W2',
      'sellers_chart_w3': 'W3',
      'sellers_chart_w4': 'W4',
      'sellers_chart_w5': 'W5',
      'sellers_chart_w6': 'W6',
      'sellers_chart_w7': 'W7',
      'ai_eyebrow': 'Technology',
      'ai_title': 'Find what you want, the easy way.',
      'ai_sub': 'Write like you speak — or tap the microphone.',
      'ai_demo_q': 'modern furniture',
      'ai_demo_note': 'Demo illustration',
      'ai_suggest': 'I suggest these categories:',
      'ai_voice': 'Voice search',
      'deliver_eyebrow': 'Delivery',
      'deliver_title': 'See every step of your parcel.',
      'deliver_1t': 'Order placed',
      'deliver_1b': 'Payment enters escrow immediately.',
      'deliver_2t': 'Seller prepares',
      'deliver_2b': 'The product is packed and handed to the courier.',
      'deliver_3t': 'In transit',
      'deliver_3b': 'You follow delivery across the country.',
      'deliver_4t': 'Arriving',
      'deliver_4b': 'You are notified as the parcel arrives.',
      'deliver_5t': 'Delivered',
      'deliver_5b': 'You confirm with OTP — the seller is paid.',
      'boost_eyebrow': 'Seller growth',
      'boost_title': 'Want your product seen more?',
      'boost_sub': 'Listing is always free. You only pay when you choose to boost.',
      'boost_bronze_f': 'Quick visibility',
      'boost_silver_f': 'A full week of visibility',
      'boost_gold_f': 'Maximum reach, all month',
      'boost_per': 'per listing',
      'boost_d3': '3 days',
      'boost_d7': '7 days',
      'boost_d30': '30 days',
      'boost_popular': 'Popular',
      'boost_cta': 'Boost in the app',
      'boost_note': 'All prices are Tanzanian shillings. Boosting happens inside the app.',
      'sec_eyebrow': 'Security',
      'sec_title': 'Calm, open, secure.',
      'sec_1t': 'Escrow & ClickPesa',
      'sec_1b': 'Funds are held until the purchase is confirmed.',
      'sec_2t': 'Seller KYC',
      'sec_2b': 'Identity is verified before selling.',
      'sec_3t': 'Complaints process',
      'sec_3b': 'If a dispute arises there is a formal resolution path.',
      'sec_4t': 'Data privacy',
      'sec_4b': 'We follow the Tanzania Data Protection Act, 2022.',
      'app_eyebrow': 'App',
      'app_title': 'The whole market in your pocket.',
      'app_sub':
          'The Android app is available now via WhatsApp. Message us and we will send the official link.',
      'app_cta': 'Get Soko Vibe',
      'app_store_note': 'Google Play — Coming soon',
      'faq_eyebrow': 'FAQ',
      'faq_title': 'Frequently asked questions',
      'q1': 'Is listing products free?',
      'a1': 'Yes. Opening a listing costs nothing. You only pay when you choose to boost.',
      'q2': 'How is my money protected?',
      'a2': 'Payments enter escrow via ClickPesa and reach the seller only after you confirm receipt.',
      'q3': 'Can I talk to the seller?',
      'a3': 'Yes — every listing has in-app chat before you buy.',
      'q4': 'How does delivery work?',
      'a4': 'Sellers arrange nationwide delivery; you confirm receipt with OTP.',
      'q5': 'What fees exist?',
      'a5': 'A 3.5% platform fee for the buyer at checkout. The seller receives the full price. No listing fees.',
      'q6': 'How do I get the app?',
      'a6': 'Message us on WhatsApp at +255 693 273 241 for the official Android link.',
      'final_title': 'Welcome to the next Tanzanian market.',
      'final_sub': 'Buy with confidence. Sell with courage.',
      'final_cta': 'Start with Soko Vibe',
      'foot_tag': 'The Tanzanian market for safe buying and selling.',
      'foot_soko': 'Soko Vibe',
      'foot_how': 'How It Works',
      'foot_safety': 'Security',
      'foot_fees': 'Fees',
      'foot_faq': 'FAQ',
      'foot_sellers': 'For Sellers',
      'foot_sell': 'Start Selling',
      'foot_tools': 'Seller Tools',
      'foot_boost': 'Boost',
      'foot_verify': 'Verification',
      'foot_legal': 'Legal',
      'foot_privacy': 'Privacy',
      'foot_terms': 'Terms',
      'foot_security': 'Security',
      'foot_contact': 'Contact',
      'foot_rights': 'All rights reserved.',
    },
  };
}

class AppStringsProvider extends InheritedWidget {
  final AppStrings strings;
  const AppStringsProvider({
    super.key,
    required this.strings,
    required super.child,
  });

  @override
  bool updateShouldNotify(AppStringsProvider old) =>
      old.strings.code != strings.code;
}

extension StringsX on BuildContext {
  String str(String key) => AppStrings.of(this).t(key);
}
