import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static const String _languageKey = 'language_code';
  static const String _currencyKey = 'currency';

  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'sw': 'Swahili',
  };

  static const Map<String, Map<String, String>> supportedCurrencies = {
    'TZS': {'symbol': 'TSh', 'name': 'Tanzanian Shilling'},
    'USD': {'symbol': r'$', 'name': 'US Dollar'},
    'EUR': {'symbol': '€', 'name': 'Euro'},
    'GBP': {'symbol': '£', 'name': 'British Pound'},
    'KES': {'symbol': 'KSh', 'name': 'Kenyan Shilling'},
    'UGX': {'symbol': 'USh', 'name': 'Ugandan Shilling'},
    'NGN': {'symbol': '₦', 'name': 'Nigerian Naira'},
    'ZAR': {'symbol': 'R', 'name': 'South African Rand'},
    'CNY': {'symbol': '¥', 'name': 'Chinese Yuan'},
  };

  static const Map<String, Map<String, String>> translations = {
    'sw': {
      'app_name': 'Soko Langu',
      'login': 'Ingia',
      'register': 'Fungua Akaunti',
      'email': 'Barua Pepe',
      'password': 'Nywila',
      'categories': 'Kategoria',
      'latest_products': 'Bidhaa Mpya',
      'search': 'Tafuta',
      'sell_product': 'Uza Bidhaa',
      'profile': 'Wasifu',
      'settings': 'Mipangilio',
      'chats': 'Mazungumzo',
      'logout': 'Toka',
      'add_to_cart': 'Ongeza kwenye Rukwama',
      'buy_now': 'Nunua Sasa',
      'quantity': 'Idadi',
      'total': 'Jumla',
      'no_products': 'Hakuna bidhaa bado',
      'no_categories': 'Hakuna kategoria bado',
      'product_detail': 'Maelezo ya Bidhaa',
      'description': 'Maelezo',
      'details': 'Maelezo',
      'category': 'Kategoria',
      'brand': 'Chapa',
      'condition': 'Hali',
      'location': 'Mahali',
      'stock': 'Hifadhi',
      'wholesale': 'Jumla',
      'seller': 'Muuzaji',
      'view_store': 'Tazama Duka',
      'chat': 'Zungumza',
      'reviews': 'Maoni',
      'write_review': 'Andika Maoni',
      'rating': 'Ukadiriaji',
      'comment': 'Maoni',
      'submit': 'Wasilisha',
      'cancel': 'Ghairi',
      'save': 'Hifadhi',
      'delete': 'Futa',
      'edit': 'Hariri',
      'my_ads': 'Matangazo Yangu',
      'my_orders': 'Maagizo Yangu',
      'wishlist': 'Orodha ya Tamaa',
      'music_player': 'Kicheza Muziki',
      'shopping_cart': 'Rukwama ya Manunuzi',
      'cart_empty': 'Rukwama yako haina kitu',
      'checkout': 'Nenda kwa Malipo',
      'place_order': 'Weka Agizo',
      'order_placed': 'Agizo limewekwa! Tuma malipo kwa muuzaji.',
      'order_failed': 'Agizo limeshindwa',
      'pending': 'Inasubiri',
      'confirmed': 'Imethibitishwa',
      'processing': 'Inachakatwa',
      'shipped': 'Imesafirishwa',
      'delivered': 'Imefikishwa',
      'cancelled': 'Imeghairiwa',
      'edit_profile': 'Hariri Wasifu',
      'display_name': 'Jina la Kuonyesha',
      'bio': 'Maelezo',
      'phone': 'Namba ya Simu',
      'payment_methods': 'Njia za Malipo',
      'add_payment': 'Ongeza',
      'select_payment': 'Chagua Njia ya Malipo',
      'total_amount': 'Jumla',
      'chat_with_seller': 'Zungumza na Muuzaji',
      'send': 'Tuma',
      'type_message': 'Andika ujumbe...',
      'no_conversations': 'Hakuna mazungumzo bado',
      'no_notifications': 'Hakuna arifa bado',
      'search_products': 'Tafuta bidhaa...',
      'filter': 'Chuja',
      'price_range': 'Bei',
      'apply': 'Tekeleza',
      'clear': 'Futa',
      'about': 'Kuhusu Soko Langu',
      'version': 'Toleo 1.0.0',
      'help': 'Msaada',
      'appearance': 'Mwonekano',

      'notifications': 'Arifa',
      'push_notifications': 'Arifa za Push',
      'language': 'Lugha',
      'currency': 'Sarafu',
      'account': 'Akaunti',
      'support': 'Msaada',
      'contact': 'Wasiliana: langusoko@gmail.com',
      'online': 'Mtandaoni',
      'offline': 'Nje ya mtandao',
      'last_seen': 'Imeonekana mwisho',
      'just_now': 'sasa hivi',
      'minutes_ago': 'dakika zilizopita',
      'set_pin': 'Weka PIN',
      'confirm_pin': 'Thibitisha PIN',
      'pin_mismatch': 'PIN hazilingani',
      'pin_updated': 'PIN imesasishwa',
      'premium': 'Premium',
      'go_premium': 'Pata Premium',
      'premium_active': 'Premium Imewashwa',
      'premium_no_ads': 'Hakuna matangazo',
      'premium_subtitle': 'Ondoa matangazo na upate vipengele vya kipekee',
      'premium_benefits':
          'Pata Premium kufurahia:\n\n✓ Hakuna matangazo\n✓ Msaada wa haraka\n✓ Vipengele vya kipekee',
      'upgrade_now': 'Pata Sasa',
      'premium_upgraded': 'Karibu Premium! Hakuna matangazo tena.',
      'premium_title': 'Pata Premium',
      'premium_feature_support': 'Msaada wa haraka kwa wateja',
      'premium_feature_badges': 'Beji na vipengele vya kipekee',
      'monthly': 'Kila Mwezi',
      'yearly': 'Kwa Mwaka',
      'per_month': '/mwezi',
      'per_year': '/mwaka',
      'payment_method': 'Njia ya Malipo',
      'enter_phone': 'Ingiza namba yako ya simu',
      'phone_number': 'Namba ya Simu',
      'phone_hint': 'mfano 2557XXXXXXXX',
      'subscribe_now': 'Jiandikisha Sasa',
      'payment_failed': 'Malipo yameshindwa. Jaribu tena.',
      'welcome_premium': 'Karibu Premium!',
      'help_payment_mongike':
          'Malipo yanafanywa kwa njia salama kupitia Mongike. Tuma malipo kwa kutumia M-Pesa, Airtel Money, Mixx by Yas, au Halopesa.',
      'payment_secure': 'Malipo salama kupitia Mongike',
      'upgrade_account': 'Pata Akaunti',
      'silver': 'Silver',
      'free': 'Bure',
      'silver_feature_visibility':
          'Bidhaa zako zinaonekana KWANZA kwenye matokeo',
      'silver_feature_badge': 'Beji ya Silver kwenye wasifu wako',
      'silver_feature_support': 'Msaada wa haraka kwa wateja',
      'silver_welcome_msg':
          'Bidhaa zako sasa zinaonekana kwanza kwenye matokeo!',
      'account_tier': 'Aina ya Akaunti',
      'welcome_soko': 'Karibu Soko Langu!',
      'choose_account': 'Chagua aina ya akaunti yako',
      'forever': 'Daima',
      'free_feature_list': 'Orodhesha na uze bidhaa',
      'free_feature_ads': 'Matangazo yanaonekana',
      'continue_free': 'Endelea na Bure',
      'skip_choose': 'Nitaamua baadaye, nianze na Bure',

      'plan_compare': 'Vipengele',
      'wallpaper': 'Picha ya Mandhari',
      'wallpaper_sub': 'Badilisha mandhari ya app yako',
      'choose_wallpaper': 'Chagua kutoka Kwenye Picha',
      'remove_wallpaper': 'Ondoa Picha',
      'no_wallpaper': 'Hakuna picha iliyowekwa',
      'admin_dashboard': 'Admin Dashboard',
      'transaction_history': 'Historia ya Malipo',
      'processing_fee': 'Ada ya Kuchakata',
      'platform_fee': 'Ada ya Jemala',
      'total_fee': 'Jumla ya Ada',
      'total_to_pay': 'Jumla ya Kulipa',
      'seller_receives': 'Muuzaji Anapokea',
      'payment_successful': 'Malipo Yamekamilika!',
      'payment_processed': 'Malipo yako yamechakatwa.',
      'back_to_home': 'Rudi Nyumbani',
      'transaction_fee_agreement': 'Mkataba wa Ada ya Ununuzi',
      'fee_explanation':
          'Ununuzi huu unajumuisha ada ya 5% (3% ada ya kuchakata + 2% ada ya jemala).',
      'allow_continue': 'Ruhusu na Endelea',
      'deny_cancel': 'Kataa na Ghairi',
      'transaction_cancelled':
          'Ununuzi umetenguliwa. Hakuna malipo yaliyotozwa.',
      'searching_soko': 'Inatafuta soko_langu...',
      'loading_results': 'Inapakia matokeo kutoka soko_langu...',
      'no_results_soko': 'Hakuna matokeo katika soko_langu',
      'try_different': 'Jaribu maneno tofauti au vinjari kategoria',
      'trouble_connecting':
          'soko_langu inatatizika kuunganisha. Tafadhali jaribu tena.',
      'try_again': 'Jaribu Tena',

      'total_sales': 'Mauzo Jumla',
      'amount_received': 'Kiasi Kilichopokelewa',
      'admin_earnings': 'Mapato ya Msimamizi',
      'set_username': 'Weka jina la mtumiaji',
      'username_taken': 'Jina hili la mtumiaji tayari linatumika',
      'free_plan_current': 'Hivi sasa uko kwenye mpango wa Bure',
      'plan_active': 'Mpango wako umewashwa',
      'received_orders': 'Maagizo Niliyopokea',
      'received': 'Nimepokea',
    },
    'en': {
      'app_name': 'Soko Langu',
      'login': 'Login',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'categories': 'Categories',
      'latest_products': 'Latest Products',
      'search': 'Search',
      'sell_product': 'Sell Product',
      'profile': 'Profile',
      'settings': 'Settings',
      'chats': 'Chats',
      'logout': 'Logout',
      'add_to_cart': 'Add to Cart',
      'buy_now': 'Buy Now',
      'quantity': 'Quantity',
      'total': 'Total',
      'no_products': 'No products yet',
      'no_categories': 'No categories yet',
      'product_detail': 'Product Detail',
      'description': 'Description',
      'details': 'Details',
      'category': 'Category',
      'brand': 'Brand',
      'condition': 'Condition',
      'location': 'Location',
      'stock': 'Stock',
      'wholesale': 'Wholesale',
      'seller': 'Seller',
      'view_store': 'View Store',
      'chat': 'Chat',
      'reviews': 'Reviews',
      'write_review': 'Write a Review',
      'rating': 'Rating',
      'comment': 'Comment',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'my_ads': 'My Ads',
      'my_orders': 'My Orders',
      'wishlist': 'Wishlist',
      'music_player': 'Music Player',
      'shopping_cart': 'Shopping Cart',
      'cart_empty': 'Your cart is empty',
      'checkout': 'Proceed to Checkout',
      'place_order': 'Place Order',
      'order_placed': 'Order placed! Send payment to the seller.',
      'order_failed': 'Order failed',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'processing': 'Processing',
      'shipped': 'Shipped',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'edit_profile': 'Edit Profile',
      'display_name': 'Display Name',
      'bio': 'Bio',
      'phone': 'Phone Number',
      'payment_methods': 'Payment Methods',
      'add_payment': 'Add',
      'select_payment': 'Select Payment Method',
      'total_amount': 'Total',
      'chat_with_seller': 'Chat with Seller',
      'chat_first':
          'You need to chat with the seller before buying. Start a conversation?',
      'chat_now': 'Chat Now',
      'send': 'Send',
      'type_message': 'Type a message...',
      'no_conversations': 'No conversations yet',
      'waiting_for_user': 'Waiting for other user...',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'switch_camera': 'Switch',
      'speaker': 'Speaker',
      'earpiece': 'Earpiece',
      'end_call': 'End',
      'search_products': 'Search products...',
      'filter': 'Filter',
      'price_range': 'Price Range',
      'apply': 'Apply',
      'clear': 'Clear',
      'about': 'About Soko Langu',
      'version': 'Version 1.0.0',
      'help': 'Help Center',
      'privacy': 'Privacy & Security',
      'appearance': 'Appearance',
      'notifications': 'Notifications',
      'push_notifications': 'Push Notifications',
      'language': 'Language',
      'currency': 'Currency',
      'account': 'Account',
      'support': 'Support',
      'contact': 'Contact: langusoko@gmail.com',
      'coming_soon': 'Coming soon',
      'error': 'Error',
      'success': 'Success',
      'required': 'Required',
      'online': 'Online',
      'offline': 'Offline',
      'last_seen': 'Last seen',
      'just_now': 'just now',
      'minutes_ago': 'minutes ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'allow': 'Allow',
      'deny': 'Deny',
      'permission_required': 'Permission Required',
      'permission_camera': 'Camera access is needed for video calls',
      'permission_microphone':
          'Microphone access is needed for voice calls and voice messages',
      'permission_storage': 'Storage access is needed to read music files',
      'permission_photos': 'Photo access is needed to share images',
      'auto_lock': 'Auto-Lock',
      'auto_lock_desc': 'Lock app after inactivity',
      'auto_lock_time': 'Lock after',
      'minutes': 'minutes',
      'never': 'Never',
      'enter_pin': 'Enter PIN',
      'wrong_pin': 'Wrong PIN',
      'set_pin': 'Set PIN',
      'confirm_pin': 'Confirm PIN',
      'pin_mismatch': 'PINs do not match',
      'pin_updated': 'PIN updated successfully',
      'payment_gateway': 'Payment Gateway',
      'google_pay': 'Google Pay',
      'api_key': 'API Key',
      'api_secret': 'API Secret',
      'test_mode': 'Test Mode',
      'live_mode': 'Live Mode',
      'save_settings': 'Save Settings',
      'settings_saved': 'Settings saved',
      'select_language': 'Select Language',
      'select_currency': 'Select Currency',
      'no_songs': 'No songs found',
      'permission_storage_desc': 'Permission to read storage is required',
      'grant_permission': 'Grant Permission',
      'product_images': 'Product Images',
      'product_name': 'Product Name',
      'price': 'Price',
      'subcategory': 'Subcategory',
      'new': 'New',
      'used': 'Used',
      'refurbished': 'Refurbished',
      'add_product': 'Uza Bidhaa',
      'update_product': 'Edit Product',
      'product_added': 'Product added!',
      'product_updated': 'Product updated!',
      'delete_product': 'Delete Product',
      'delete_confirm': 'Delete this product permanently?',
      'product_deleted': 'Product deleted',
      'no_ads': "You haven't listed any products yet",
      'upload_image': 'Please add at least one image',
      'copied': 'Copied to clipboard',
      'share': 'Share',
      'sold': 'sold',
      'reviews_count': 'reviews',
      'no_reviews': 'No reviews yet',
      'login_required': 'Login required',
      'email_verification_sent': 'Verification email sent! Check your inbox.',
      'check_email': 'Check your email for verification link',
      'use_different_account': 'Use a different account',
      'forgot_password': 'Forgot password?',
      'reset_password': 'Reset Password',
      'reset_sent': 'Password reset email sent',
      'no_name': 'No Name',
      'no_email': 'No Email',
      'unlock': 'Unlock',
      'no_payment_methods': 'Seller has not set payment methods yet.',
      'dashboard': 'Dashboard',
      'revenue': 'Revenue',
      'total_orders': 'Total Orders',
      'total_products': 'Total Products',
      'recent_orders': 'Recent Orders',
      'mark_as': 'Mark as',
      'no_received_orders': 'No orders received yet',
      'no_notifications': 'No notifications yet',
      'use_biometric': 'Fingerprint / Face Unlock',
      'use_biometric_sub': 'Use fingerprint or face to unlock',
      'welcome_back': 'Welcome back!',
      'fill_fields': 'Fill all fields',
      'enter_email': 'Enter your email first',
      'continue_google': 'Continue with Google',
      'no_account': "Don't have an account? ",
      'join_soko': 'Join Soko Langu',
      'create_account': 'Create your account',
      'full_name': 'Full Name',
      'account_created': 'Account created!',
      'login_prompt': 'Already have account? Login',
      'no_orders': 'No orders yet',
      'order': 'Order',
      'ordered': 'Ordered',
      'tagline': 'Your Marketplace, Your Language',
      'version_label': 'Version',
      'developer': 'Developer',
      'team_name': 'Soko Langu Team',
      'contact_label': 'Contact',
      'features': 'Features',
      'features_text':
          'Online Marketplace\nChat & Video Calls\nMulti-language & Currency Support',
      'copyright': '© 2026 Soko Langu. All rights reserved.',
      'photo_updated': 'Profile photo updated!',
      'products': 'Products',
      'followers': 'Followers',
      'following': 'Following',
      'follow': 'Follow',
      'home': 'Home',
      'send_photo': 'Send Photo',
      'voice': 'Voice',
      'checkout_failed': 'Checkout failed',
      'replied_to': 'Re: ',
      'unlock_app': 'Unlock Soko Langu',
      'enroll_biometric': 'Scan your fingerprint or face to enable unlock',
      'added_to_cart': 'Added to cart!',
      'delete_failed': 'Failed to delete',
      'premium': 'Premium',
      'go_premium': 'Go Premium',
      'premium_active': 'Premium Active',
      'premium_no_ads': 'No ads — enjoy an ad-free experience',
      'premium_subtitle': 'Remove ads and get exclusive features',
      'premium_benefits':
          'Upgrade to Premium to enjoy:\n\n✓ No ads anywhere in the app\n✓ Priority support\n✓ Exclusive features coming soon',
      'upgrade_now': 'Upgrade Now',
      'premium_upgraded': 'Welcome to Premium! No more ads.',
      'premium_title': 'Upgrade to Premium',
      'premium_feature_support': 'Priority customer support',
      'premium_feature_badges': 'Exclusive badges & features',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'per_month': '/mo',
      'per_year': '/yr',
      'payment_method': 'Payment Method',
      'enter_phone': 'Enter your phone number',
      'phone_number': 'Phone Number',
      'phone_hint': 'e.g. 2557XXXXXXXX',
      'subscribe_now': 'Subscribe Now',
      'payment_failed': 'Payment failed. Please try again.',
      'welcome_premium': 'Welcome to Premium!',
      'help_payment_mongike':
          'Payments are securely processed through Mongike. Pay using M-Pesa, Airtel Money, Mixx by Yas, or Halopesa.',
      'payment_secure': 'Secure payment via Mongike',
      'upgrade_account': 'Upgrade Account',
      'silver': 'Silver',
      'free': 'Free',
      'silver_feature_visibility':
          'Your products appear FIRST in search results',
      'silver_feature_badge': 'Silver seller badge on your profile & products',
      'silver_feature_support': 'Priority customer support',
      'silver_welcome_msg': 'Your products now appear first in search results!',
      'account_tier': 'Account Tier',
      'welcome_soko': 'Welcome to Soko Langu!',
      'choose_account': 'Choose your account type to get started',
      'forever': 'Forever',
      'free_feature_list': 'List & sell products',
      'free_feature_ads': 'Ads are shown',
      'continue_free': 'Continue with Free',
      'skip_choose': 'Skip, start with Free',
      'plan_compare': 'Plan Features',
      'wallpaper': 'Wallpaper',
      'wallpaper_sub': 'Customize your app background',
      'choose_wallpaper': 'Choose from Gallery',
      'remove_wallpaper': 'Remove Wallpaper',
      'no_wallpaper': 'No wallpaper set',
      'admin_dashboard': 'Admin Dashboard',
      'transaction_history': 'Transaction History',
      'processing_fee': 'Processing Fee',
      'platform_fee': 'Platform Fee',
      'total_fee': 'Total Fee',
      'total_to_pay': 'Total to Pay',
      'seller_receives': 'Seller Receives',
      'payment_successful': 'Payment Successful!',
      'payment_processed': 'Your payment has been processed.',
      'back_to_home': 'Back to Home',
      'transaction_fee_agreement': 'Transaction Fee Agreement',
      'fee_explanation':
          'This transaction includes a 5% service fee (3% processing fee + 2% platform commission).',
      'allow_continue': 'Allow & Continue',
      'deny_cancel': 'Deny & Cancel',
      'transaction_cancelled': 'Transaction cancelled. No charges were made.',
      'searching_soko': 'Searching soko_langu...',
      'loading_results': 'Loading results from soko_langu marketplace...',
      'no_results_soko': 'No results found in soko_langu',
      'try_different': 'Try different keywords or browse categories',
      'trouble_connecting':
          'soko_langu is having trouble connecting. Please try again.',
      'try_again': 'Try Again',
      'total_sales': 'Total Sales',
      'amount_received': 'Amount Received',
      'admin_earnings': 'Admin Earnings',
      'set_username': 'Set username',
      'username_taken': 'Username already taken',
      'free_plan_current': 'You are currently on the Free plan',
      'plan_active': 'Your plan is active',
      'received_orders': 'Orders Received',
      'received': 'Received',
    },
  };

  Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'sw';
  }

  Future<void> setLanguage(String code) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, code);
  }

  Future<String> getCurrency() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_currencyKey) ?? 'TZS';
  }

  Future<void> setCurrency(String code) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_currencyKey, code);
  }

  String getCurrencySymbol(String code) {
    return supportedCurrencies[code]?['symbol'] ?? 'TSh';
  }

  static String translate(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']![key] ?? key;
  }
}
