import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static const String _languageKey = 'language_code';
  static const String _currencyKey = 'currency';

  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'sw': 'Swahili',
  };

  static const Map<String, Map<String, String>> supportedCurrencies = {
    'TZS': {'symbol': 'TSh', 'name': 'Tanzanian Shilling'},
    'USD': {'symbol': r'$', 'name': 'US Dollar'},
    'EUR': {'symbol': '€', 'name': 'Euro'},
    'GBP': {'symbol': '£', 'name': 'British Pound'},
    'KES': {'symbol': 'KSh', 'name': 'Kenyan Shilling'},
    'UGX': {'symbol': 'USh', 'name': 'Ugandan Shilling'},
    'NGN': {'symbol': '₦', 'name': 'Nigerian Naira'},
    'ZAR': {'symbol': 'R', 'name': 'South African Rand'},
    'CNY': {'symbol': '¥', 'name': 'Chinese Yuan'},
  };

  static const Map<String, Map<String, String>> translations = {
    'sw': {
      'app_name': 'Soko Langu',
      'login': 'Ingia',
      'register': 'Fungua Akaunti',
      'email': 'Barua Pepe',
      'password': 'Nywila',
      'categories': 'Kategoria',
      'latest_products': 'Bidhaa Mpya',
      'search': 'Tafuta',
      'sell_product': 'Uza Bidhaa',
      'profile': 'Wasifu',
      'settings': 'Mipangilio',
      'chats': 'Mazungumzo',
      'logout': 'Toka',
      'add_to_cart': 'Ongeza kwenye Rukwama',
      'buy_now': 'Nunua Sasa',
      'quantity': 'Idadi',
      'total': 'Jumla',
      'no_products': 'Hakuna bidhaa bado',
      'no_categories': 'Hakuna kategoria bado',
      'product_detail': 'Maelezo ya Bidhaa',
      'description': 'Maelezo',
      'details': 'Maelezo',
      'category': 'Kategoria',
      'brand': 'Chapa',
      'condition': 'Hali',
      'location': 'Mahali',
      'stock': 'Hifadhi',
      'wholesale': 'Jumla',
      'seller': 'Muuzaji',
      'view_store': 'Tazama Duka',
      'chat': 'Zungumza',
      'reviews': 'Maoni',
      'write_review': 'Andika Maoni',
      'rating': 'Ukadiriaji',
      'comment': 'Maoni',
      'submit': 'Wasilisha',
      'cancel': 'Ghairi',
      'save': 'Hifadhi',
      'delete': 'Futa',
      'edit': 'Hariri',
      'my_ads': 'Matangazo Yangu',
      'my_orders': 'Maagizo Yangu',
      'wishlist': 'Orodha ya Tamaa',
      'music_player': 'Kicheza Muziki',
      'shopping_cart': 'Rukwama ya Manunuzi',
      'cart_empty': 'Rukwama yako haina kitu',
      'checkout': 'Nenda kwa Malipo',
      'place_order': 'Weka Agizo',
      'order_placed': 'Agizo limewekwa! Tuma malipo kwa muuzaji.',
      'order_failed': 'Agizo limeshindwa',
      'pending': 'Inasubiri',
      'confirmed': 'Imethibitishwa',
      'processing': 'Inachakatwa',
      'shipped': 'Imesafirishwa',
      'delivered': 'Imefikishwa',
      'cancelled': 'Imeghairiwa',
      'edit_profile': 'Hariri Wasifu',
      'display_name': 'Jina la Kuonyesha',
      'bio': 'Maelezo',
      'phone': 'Namba ya Simu',
      'payment_methods': 'Njia za Malipo',
      'add_payment': 'Ongeza',
      'select_payment': 'Chagua Njia ya Malipo',
      'total_amount': 'Jumla',
      'chat_with_seller': 'Zungumza na Muuzaji',
      'send': 'Tuma',
      'type_message': 'Andika ujumbe...',
      'no_conversations': 'Hakuna mazungumzo bado',
      'no_notifications': 'Hakuna arifa bado',
      'search_products': 'Tafuta bidhaa...',
      'filter': 'Chuja',
      'price_range': 'Bei',
      'apply': 'Tekeleza',
      'clear': 'Futa',
      'about': 'Kuhusu Soko Langu',
      'version': 'Toleo 1.0.0',
      'help': 'Msaada',
      'appearance': 'Mwonekano',

      'notifications': 'Arifa',
      'push_notifications': 'Arifa za Push',
      'language': 'Lugha',
      'currency': 'Sarafu',
      'account': 'Akaunti',
      'support': 'Msaada',
      'contact': 'Wasiliana: langusoko@gmail.com',
      'online': 'Mtandaoni',
      'offline': 'Nje ya mtandao',
      'last_seen': 'Imeonekana mwisho',
      'just_now': 'sasa hivi',
      'minutes_ago': 'dakika zilizopita',
      'set_pin': 'Weka PIN',
      'confirm_pin': 'Thibitisha PIN',
      'pin_mismatch': 'PIN hazilingani',
      'pin_updated': 'PIN imesasishwa',
      'premium': 'Premium',
      'go_premium': 'Pata Premium',
      'premium_active': 'Premium Imewashwa',
      'premium_no_ads': 'Hakuna matangazo',
      'premium_subtitle': 'Ondoa matangazo na upate vipengele vya kipekee',
      'premium_benefits':
          'Pata Premium kufurahia:\n\n✓ Hakuna matangazo\n✓ Msaada wa haraka\n✓ Vipengele vya kipekee',
      'upgrade_now': 'Pata Sasa',
      'premium_upgraded': 'Karibu Premium! Hakuna matangazo tena.',
      'premium_title': 'Pata Premium',
      'premium_feature_support': 'Msaada wa haraka kwa wateja',
      'premium_feature_badges': 'Beji na vipengele vya kipekee',
      'monthly': 'Kila Mwezi',
      'yearly': 'Kwa Mwaka',
      'per_month': '/mwezi',
      'per_year': '/mwaka',
      'payment_method': 'Njia ya Malipo',
      'enter_phone': 'Ingiza namba yako ya simu',
      'phone_number': 'Namba ya Simu',
      'phone_hint': 'mfano 2557XXXXXXXX',
      'subscribe_now': 'Jiandikisha Sasa',
      'payment_failed': 'Malipo yameshindwa. Jaribu tena.',
      'welcome_premium': 'Karibu Premium!',
      'help_payment_mongike':
          'Malipo yanafanywa kwa njia salama kupitia Mongike. Tuma malipo kwa kutumia M-Pesa, Airtel Money, Mixx by Yas, au Halopesa.',
      'payment_secure': 'Malipo salama kupitia Mongike',
      'upgrade_account': 'Pata Akaunti',
      'silver': 'Silver',
      'free': 'Bure',
      'silver_feature_visibility':
          'Bidhaa zako zinaonekana KWANZA kwenye matokeo',
      'silver_feature_badge': 'Beji ya Silver kwenye wasifu wako',
      'silver_feature_support': 'Msaada wa haraka kwa wateja',
      'silver_welcome_msg':
          'Bidhaa zako sasa zinaonekana kwanza kwenye matokeo!',
      'account_tier': 'Aina ya Akaunti',
      'welcome_soko': 'Karibu Soko Langu!',
      'choose_account': 'Chagua aina ya akaunti yako',
      'forever': 'Daima',
      'free_feature_list': 'Orodhesha na uze bidhaa',
      'free_feature_ads': 'Matangazo yanaonekana',
      'continue_free': 'Endelea na Bure',
      'skip_choose': 'Nitaamua baadaye, nianze na Bure',

      'plan_compare': 'Vipengele',
      'wallpaper': 'Picha ya Mandhari',
      'wallpaper_sub': 'Badilisha mandhari ya app yako',
      'choose_wallpaper': 'Chagua kutoka Kwenye Picha',
      'remove_wallpaper': 'Ondoa Picha',
      'no_wallpaper': 'Hakuna picha iliyowekwa',
      'admin_dashboard': 'Admin Dashboard',
      'transaction_history': 'Historia ya Malipo',
      'processing_fee': 'Ada ya Kuchakata',
      'platform_fee': 'Ada ya Jemala',
      'total_fee': 'Jumla ya Ada',
      'total_to_pay': 'Jumla ya Kulipa',
      'seller_receives': 'Muuzaji Anapokea',
      'payment_successful': 'Malipo Yamekamilika!',
      'payment_processed': 'Malipo yako yamechakatwa.',
      'back_to_home': 'Rudi Nyumbani',
      'transaction_fee_agreement': 'Mkataba wa Ada ya Ununuzi',
      'fee_explanation':
          'Ununuzi huu unajumuisha ada ya 5% (3% ada ya kuchakata + 2% ada ya jemala).',
      'allow_continue': 'Ruhusu na Endelea',
      'deny_cancel': 'Kataa na Ghairi',
      'transaction_cancelled':
          'Ununuzi umetenguliwa. Hakuna malipo yaliyotozwa.',
      'searching_soko': 'Inatafuta soko_langu...',
      'loading_results': 'Inapakia matokeo kutoka soko_langu...',
      'loading': 'Inapakia...',
      'no_results_soko': 'Hakuna matokeo katika soko_langu',
      'try_different': 'Jaribu maneno tofauti au vinjari kategoria',
      'trouble_connecting':
          'soko_langu inatatizika kuunganisha. Tafadhali jaribu tena.',
      'try_again': 'Jaribu Tena',

      'total_sales': 'Mauzo Jumla',
      'amount_received': 'Kiasi Kilichopokelewa',
      'admin_earnings': 'Mapato ya Msimamizi',
      'set_username': 'Weka jina la mtumiaji',
      'username_taken': 'Jina hili la mtumiaji tayari linatumika',
      'free_plan_current': 'Hivi sasa uko kwenye mpango wa Bure',
      'plan_active': 'Mpango wako umewashwa',
      'received_orders': 'Maagizo Niliyopokea',
      'received': 'Nimepokea',
      'app_locked': 'App Imefungwa',
      'enter_pin_unlock': 'Weka namba ya siri ili kufungua',
      'or_use': 'au tumia',
      'customize_shop': 'Customize Shop',
      'shop_customization': 'Customize Your Shop',
      'shop_banner': 'Shop Banner',
      'shop_banner_hint': 'Upload a banner image for your shop',
      'shop_accent_color': 'Accent Color',
      'shop_accent_color_hint': 'Choose a color theme for your shop',
      'shop_banner_color': 'Banner Background Color',
      'premium_feature_locked': 'Premium Feature',
      'premium_only': 'Premium only',
      'upgrade_to_customize':
          'Upgrade to Premium or Silver to customize your shop',
      'storefront_updated': 'Shop appearance saved!',
      'shop_premium_banner': 'Premium Shop',
      'shop_silver_banner': 'Silver Shop',
      'create_playlist': 'Unda Orodha',
      'playlist_name': 'Jina la Orodha',
      'playlist_name_hint': 'Weka jina la orodha',
      'select_songs': 'Chagua Nyimbo',
      'no_songs_selected': 'Tafadhali chagua angalau wimbo mmoja',
      'playlist_created': 'Orodha imeundwa!',
      'all_songs': 'Nyimbo Zote',
      'search_songs': 'Tafuta nyimbo...',
      'delete_message': 'Futa Ujumbe',
      'delete_message_confirm': 'Futa ujumbe huu?',
      'editing_message': 'Inahariri ujumbe',
      'message_deleted': 'Ujumbe huu umefutwa',
      'comments': 'Maoni',
      'write_comment': 'Andika Maoni',
      'no_comments_yet': 'Hakuna maoni bado. Kuwa wa kwanza!',
      'comment_hint': 'Andika maoni...',
      'replies': 'majibu',
      'reply': 'Jibu',
      'view_replies': 'Tazama majibu',
      'delete_conversation': 'Futa Mazungumzo',
      'delete_conversation_confirm':
          'Una uhakika unataka kufuta mazungumzo haya? Haliwezi kutenguliwa.',
      'pay_now': 'Lipa Sasa',

      'see_all': 'Ona Zote',
      'all': 'Zote',
      'live_now': 'Moja kwa Moja Sasa',
      'go_back': 'Rudi',
      'unknown': 'Haijulikani',
      'no_results': 'Hakuna Matokeo',
      'yes': 'Ndiyo',
      'no': 'Hapana',
      'ok': 'Sawa',
      'added_to_wishlist': 'Imeongezwa kwenye Orodha ya Tamaa',
      'removed_from_wishlist': 'Imeondolewa kwenye Orodha ya Tamaa',
      'variants': 'Aina Mbalimbali',
      'selected': 'Imechaguliwa',
      'price_adjustment': 'Marekebisho ya Bei',
      'available': 'Inapatikana',
      'units': 'vitengo',
      'with_variant': 'Kwa aina:',
      'check_out_on': 'Angalia kwenye Soko Langu!',
      'no_products_category': 'Hakuna bidhaa katika kategoria hii',
      'name_eg': 'Jina (mf. Ukubwa, Rangi)',
      'value_eg': 'Thamani (mf. Kubwa, Nyekundu)',
      'price_adj_label': 'Bei ±',
      'verify_email_title': 'Thibitisha Barua Pepe',
      'verify_email_sent':
          'Tumekutumia barua pepe ya uthibitisho. Angalia kikasha chako.',
      'verified_continue': 'Nimethibitisha - Endelea',
      'resend_verification': 'Tuma Tena Barua Pepe',
      'email_not_verified':
          'Barua pepe bado haijathibitishwa. Tafadhali thibitisha kwanza.',
      'wishlist_empty': 'Orodha yako ya tamaa haina kitu',
      'choose_username': 'chagua jina la kipekee la mtumiaji',
      'username_required': 'Jina la mtumiaji linahitajika',
      'no_spaces': 'Hakuna nafasi zinazoruhusiwa',
      'min_chars': 'Angalau herufi 3',
      'mood': 'Hali',
      'how_feeling': 'Unaje?',
      'method': 'Njia',
      'number': 'Namba',
      'payment_number': 'Namba ya malipo',
      'tell_about': 'Tuambie kukuhusu...',
      'get_location': 'Pata mahali nilipo',
      'location_disabled': 'Huduma za mahali zimezimwa',
      'location_denied': 'Ruhusa ya mahali imekataliwa kabisa',
      'profile_saved': 'Wasifu umehifadhiwa!',
      'call_history': 'Historia ya Simu',
      'my_media': 'Vyombo Vyangu',
      'buy_coins': 'Nunua Coins',
      'playlists': 'Orodha za Nyimbo',
      'sales': 'Mauzo',
      'message': 'Tuma Ujumbe',
      'complete_payment': 'Kamilisha Malipo',
      'failed_payment_init': 'Imeshindwa kuanzisha malipo. Jaribu tena.',
      'payment_confirmed_activating': 'Malipo yamethibitishwa! Inawasha...',
      'pay_mongike': 'Lipa kwa Mongike',
      'streamer_earnings': 'Mapato ya Mtangazaji',
      'boost_listing': 'Kuza Matangazo',
      'pay_boost': 'Lipa TZS 5,000',
      'mpesa_phone': 'Namba yako ya M-Pesa/Airtel',
      'total_gifts_earned': 'Jumla ya Zawadi Zilizopatikana',
      'next_payout': 'Malipo Yajayo',
      'your_earnings_70': 'Mapato Yako (70%)',
      'platform_fee_30': 'Ada ya Jemala (30%)',
      'mongike_fee': 'Ada ya Mongike',
      'you_receive': 'Unapokea',
      'payout_end_month': 'Malipo yanafanywa mwishoni mwa mwezi',
      'min_payout': 'Kiwango cha chini TZS 4,000 kinahitajika kwa malipo',
      'no_gifts': 'Hakuna zawadi zilizopokelewa bado',
      'days': 'siku',
      'earned': 'umepata',
      'coins': 'coins',
      'no_messages_yet': 'Hakuna ujumbe bado',
      'start_conversation': 'Anza mazungumzo...',
      'call_failed': 'Simu imeshindwa:',
      'call_ended': 'Simu imekamilika',
      'calling': 'Inapiga...',
      'typing': 'anaandika...',
      'edited': 'imehaririwa',
      'chat_empty': 'Zungumza na wauzaji kuona mazungumzo hapa',
      'send_payment_to_sellers': 'Tuma Malipo kwa Wauzaji',
      'seller_label': 'Muuzaji: ',
      'subtotal': 'Jumla Ndogo',
      'phone_label': 'Simu: ',
      'send_money_instructions':
          'Tuma pesa kwa kila muuzaji kupitia M-Pesa au Airtel Money',
      'orders_placed': 'maagizo yamewekwa!',
      'flip': 'Geuza',
      'connected': 'Imeunganishwa',
      'ringing': 'Inaita...',
      'connecting': 'Inaunganisha...',
      'incoming_video': 'Simu ya Video Inayoingia...',
      'incoming_voice': 'Simu ya Sauti Inayoingia...',
      'decline': 'Kataa',
      'accept': 'Kubali',
      'not_logged_in': 'Hujaingia',
      'no_call_history': 'Hakuna historia ya simu',
      'missed': 'Haikujibiwa',
      'declined': 'Imekataliwa',
      'outgoing_video': 'Simu ya Video Inayotoka',
      'outgoing_voice': 'Simu ya Sauti Inayotoka',
      'incoming_video_call': 'Simu ya Video Inayoingia',
      'incoming_voice_call': 'Simu ya Sauti Inayoingia',
      'send_message': 'Tuma ujumbe...',
      'stream_ended': 'Mtiririko Umekwisha',
      'stream_ended_subtitle': 'mtiririko wake umekwisha.',
      'sent_gift': 'alituma zawadi',
      'gift_shop': 'Zawadi',
      'buy': 'Nunua',
      'sent': 'Imetumwa',
      'preparing_camera': 'Inaandaa kamera...',
      'camera': 'Kamera',
      'off': 'Zima',
      'starting': 'Inaanza...',
      'go_live_now': 'Anza Moja kwa Moja Sasa',
      'chat_viewers': 'Zungumza na watazamaji...',
      'end_live': 'Maliza Moja kwa Moja?',
      'go_to_dashboard': 'Nenda kwenye Dashibodi',
      'failed_start_live': 'Imeshindwa kuanza moja kwa moja:',
      'share_live':
          'Tazama mtiririko wangu wa moja kwa moja kwenye Soko Langu!',
      'live_feed': 'Mtiririko Moja kwa Moja',
      'no_live_now': 'Hakuna mtiririko moja kwa moja sasa',
      'no_live_subtitle': 'Wauzaji huanza moja kwa moja wanapokuwa tayari',
      'selling': 'Anauza ',
      'watch': 'Tazama',
      'direct_transfer': 'Uhamisho wa Moja kwa Moja',
      'send_to_seller_directly': 'Tuma kwa muuzaji moja kwa moja',
      'no_commission': 'Hakuna ada',
      'mongike': 'Mongike',
      'automated_payment': 'Malipo ya Kiotomatiki',
      'service_fee_5': 'Ada ya huduma 5%',
      'send_payment_to': 'Tuma malipo kwa ',
      'payment_methods_label': 'Njia za Malipo:',
      'send_money_mpesa':
          'Tuma pesa kupitia M-Pesa, Airtel Money, Mixx, au Halopesa',
      'pay_via_mongike': 'Lipa kupitia Mongike',
      'enter_phone_mpesa': 'Ingiza namba yako ya M-Pesa / Airtel',
      'product': 'Bidhaa',
      'service_fee': 'Ada ya Huduma (5%)',
      'subtotal_label': 'Jumla Ndogo',
      'check_phone_ussd': 'Angalia simu yako kwa maagizo ya USSD',
      'valid_phone_required': 'Weka namba halali ya M-Pesa au Airtel',
      'no_order_id': 'Hakuna ID ya agizo ilirudishwa',
      'waiting_payment': 'Inasubiri Malipo',
      'paid_button': 'Nimelipa - TZS ',
      'amount_paid': 'Kiasi Kilicholipwa',
      'transaction_id': 'Kitambulisho cha Muamala',
      'status': 'Hali',
      'completed': 'Imekamilika',
      'confirmation_message':
          'Ujumbe wa uthibitisho utatumwa kwa namba yako ya simu',
      'your_balance': 'Salio Lako: ',
      'coins_added': ' coins zimeongezwa!',
      'payment_prompt_sent': 'Maagizo ya malipo yametumwa kwenye simu yako',
      'add_phone_first':
          'Tafadhali weka namba yako ya simu kwenye Mipangilio ya Wasifu kwanza',
      'bonus': 'bonasi',
      'complete_purchase': 'Kamilisha Ununuzi',
      'buyer': 'Mnunuzi: ',
      'confirm_received_payment': 'Thibitisha - Nimepokea Malipo',
      'waiting_seller_confirm': 'Inasubiri muuzaji kuthibitisha malipo',
      'payment_confirmed_success':
          'Malipo yamethibitishwa! Agizo limekamilika.',
      'confirm_failed': 'Imeshindwa kuthibitisha:',
      'share_experience': 'Shiriki uzoefu wako...',
      'rate': 'Kadiria',
      'review_submitted': 'Maoni yamewasilishwa!',
      'access_denied': 'Hauruhusiwi',
      'users': 'Watumiaji',
      'orders': 'Maagizo',
      'stats': 'Takwimu',
      'search_users': 'Tafuta watumiaji...',
      'set_silver': 'Weka Silver',
      'set_premium': 'Weka Premium',
      'set_free': 'Weka Bure',
      'toggle_admin': 'Badilisha Admin',
      'unsuspend': 'Ruhusu',
      'suspend': 'Simamisha',
      'suspended_label': ' (Imesimamishwa)',
      'tier_label': 'Daraja: ',
      'deactivate': 'Zima',
      'activate': 'Washa',
      'remove_featured': 'Ondoa Ilipendekezwa',
      'mark_featured': 'Weka Ilipendekezwa',
      'product_updated_action': 'Bidhaa imesasishwa:',
      'order_updated': 'Agizo limesasishwa hadi ',
      'platform_earnings': 'Mapato ya Jemala',
      'total_earnings': 'Jumla ya Mapato',
      'today': 'Leo',
      'this_month': 'Mwezi Huu',
      'transactions': 'Miamala',
      'revenue_breakdown': 'Mgawanyo wa Mapato',
      'platform_commission_2': 'Ada ya Jemala 2%',
      'subscription_income': 'Mapato ya Usajili',
      'active_users': 'Watumiaji Hai',
      'available_balance': 'Salio Linalopatikana',
      'total_earned_label': 'Jumla Uliyopata: ',
      'todays_views': 'Matazamio ya Leo',
      'rev_share': 'Sehemu ya Mapato',
      'recent_transactions': 'Miamala ya Karibuni',
      'no_transactions': 'Hakuna miamala bado',
      'error_loading_wallet': 'Hitilafu kupakia pochi: ',
      'error_loading_transactions': 'Hitilafu kupakia miamala',
      'featured': 'Iliyopendekezwa',
      'write': 'Andika',
      'ad': 'Tangazo',
      'live_tab': 'Moja kwa Moja',
      'retry': 'Jaribu Tena',
      'now_playing': 'Inacheza Sasa',
      'no_song_playing': 'Hakuna wimbo unaocheza',
      'unknown_artist': 'Msanii Asiyejulikana',
      'songs': 'Nyimbo',
      'audio': 'Sauti',
      'video': 'Video',
      'add_to_playlist': 'Ongeza kwenye Orodha',
      'no_playlists': 'Hakuna orodha bado',
      'new_playlist': 'Orodha Mpya',
      'create': 'Unda',
      'play_all': 'Cheza Zote',
      'delete_playlist': 'Futa Orodha',
      'delete_playlist_confirm': 'Una uhakika unataka kufuta orodha hii?',
      'no_songs_in_playlist': 'Hakuna nyimbo kwenye orodha hii',
      'like': 'Penda',
      'failed_to_load_video': 'Imeshindwa kupakia video',
      'select_all': 'Chagua Zote',
      'deselect_all': 'Ondoa Uchaguzi Wote',
      'no_videos': 'Hakuna video',
      'open': 'Fungua',
      'allow_access': 'Ruhusu Ufikiaji',
      'open_settings': 'Fungua Mipangilio',
      'permission_denied_text': 'Ruhusa imekataliwa. Fungua mipangilio ya app.',
      'failed_to_load': 'Imeshindwa kupakia',
      'no_reviews_yet': 'Hakuna maoni bado. Kuwa wa kwanza!',
      'chat_first':
          'Unahitaji kuzungumza na muuzaji kabla ya kununua. Anza mazungumzo?',
      'chat_now': 'Zungumza Sasa',
      'waiting_for_user': 'Inasubiri mtumiaji mwingine...',
      'coming_soon': 'Inakuja hivi karibuni',
      'hours_ago': 'saa zilizopita',
      'days_ago': 'siku zilizopita',
      'allow': 'Ruhusu',
      'deny': 'Kataa',
      'permission_required': 'Ruhusa Inahitajika',
      'permission_camera': 'Ruhusa ya kamera inahitajika kwa simu za video',
      'permission_microphone':
          'Ruhusa ya maikrofoni inahitajika kwa simu za sauti',
      'permission_storage':
          'Ruhusa ya kuhifadhi inahitajika kusoma faili za muziki',
      'permission_photos': 'Ruhusa ya picha inahitajika kushiriki picha',
      'auto_lock': 'Kuji-Funga Kiotomatiki',
      'auto_lock_desc': 'Funga app baada ya kutotumika',
      'auto_lock_time': 'Funga baada ya',
      'never': 'Kamwe',
      'enter_pin': 'Weka PIN',
      'wrong_pin': 'PIN si sahihi',
      'no_songs': 'Hakuna nyimbo zilizopatikana',
      'permission_storage_desc': 'Ruhusa ya kusoma hifadhi inahitajika',
      'grant_permission': 'Toa Ruhusa',
      'product_images': 'Picha za Bidhaa',
      'product_name': 'Jina la Bidhaa',
      'new': 'Mpya',
      'used': 'Imetumika',
      'refurbished': 'Imerekebishwa',
      'add_product': 'Uza Bidhaa',
      'update_product': 'Hariri Bidhaa',
      'product_added': 'Bidhaa imeongezwa!',
      'product_updated': 'Bidhaa imesasishwa!',
      'delete_product': 'Futa Bidhaa',
      'delete_confirm': 'Futa bidhaa hii kabisa?',
      'product_deleted': 'Bidhaa imefutwa',
      'no_ads': 'Hujaja bidhaa yoyote bado',
      'upload_image': 'Tafadhali ongeza angalau picha moja',
      'copied': 'Imenakiliwa kwenye clipboard',
      'sold': 'zimeuzwa',
      'reviews_count': 'maoni',
      'no_reviews': 'Hakuna maoni bado',
      'login_required': 'Ingia kwanza',
      'check_email': 'Angalia barua pepe yako kwa kiungo cha uthibitisho',
      'forgot_password': 'Umesahau nywila?',
      'reset_password': 'Weka upya nywila',
      'reset_sent': 'Barua pepe ya kuweka upya nywila imetumwa',
      'no_name': 'Hakuna Jina',
      'no_email': 'Hakuna Barua Pepe',
      'unlock': 'Fungua',
      'no_payment_methods': 'Muuzaji hajaweka njia za malipo bado.',
      'dashboard': 'Dashibodi',
      'total_orders': 'Jumla ya Maagizo',
      'total_products': 'Jumla ya Bidhaa',
      'recent_orders': 'Maagizo ya Karibuni',
      'mark_as': 'Weka kama',
      'welcome_back': 'Karibu tena!',
      'fill_fields': 'Jaza sehemu zote',
      'enter_email': 'Weka barua pepe yako kwanza',
      'continue_google': 'Endelea na Google',
      'no_account': 'Huna akaunti? ',
      'join_soko': 'Jiunge na Soko Langu',
      'create_account': 'Fungua akaunti yako',
      'full_name': 'Jina Kamili',
      'account_created': 'Akaunti imeundwa!',
      'login_prompt': 'Tayari una akaunti? Ingia',
      'no_orders': 'Hakuna maagizo bado',
      'order': 'Agizo',
      'ordered': 'Imeagizwa',
      'tagline': 'Soko Lako, Lugha Yako',
      'version_label': 'Toleo',
      'developer': 'Msanidi',
      'team_name': 'Timu ya Soko Langu',
      'contact_label': 'Wasiliana',
      'features': 'Vipengele',
      'features_text':
          'Soko la Mtandaoni\nMazungumzo na Simu za Video\nMsaada wa Lugha Nyingi na Sarafu',
      'copyright': '© 2026 Soko Langu. Haki zote zimehifadhiwa.',
      'photo_updated': 'Picha ya wasifu imesasishwa!',
      'followers': 'Wafuasi',
      'following': 'Anafuata',
      'follow': 'Fuata',
      'home': 'Nyumbani',
      'send_photo': 'Tuma Picha',
      'voice': 'Sauti',
      'checkout_failed': 'Malipo yameshindwa',
      'replied_to': 'Re: ',
      'unlock_app': 'Fungua Soko Langu',
      'added_to_cart': 'Imeongezwa kwenye rukwama!',
      'delete_failed': 'Imeshindwa kufuta',
      'earn_coins': 'Pata Coins',
      'your_coins': 'Coins Zako',
      'watch_ad': 'Tazama Tangazo',
      'loading_ad': 'Inapakia tangazo...',
      'crediting': 'Inakupa coins...',
      'earned_coin': 'Umepata coin 1! Endelea kutazama.',
      'ad_not_ready': 'Tangazo halijatayarishwa. Jaribu tena.',
      'ad_failed': 'Imeshindwa kuonyesha tangazo.',
      'earn_failed': 'Imeshindwa kukupa coins',
      'no_payouts_yet': 'Hujawahi kulipwa bado',
      'total_earned': 'Jumla uliyopata',
      'paid': 'Imelipwa',
      'daily_limit_reached': 'Umefika kikomo cha leo! Njoo kesho.',
      'earned_coins': 'Umepata',
      'soft_coins': 'Coins Wastani',
      'premium_coins': 'Coins Premium',
      'earn_per_ad': 'Pata kwa kila tangazo',
      'cooldown': 'Subiri',
      'regular_gifts': 'Zawadi za Kawaida',
      'premium_gifts': 'Zawadi za Premium',
      'otp_sent': 'OTP imetumwa kwenye barua pepe yako',
      'otp_expired': 'OTP imeisha muda. Tuma nyingine.',
      'otp_invalid': 'OTP si sahihi',
      'password_mismatch': 'Nywila hazilingani',
      'password_short': 'Nywila lazima iwe angalau herufi 6',
      'password_reset_success':
          'Nywila imebadilishwa! Umeingia kwenye akaunti yako.',
    },
    'en': {
      'app_name': 'Soko Langu',
      'login': 'Login',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'categories': 'Categories',
      'latest_products': 'Latest Products',
      'search': 'Search',
      'sell_product': 'Sell Product',
      'profile': 'Profile',
      'settings': 'Settings',
      'chats': 'Chats',
      'logout': 'Logout',
      'add_to_cart': 'Add to Cart',
      'buy_now': 'Buy Now',
      'quantity': 'Quantity',
      'total': 'Total',
      'no_products': 'No products yet',
      'no_categories': 'No categories yet',
      'product_detail': 'Product Detail',
      'description': 'Description',
      'details': 'Details',
      'category': 'Category',
      'brand': 'Brand',
      'condition': 'Condition',
      'location': 'Location',
      'stock': 'Stock',
      'wholesale': 'Wholesale',
      'seller': 'Seller',
      'view_store': 'View Store',
      'chat': 'Chat',
      'reviews': 'Reviews',
      'write_review': 'Write a Review',
      'rating': 'Rating',
      'comment': 'Comment',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'my_ads': 'My Ads',
      'my_orders': 'My Orders',
      'wishlist': 'Wishlist',
      'music_player': 'Music Player',
      'shopping_cart': 'Shopping Cart',
      'cart_empty': 'Your cart is empty',
      'checkout': 'Proceed to Checkout',
      'place_order': 'Place Order',
      'order_placed': 'Order placed! Send payment to the seller.',
      'order_failed': 'Order failed',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'processing': 'Processing',
      'shipped': 'Shipped',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'edit_profile': 'Edit Profile',
      'display_name': 'Display Name',
      'bio': 'Bio',
      'phone': 'Phone Number',
      'payment_methods': 'Payment Methods',
      'add_payment': 'Add',
      'select_payment': 'Select Payment Method',
      'total_amount': 'Total',
      'chat_with_seller': 'Chat with Seller',
      'chat_first':
          'You need to chat with the seller before buying. Start a conversation?',
      'chat_now': 'Chat Now',
      'send': 'Send',
      'type_message': 'Type a message...',
      'no_conversations': 'No conversations yet',
      'waiting_for_user': 'Waiting for other user...',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'switch_camera': 'Switch',
      'speaker': 'Speaker',
      'earpiece': 'Earpiece',
      'end_call': 'End',
      'search_products': 'Search products...',
      'filter': 'Filter',
      'price_range': 'Price Range',
      'apply': 'Apply',
      'clear': 'Clear',
      'about': 'About Soko Langu',
      'version': 'Version 1.0.0',
      'help': 'Help Center',
      'privacy': 'Privacy & Security',
      'appearance': 'Appearance',
      'notifications': 'Notifications',
      'push_notifications': 'Push Notifications',
      'language': 'Language',
      'currency': 'Currency',
      'account': 'Account',
      'support': 'Support',
      'contact': 'Contact: langusoko@gmail.com',
      'coming_soon': 'Coming soon',
      'error': 'Error',
      'success': 'Success',
      'required': 'Required',
      'online': 'Online',
      'offline': 'Offline',
      'last_seen': 'Last seen',
      'just_now': 'just now',
      'minutes_ago': 'minutes ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'allow': 'Allow',
      'deny': 'Deny',
      'permission_required': 'Permission Required',
      'permission_camera': 'Camera access is needed for video calls',
      'permission_microphone':
          'Microphone access is needed for voice calls and voice messages',
      'permission_storage': 'Storage access is needed to read music files',
      'permission_photos': 'Photo access is needed to share images',
      'auto_lock': 'Auto-Lock',
      'auto_lock_desc': 'Lock app after inactivity',
      'auto_lock_time': 'Lock after',
      'minutes': 'minutes',
      'never': 'Never',
      'enter_pin': 'Enter PIN',
      'wrong_pin': 'Wrong PIN',
      'set_pin': 'Set PIN',
      'confirm_pin': 'Confirm PIN',
      'pin_mismatch': 'PINs do not match',
      'pin_updated': 'PIN updated successfully',
      'payment_gateway': 'Payment Gateway',
      'google_pay': 'Google Pay',
      'api_key': 'API Key',
      'api_secret': 'API Secret',
      'test_mode': 'Test Mode',
      'live_mode': 'Live Mode',
      'save_settings': 'Save Settings',
      'settings_saved': 'Settings saved',
      'select_language': 'Select Language',
      'select_currency': 'Select Currency',
      'no_songs': 'No songs found',
      'permission_storage_desc': 'Permission to read storage is required',
      'grant_permission': 'Grant Permission',
      'product_images': 'Product Images',
      'product_name': 'Product Name',
      'price': 'Price',
      'subcategory': 'Subcategory',
      'new': 'New',
      'used': 'Used',
      'refurbished': 'Refurbished',
      'add_product': 'Uza Bidhaa',
      'update_product': 'Edit Product',
      'product_added': 'Product added!',
      'product_updated': 'Product updated!',
      'delete_product': 'Delete Product',
      'delete_confirm': 'Delete this product permanently?',
      'product_deleted': 'Product deleted',
      'no_ads': "You haven't listed any products yet",
      'upload_image': 'Please add at least one image',
      'copied': 'Copied to clipboard',
      'share': 'Share',
      'sold': 'sold',
      'reviews_count': 'reviews',
      'no_reviews': 'No reviews yet',
      'comments': 'Comments',
      'write_comment': 'Write a Comment',
      'no_comments_yet': 'No comments yet. Be the first!',
      'comment_hint': 'Write a comment...',
      'replies': 'replies',
      'reply': 'Reply',
      'view_replies': 'View replies',
      'delete_conversation': 'Delete Conversation',
      'delete_conversation_confirm':
          'Are you sure you want to delete this conversation? This cannot be undone.',
      'login_required': 'Login required',
      'email_verification_sent': 'Verification email sent! Check your inbox.',
      'check_email': 'Check your email for verification link',
      'use_different_account': 'Use a different account',
      'forgot_password': 'Forgot password?',
      'reset_password': 'Reset Password',
      'reset_sent': 'Password reset email sent',
      'no_name': 'No Name',
      'no_email': 'No Email',
      'unlock': 'Unlock',
      'no_payment_methods': 'Seller has not set payment methods yet.',
      'dashboard': 'Dashboard',
      'revenue': 'Revenue',
      'total_orders': 'Total Orders',
      'total_products': 'Total Products',
      'recent_orders': 'Recent Orders',
      'mark_as': 'Mark as',
      'no_received_orders': 'No orders received yet',
      'no_notifications': 'No notifications yet',
      'app_locked': 'App Locked',
      'enter_pin_unlock': 'Enter your PIN to unlock',
      'or_use': 'or use',
      'welcome_back': 'Welcome back!',
      'fill_fields': 'Fill all fields',
      'enter_email': 'Enter your email first',
      'continue_google': 'Continue with Google',
      'no_account': "Don't have an account? ",
      'join_soko': 'Join Soko Langu',
      'create_account': 'Create your account',
      'full_name': 'Full Name',
      'account_created': 'Account created!',
      'login_prompt': 'Already have account? Login',
      'no_orders': 'No orders yet',
      'order': 'Order',
      'ordered': 'Ordered',
      'tagline': 'Your Marketplace, Your Language',
      'version_label': 'Version',
      'developer': 'Developer',
      'team_name': 'Soko Langu Team',
      'contact_label': 'Contact',
      'features': 'Features',
      'features_text':
          'Online Marketplace\nChat & Video Calls\nMulti-language & Currency Support',
      'copyright': '© 2026 Soko Langu. All rights reserved.',
      'photo_updated': 'Profile photo updated!',
      'products': 'Products',
      'followers': 'Followers',
      'following': 'Following',
      'follow': 'Follow',
      'home': 'Home',
      'send_photo': 'Send Photo',
      'voice': 'Voice',
      'checkout_failed': 'Checkout failed',
      'replied_to': 'Re: ',
      'unlock_app': 'Unlock Soko Langu',
      'added_to_cart': 'Added to cart!',
      'delete_failed': 'Failed to delete',
      'earn_coins': 'Earn Coins',
      'your_coins': 'Your Coins',
      'watch_ad': 'Watch Ad',
      'loading_ad': 'Loading ad...',
      'crediting': 'Crediting...',
      'earned_coin': 'You earned 1 coin! Keep watching.',
      'ad_not_ready': 'Ad not ready yet. Try again.',
      'ad_failed': 'Failed to show ad.',
      'earn_failed': 'Failed to credit coins',
      'no_payouts_yet': 'No payouts yet',
      'total_earned': 'Total Earned',
      'platform_fee': 'Platform Fee',
      'paid': 'Paid',
      'daily_limit_reached': 'Daily limit reached! Come back tomorrow.',
      'earned_coins': 'You earned',
      'soft_coins': 'Soft Coins',
      'premium_coins': 'Premium Coins',
      'today': 'Today',
      'earn_per_ad': 'Earn per ad',
      'cooldown': 'Wait',
      'regular_gifts': 'Regular Gifts',
      'premium_gifts': 'Premium Gifts',
      'otp_sent': 'OTP sent to your email',
      'otp_expired': 'OTP expired. Request a new one.',
      'otp_invalid': 'Invalid OTP',
      'password_mismatch': 'Passwords do not match',
      'password_short': 'Password must be at least 6 characters',
      'password_reset_success': 'Password reset! You are now logged in.',
    },
  };

  Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'sw';
  }

  Future<void> setLanguage(String code) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, code);
  }

  Future<String> getCurrency() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_currencyKey) ?? 'TZS';
  }

  Future<void> setCurrency(String code) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_currencyKey, code);
  }

  String getCurrencySymbol(String code) {
    return supportedCurrencies[code]?['symbol'] ?? 'TSh';
  }

  static String translate(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']![key] ?? key;
  }
}
