// Soko Vibe Dukani — static data: categories, regions/districts, labels.
// Regions + districts generated from lib/constants/tanzania_districts.dart
// (CC-BY-4.0 open-admin-data, 31 regions). Labels are sw default + en.

const SV_CATEGORIES = [
  'Phones & Tablets', 'Electronics', 'Fashion & Clothing', 'Home & Garden',
  'Vehicles & Spare Parts', 'Health & Beauty', 'Sports & Outdoors',
  'Toys & Games', 'Books & Stationery', 'Supermarket', 'Agriculture', 'Services',
];

// Sub-category menus for the left mega nav, mirroring how the app groups
// products by category + subcategory fields.
const SV_SUBCATS = {
  'Phones & Tablets': ['Smartphones', 'Feature Phones', 'Tablets', 'Phone Accessories', 'Phone Cases'],
  'Electronics': ['TVs & Audio', 'Computers & Laptops', 'Cameras', 'Gaming', 'Home Appliances'],
  'Fashion & Clothing': ["Men's Fashion", "Women's Fashion", "Kids Fashion", 'Shoes', 'Bags & Accessories'],
  'Home & Garden': ['Furniture', 'Kitchen', 'Decor', 'Garden & Outdoor'],
  'Vehicles & Spare Parts': ['Cars', 'Motorbikes', 'Bicycles', 'Spare Parts'],
  'Health & Beauty': ['Cosmetics', 'Personal Care', 'Fragrances', 'Supplements'],
  'Sports & Outdoors': ['Fitness', 'Sportswear', 'Camping', 'Fishing'],
  'Toys & Games': ['Kids Toys', 'Remote Control', 'Board Games'],
  'Books & Stationery': ['Books', 'Stationery', 'Office Supplies'],
  'Supermarket': ['Food & Beverages', 'Household', 'Personal Care', 'Fresh'],
  'Agriculture': ['Farm Produce', 'Livestock', 'Machinery', 'Seeds & Fertilizer'],
  'Services': ['Delivery & Transport', 'Repairs', 'Rental', 'Professional'],
};

const SV_REGIONS = ["Arusha","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi","Manyara","Mara","Mbeya","Mjini Magharibi","Morogoro","Mtwara","Mwanza","Njombe","Pwani","Rukwa","Ruvuma","Shinyanga","Simiyu","Singida","Songwe","Tabora","Tanga","Kaskazini Pemba","Kusini Pemba","Kaskazini Unguja","Kusini Unguja"];

const SV_DISTRICTS = {"Rukwa":["Kalambo","Nkasi","Sumbawanga City","Sumbawanga"],"Songwe":["Ileje","Mbozi","Momba","Songwe","Tunduma"],"Kilimanjaro":["Hai","Moshi City","Moshi","Mwanga","Rombo","Same","Siha"],"Mtwara":["Masasi City","Masasi","Mtwara City","Mtwara","Nanyumbu","Newala City","Newala","Tandahimba"],"Kaskazini Unguja":["Kaskazini A","Kaskazini B"],"Kagera":["Biharamulo","Bukoba City","Bukoba","Karagwe","Kyerwa","Missenyi","Muleba","Ngara"],"Mjini Magharibi":["Magharibi","Mjini"],"Kaskazini Pemba":["Wete","Micheweni"],"Pwani":["Bagamoyo","Chalinze","Kibaha City","Kibaha","Kisarawe","Mafia","Mkuranga","Rufiji"],"Simiyu":["Bariadi","Busega","Itilima","Maswa","Meatu"],"Dar es Salaam":["Ilala","Kigamboni","Kinondoni","Temeke","Ubungo"],"Shinyanga":["Kahama City","Kahama","Kishapu","Msalala","Shinyanga City","Shinyanga","Ushetu"],"Manyara":["Babati City","Babati","Hanang","Kiteto","Mbulu","Simanjiro"],"Mara":["Bunda","Butiama","Musoma City","Musoma","Rorya","Serengeti","Tarime"],"Tanga":["Bumbuli","Handeni City","Handeni","Kilindi","Korogwe City","Korogwe","Lushoto","Mkinga","Muheza","Pangani","Tanga City"],"Morogoro":["Gairo","Ifakara","Kilombero","Kilosa","Malinyi","Morogoro City","Morogoro","Mvomero","Ulanga"],"Kusini Pemba":["Chake Chake","Mkoani"],"Dodoma":["Bahi","Chamwino","Chemba","Dodoma City","Kongwa","Kondoa","Mpwapwa"],"Singida":["Ikungi","Iramba","Itigi","Manyoni","Mkalama","Singida City","Singida"],"Ruvuma":["Mbinga","Namtumbo","Nyasa","Songea City","Songea","Tunduru"],"Kusini Unguja":["Kati","Kusini"],"Katavi":["Mlele","Mpanda","Mpimbwe","Tanganyika"],"Lindi":["Kilwa","Lindi City","Lindi","Liwale","Nachingwea","Ruangwa"],"Geita":["Bukombe","Chato","Geita","Mbogwe","Nyang'hwale"],"Tabora":["Igunga","Kaliua","Nzega","Sikonge","Tabora City","Urambo","Uyui"],"Arusha":["Arusha City","Arusha","Karatu","Longido","Meru","Monduli","Ngorongoro"],"Iringa":["Iringa City","Iringa","Kilolo","Mufindi"],"Kigoma":["Buhigwe","Kakonko","Kasulu City","Kasulu","Kibondo","Kigoma City","Kigoma","Uvinza"],"Mbeya":["Busokelo","Chunya","Kyela","Mbarali","Mbeya City","Mbeya","Rungwe"],"Mwanza":["Bukoba City","Buchosa","Kwimba","Magu","Misungwi","Nyamagana","Sengerema","Ukerewe"]};

const SV_T = {
  sw: {
    nav_home: 'Nyumbani', nav_categories: 'Kategoria', nav_orders: 'Agizo Zangu',
    nav_account: 'Akaunti', nav_signin: 'Ingia', search_ph: 'Tafuta bidhaa...',
    splash_p: 'Hujambo! Soko Vibe Dukani linapakia bidhaa zako.',
    home_hero_kicker: 'Soko la Tanzania', home_hero_title: 'Nunua na kuuza popote Tanzania.',
    home_hero_sub: 'Malipo salama kupitia ClickPesa na escrow — bidhaa unayoipata ndiyo unayolipia.',
    home_new: 'Bidhaa mpya', home_browse: 'Vinjari', featured: 'Zinazoangaziwa',
    feed_all: 'Bidhaa Zote', feed_new: 'Bidhaa Mpya', trust_escrow: 'Escrow Protected',
    trust_verified: 'Verified Sellers', trust_clickpesa: 'ClickPesa Secured', trust_delivery: 'Nationwide Delivery',
    checkout_step_addr: 'Anwani', checkout_step_pay: 'Malipo', checkout_step_done: 'Uthibitisho',
    addr_heading: 'Anwani ya Ununuzi', summary_heading: 'Muhtasari wa Agizo',
    escrow_note: 'Malipo yanashikiliwa kwa escrow kupitia ClickPesa hadi uthibitishe kupokea.',
    step_back: 'Rudi nyuma', step_next: 'Endelea', confirm_title: 'Agizo Limepokelewa',
    confirm_sub: 'Malipo yameingia escrow. Muuzaji ataanza kukusanyia bidhaa yako.',
    view_orders: 'Angalia Agizo Zangu', back_home: 'Endelea Kununua',
    categories: 'Kategoria', all: 'Zote', load_more: 'Pakia zaidi',
    empty: 'Hakuna bidhaa', empty_filter: 'Hakuna bidhaa zinazolingana',
    view_detail: 'Angalia', add_cart: 'Ongeza kwenye kikapu', buy_now: 'Nunua Sasa',
    in_stock: 'Zipo', out_stock: 'Zimeisha', qty: 'Idadi', add_to_cart_ok: 'Imeongezwa kwenye kikapu',
    cart_title: 'Kikapu', cart_empty: 'Kikapu chako kipo tupu.', cart_browse: 'Vinjari bidhaa',
    cart_seller: 'Muuzaji', remove: 'Ondoa', cart_total: 'Jumla', cart_checkout: 'Tengeneza oda',
    back: 'Rudi', seller: 'Muuzaji', condition: 'Hali', location: 'Mahali',
    description: 'Maelezo', attributes: 'Sifa nyingine', variants: 'Vitokezi',
    checkout_title: 'Malipo', checkout_addr: 'Anwani ya ununuzi',
    region: 'Mkoa', district: 'Wilaya', ward: 'Kata', street: 'Mtaa / barabara',
    landmarks: 'Alama za kipekee (si lazima)', phone: 'Namba ya simu (kwa USSD)',
    delivery: 'Namna ya kupokea', deliver_local: 'Ndani ya jiji / senioribu',
    fee_note: 'Ukomo wa mfumo (3.5%) + shipping unahesabiwa upande wa muuzaji',
    place_order: 'Tengeneza Oda na Ulipa', processing: 'Inachakata...',
    pay_wait: 'Tumekutumia USSD prompt kwenye simu yako. Lipa uone "Lipa" na weka PIN.',
    pay_status_pending: 'Inasubiri malipo...', pay_status_paid: 'Malipo yametambuliwa!',
    pay_done: 'Agizo limekamilishwa — escrow imeanzishwa.', pay_failed: 'Malipo hayajafika.',
    pay_new: 'Tuma USSD tena', order_created: 'Agizo limeanzishwa.',
    need_auth: 'Ingia kwanza ili kuendelea.', signin_title: 'Ingia',
    signup_title: 'Sajili akaunti', name: 'Jina kamili', email: 'Barua pepe',
    password: 'Nenosiri', have_account: 'Una akaunti?', no_account: 'Huna akaunti?',
    submit_signin: 'Ingia', submit_signup: 'Sajili', signout: 'Ondoka',
    profile: 'Akaunti yako', orders_my: 'Agizo Zangu', my_orders_empty: 'Huna agizo bado.',
    order_statuses: { pending: 'Inafanyiwa kazi', quoted: 'Imehifadhiwa kimasaa', paid: 'Imelipwa', escrow_hold: 'Escrow imeanzishwa', escrow_held: 'Escrow imeanzishwa', dispatched: 'Imesafirishwa', confirmed: 'Imetolewa', completed: 'Imekamilika', cancelled: 'Imeghairiwa', disputed: 'Kuna mzozo', refunded: 'Imerudishiwa', failed: 'Imeshindikana', expired: 'Muda umeisha' },
    status_label: 'Hali', order_total: 'Jumla', order_date: 'Tarehe', order_id: 'Oda #', wa_cta: 'Wasiliana kwa WhatsApp', call_seller: 'Piga Simu',
    price: 'Bei', wait_fetch: 'Inapakia...', err_generic: 'Kuna tatizo. Jaribu tena.',
    theme_light: 'Mchana', theme_dark: 'Usiku', lang_label: 'Lugha', to_top: 'Juu',
    nav_wish: 'Unavyovipenda', nav_seller: 'Muuzaji', nav_seller_page: 'Kibanda changu',
    seller_become: 'Kuwa muuzaji', seller_you: 'Wewe ni muuzaji', sell_signup: 'Nina bidhaa za kuuza — kuwa muuzaji',
    seller_overview: 'Muhtasari', seller_products: 'Bidhaa zangu', seller_orders: 'Oda za kibanda', seller_wallet: 'Mlipo',
    stats_products: 'Bidhaa', stats_active: 'Zimechapishwa', stats_sold: 'Zimeuzwa', stats_orders: 'Oda', stats_pending_orders: 'Oda zinazosubiri',
    not_seller: 'Bado huuzi hapa. Fungua kibanda chako kisha uweke bidhaa zako.', seller_balance_lbl: 'Salio lako',
    new_product: 'Ongeza bidhaa', edit_product: 'Hariri', save_product: 'Hifadhi bidhaa',
    publish: 'Chapisha', unpublish: 'Ficha', delete_product: 'Futa', del_confirm: 'Una uhakika kufuta bidhaa hii?',
    product_name: 'Jina la bidhaa', product_price: 'Bei (TZS)', product_stock: 'Idadi (stock)', product_cond: 'Hali',
    product_cat: 'Kategoria', product_subcat: 'Subcategory (si lazima)', product_brand: 'Chapa (si lazima)', product_desc: 'Maelezo',
    product_imgs: 'Picha (URL, tenga kwa koma)', product_loc: 'Mahali (Mkoa, Wilaya)',
    ws_toggle: 'Uza jumla (wholesale)', ws_min: 'Idadi (min)', ws_price: 'Bei kwa kipande', jumla_tbl: 'Jumla (wholesale)',
    cond_new: 'Mpya', cond_used: 'Imetumika', cond_refurbished: 'Refurbished',
    sold: 'imeuzwa', wish_title: 'Unavyovipenda', wish_hint: 'Bidhaa ulizoziweka', wish_empty: 'Huna bidhaa zozote hapa bado. Tumia kipini cha moyo kwenye bidhaa.',
    wish_saved: 'Imehifadhiwa kwenye wishlist', wish_removed: 'Imetolewa kwenye wishlist',
    reviews: 'Tathmini', no_reviews: 'Hakuna tathmini bado.', write_review: 'Andika tathmini',
    your_rating: 'Alama zako', your_comment: 'Maoni', submit_review: 'Tuma tathmini', review_ok: 'Tathmini imetumwa — asante!',
    share: 'Shiriki', copy_link: 'Nakili kiungo', copied: 'Imenakiliwa', soldout_ov: 'ZIMEISHA',
    guest_note: 'Unununua bila akaunti: oda yako inafungwa kwenye namba ya simu uliyoiweka. USSD utatumwa kwenye namba hiyo.',
    guest_name: 'Jina lako', need_name_phone: 'Andika jina na namba ya simu kikamilifu.',
    withdraw: 'Toa fedha', withdraw_amt: 'Kiasi (TZS)', withdraw_phone: 'Namba ya simu ya ClickPesa',
    withdraw_ok: 'Ulipokelewa! Fedha zinachakatwa.', min_withdraw: 'Hakuna kiwango cha chini cha uondoaji - ClickPesa pekee hukata ada yake.',
    feat_until: 'Inaangaziwa', notchr: 'Tanzania', sold_by: 'Kiuza',
  },
  en: {
    nav_home: 'Home', nav_categories: 'Categories', nav_orders: 'My Orders',
    nav_account: 'Account', nav_signin: 'Sign in', search_ph: 'Search products...',
    splash_p: 'Hi! The Soko Vibe shop is loading your products.',
    home_hero_kicker: 'Tanzania\'s marketplace', home_hero_title: 'Buy and sell anywhere in Tanzania.',
    home_hero_sub: 'Secure ClickPesa payments and escrow — pay only for what you receive.',
    home_new: 'New arrivals', home_browse: 'Browse', featured: 'Featured',
    feed_all: 'All Products', feed_new: 'New Arrivals', trust_escrow: 'Escrow Protected',
    trust_verified: 'Verified Sellers', trust_clickpesa: 'ClickPesa Secured', trust_delivery: 'Nationwide Delivery',
    checkout_step_addr: 'Address', checkout_step_pay: 'Payment', checkout_step_done: 'Confirmation',
    addr_heading: 'Delivery address', summary_heading: 'Order summary',
    escrow_note: 'Payment is held in escrow by ClickPesa until you confirm receipt.',
    step_back: 'Go back', step_next: 'Continue', confirm_title: 'Order Received',
    confirm_sub: 'Payment reached escrow. The seller will start preparing your order.',
    view_orders: 'View my orders', back_home: 'Keep shopping',
    categories: 'Categories', all: 'All', load_more: 'Load more',
    empty: 'No products', empty_filter: 'No matching products',
    view_detail: 'View', add_cart: 'Add to cart', buy_now: 'Buy now',
    in_stock: 'In stock', out_stock: 'Out of stock', qty: 'Qty',
    add_to_cart_ok: 'Added to cart', cart_title: 'Cart', cart_empty: 'Your cart is empty.',
    cart_browse: 'Browse products', cart_seller: 'Seller', remove: 'Remove',
    cart_total: 'Total', cart_checkout: 'Place order', back: 'Back',
    seller: 'Seller', condition: 'Condition', location: 'Location',
    description: 'Description', attributes: 'More info', variants: 'Variants',
    checkout_title: 'Checkout', checkout_addr: 'Delivery address',
    region: 'Region', district: 'District', ward: 'Ward', street: 'Street / road',
    landmarks: 'Landmarks (optional)', phone: 'Phone number (for USSD)',
    delivery: 'Delivery', deliver_local: 'Local delivery',
    fee_note: 'Platform fee (3.5%) + shipping are computed by the seller end',
    place_order: 'Place order & Pay', processing: 'Processing...',
    pay_wait: 'We sent a USSD prompt to your phone. Confirm, enter your PIN, pay.',
    pay_status_pending: 'Waiting for payment...', pay_status_paid: 'Payment received!',
    pay_done: 'Order complete — escrow activated.', pay_failed: 'Payment not received.',
    pay_new: 'Send USSD again', order_created: 'Order created.',
    need_auth: 'Sign in to continue.', signin_title: 'Sign in',
    signup_title: 'Create account', name: 'Full name', email: 'Email',
    password: 'Password', have_account: 'Have an account?', no_account: 'No account yet?',
    submit_signin: 'Sign in', submit_signup: 'Sign up', signout: 'Sign out',
    profile: 'Your account', orders_my: 'My Orders', my_orders_empty: 'No orders yet.',
    order_statuses: { pending: 'Pending', quoted: 'Price quoted', paid: 'Paid', escrow_hold: 'Escrow active', escrow_held: 'Escrow active', dispatched: 'Dispatched', confirmed: 'Released', completed: 'Completed', cancelled: 'Cancelled', disputed: 'Disputed', refunded: 'Refunded', failed: 'Failed', expired: 'Expired' },
    status_label: 'Status', order_total: 'Total', order_date: 'Date', order_id: 'Order #',
    wa_cta: 'Chat on WhatsApp', call_seller: 'Call Seller', price: 'Price', wait_fetch: 'Loading...',
    err_generic: 'Something went wrong. Try again.',
    theme_light: 'Light', theme_dark: 'Dark', lang_label: 'Language', to_top: 'Top',
    nav_wish: 'Wishlist', nav_seller: 'Seller', nav_seller_page: 'My store',
    seller_become: 'Become a seller', seller_you: 'You are a seller', sell_signup: 'I have products to sell — become a seller',
    seller_overview: 'Overview', seller_products: 'My products', seller_orders: 'Store orders', seller_wallet: 'Wallet',
    stats_products: 'Products', stats_active: 'Published', stats_sold: 'Sold', stats_orders: 'Orders', stats_pending_orders: 'Pending orders',
    not_seller: 'You are not selling here yet. Open your store, then list your products.', seller_balance_lbl: 'Your balance',
    new_product: 'Add product', edit_product: 'Edit', save_product: 'Save product',
    publish: 'Publish', unpublish: 'Unpublish', delete_product: 'Delete', del_confirm: 'Delete this product? Are you sure?',
    product_name: 'Product name', product_price: 'Price (TZS)', product_stock: 'Stock', product_cond: 'Condition',
    product_cat: 'Category', product_subcat: 'Subcategory (optional)', product_brand: 'Brand (optional)', product_desc: 'Description',
    product_imgs: 'Images (URLs, comma-separated)', product_loc: 'Location (Region, District)',
    ws_toggle: 'Wholesale', ws_min: 'Min qty', ws_price: 'Unit price', jumla_tbl: 'Wholesale',
    cond_new: 'New', cond_used: 'Used', cond_refurbished: 'Refurbished',
    sold: 'sold', wish_title: 'Wishlist', wish_hint: 'Products you saved', wish_empty: 'No saved products yet. Tap the heart on any product.',
    wish_saved: 'Saved to wishlist', wish_removed: 'Removed from wishlist',
    reviews: 'Reviews', no_reviews: 'No reviews yet.', write_review: 'Write a review',
    your_rating: 'Your rating', your_comment: 'Comment', submit_review: 'Submit review', review_ok: 'Review submitted — thanks!',
    share: 'Share', copy_link: 'Copy link', copied: 'Copied', soldout_ov: 'OUT OF STOCK',
    guest_note: 'Checking out without an account: your order is tied to the phone number you enter. The USSD prompt goes to that number.',
    guest_name: 'Your name', need_name_phone: 'Enter your name and a valid phone number.',
    withdraw: 'Withdraw', withdraw_amt: 'Amount (TZS)', withdraw_phone: 'ClickPesa phone number',
    withdraw_ok: 'Request received! Funds are processing.', min_withdraw: 'No minimum withdrawal - only ClickPesa deducts its own fee.',
    feat_until: 'Featured', notchr: 'Tanzania', sold_by: 'Seller',
  },
};

  const SV_STATUS_ORDER = [
  'pending', 'quoted', 'paid', 'escrow_hold', 'escrow_held', 'dispatched',
  'confirmed', 'completed', 'disputed', 'refunded', 'cancelled', 'failed', 'expired',
];

Object.assign(SV_T.sw, {
  signin_phone: 'Ingia kwa namba ya simu', signin_google: 'Endelea kwa Google',
  notifications: 'Taarifa', chats: 'Mazungumzo', flash_sale: 'Mauzo ya Flash',
  seller_analytics: 'Takwimu', seller_kyc: 'Uthibitisho (KYC)', seller_boost: 'Angazia',
  seller_flash: 'Flash zangu', mark_all_read: 'Soma zote', notif_settings: 'Mipangilio ya taarifa',
  no_notifications: 'Hakuna taarifa bado.', say_hi: 'Andika salamu ya kwanza.', write_msg: 'Andika ujumbe...',
  send: 'Tuma', comments: 'Maoni', write_comment: 'Andika maoni...', write_reply: 'Jibu...',
  replies: 'majibu', login_to_comment: 'Ingia ili uweze kutoa maoni.', no_comments: 'Hakuna maoni bado.',
  follow: 'Fuata', following: 'Unamfuata', chat_seller: 'Wasiliana na muuzaji',
  fs_new: 'Anzisha flash', fs_empty: 'Hakuna flash inayoendelea sasa.', fs_active: 'Inayoendelea',
  fs_ended: 'Imeisha', fs_none: 'Hujaanzisha flash bado.', fs_need_product: 'Anzisha bidhaa kwanza.',
  fs_created: 'Flash imeanzishwa!', delete: 'Futa', confirm: 'Thibitisha', dispute: 'Fungua mgogoro',
  approve: 'Kubali', reject: 'Kataa', pay_now: 'Lipa sasa',
  otp_confirm: 'Thibitisha OTP', otp_enter_note: 'Weka OTP uliyopokea ili escrow itolewe kwa muuzaji.',
  open_dispute: 'Fungua mgogoro', cancel_reason: 'Sababu ya kufuta', rejected: 'Umekataa',
  cancelled: 'Imeghairiwa', continue: 'Endelea', save: 'Hifadhi', submit: 'Wasilisha',
  loading: 'Inapakia...', ship_quote: 'Bei ya usafirishaji', ship_cost: 'Gharama ya usafirishaji',
  ship_days: 'Siku za kufikisha', otp_invalid: 'OTP si sahihi.',
  analytics: 'Takwimu', avg_order: 'Wastani wa oda', boost: 'Angazia bidhaa',
  boost_bronze: 'Bronze', boost_bronze_tag: 'Shaba · TZS 15,000/siku', boost_silver: 'Silver',
  boost_silver_tag: 'Fedha · TZS 25,000/siku', boost_gold: 'Gold', boost_gold_tag: 'Dhahabu · TZS 45,000/siku',
  boost_done: 'Bidhaa inaangaziwa sasa', boost_failed: 'Boosti halikwimu', boost_need_product: 'Anzisha bidhaa kwanza.',
  boost_pay: 'Lipa angazia', cancel: 'Ghairi', cancel_order: 'Ghairi oda',
  cannot_follow_self: 'Huwezi kujifuata mwenyewe.', chats_empty: 'Hakuna mazungumzo bado.',
  clear_all: 'Futa zote', close: 'Funga', courier: 'Kampuni ya usafirishaji', days: 'siku',
  delivery_confirmed: 'Umethibitisha kupokea — escrow itatolewa.', did_you_mean: 'Unamaanisha:',
  disp_damaged: 'Bidhaa imeharibika', disp_not_received: 'Sikupokea bidhaa', disp_different: 'Tofauti na ilivyoorodheshwa',
  disp_other: 'Sababu nyingine', disp_wrong_item: 'Bidhaa si sahihi',
  dispatch: 'Tuma', dispute_desc: 'Maelezo ya mgogoro', dispute_filed: 'Mgogoro umefunguliwa.',
  dispute_reason: 'Sababu ya mgogoro', div: 'div', input: 'input',
  issue_otp: 'Toa OTP', issue_otp_after: 'Mpe bidhaa mteja kisha toa OTP.',
  kyc: 'Uthibitisho', kyc_approved: 'Uthibitisho umekubaliwa', kyc_done: 'Umekamilisha KYC.',
  kyc_full_name: 'Jina kamili (kama kwenye kitambulisho)', kyc_id_number: 'Namba ya kitambulisho',
  kyc_id_type: 'Aina ya kitambulisho', kyc_submitted: 'Uthibitisho umetumwa kwa ukaguzi.',
  kyc_upload_id: 'Pakia kitambulisho', kyc_upload_selfie: 'Pakia picha ya uso',
  most_rated: 'Zinazopendwa zaidi', no_replies: 'Hakuna majibu bado.', notification_deleted: 'Taarifa imefutwa.',
  otp_expires_note: 'OTP itaisha baada ya dakika 15.', otp_hand_to_buyer: 'Mpe mteja bidhaa kisha mwombe OTP.',
  own_only: 'Unaweza kuondoa yako tu.', pay_ok: 'Malipo yamekamilika!', pay_push_note: 'Tumetuma USSD kwa simu yako — lipa uweke PIN.',
  pay_total: 'Jumla ya kulipa', product: 'Bidhaa', sales_30d: 'Mauzo siku 30 zilizopita',
  seller_set_ship: 'Weka bei ya usafirishaji', ship_notes: 'Maelezo ya usafirishaji (hiari)',
  ship_notes_ph: 'Mf.: Kesho asubuhi Dar', stats_completed: 'Zilizokamilika', stats_gmv: 'Mauzo yote (GMV)',
  tracking: 'Namba ya kufuatilia', trending: 'Zinazoendeshwa', upload_ok: 'Imepakiwa!',
  wallet_earned: 'Ulipata', wallet_empty: 'Hakuna miamala bado.', wallet_frozen: 'Kiasi kinachofungwa',
  wallet_history: 'Historia ya salio', wallet_note: 'Fedha huelea kwa escrow hadi uhakiki malipo.',
  wallet_pending: 'Inasubiri', withdrawn: 'Umetoa',
});

Object.assign(SV_T.en, {
  signin_phone: 'Sign in with phone number', signin_google: 'Continue with Google',
  notifications: 'Notifications', chats: 'Messages', flash_sale: 'Flash Sale',
  seller_analytics: 'Analytics', seller_kyc: 'Verification (KYC)', seller_boost: 'Boost',
  seller_flash: 'My flash sales', mark_all_read: 'Mark all read', notif_settings: 'Notification settings',
  no_notifications: 'No notifications yet.', say_hi: 'Say hi to start.', write_msg: 'Type a message...',
  send: 'Send', comments: 'Comments', write_comment: 'Write a comment...', write_reply: 'Reply...',
  replies: 'replies', login_to_comment: 'Sign in to comment.', no_comments: 'No comments yet.',
  follow: 'Follow', following: 'Following', chat_seller: 'Message seller',
  fs_new: 'Start a flash sale', fs_empty: 'No active flash sales right now.', fs_active: 'Live',
  fs_ended: 'Ended', fs_none: 'You have not started any flash sales.', fs_need_product: 'List a product first.',
  fs_created: 'Flash sale created!', delete: 'Delete', confirm: 'Confirm', dispute: 'Open dispute',
  approve: 'Approve', reject: 'Reject', pay_now: 'Pay now',
  otp_confirm: 'Verify OTP', otp_enter_note: 'Enter the OTP you received to release the escrow to the seller.',
  open_dispute: 'Open dispute', cancel_reason: 'Cancellation reason', rejected: 'Rejected',
  cancelled: 'Cancelled', continue: 'Continue', save: 'Save', submit: 'Submit',
  loading: 'Loading...', ship_quote: 'Shipping quote', ship_cost: 'Shipping cost',
  ship_days: 'Delivery days', otp_invalid: 'Invalid OTP.',
  analytics: 'Analytics', avg_order: 'Avg order value', boost: 'Boost product',
  boost_bronze: 'Bronze', boost_bronze_tag: 'Bronze · TZS 15,000/day', boost_silver: 'Silver',
  boost_silver_tag: 'Silver · TZS 25,000/day', boost_gold: 'Gold', boost_gold_tag: 'Gold · TZS 45,000/day',
  boost_done: 'Product is boosted now', boost_failed: 'Boost payment failed', boost_need_product: 'List a product first.',
  boost_pay: 'Pay boost', cancel: 'Cancel', cancel_order: 'Cancel order',
  cannot_follow_self: 'You cannot follow yourself.', chats_empty: 'No conversations yet.',
  clear_all: 'Clear all', close: 'Close', courier: 'Courier company', days: 'days',
  delivery_confirmed: 'You confirmed delivery — escrow will be released.', did_you_mean: 'Did you mean:',
  disp_damaged: 'Item is damaged', disp_not_received: 'I did not receive the item', disp_different: 'Significantly different from listing',
  disp_other: 'Other reason', disp_wrong_item: 'Wrong item',
  dispatch: 'Dispatch', dispute_desc: 'Dispute details', dispute_filed: 'Dispute opened.',
  dispute_reason: 'Dispute reason', div: 'div', input: 'input',
  issue_otp: 'Issue OTP', issue_otp_after: 'Hand the item to the buyer, then issue the OTP.',
  kyc: 'Verification', kyc_approved: 'Verification approved', kyc_done: 'You completed KYC.',
  kyc_full_name: 'Full name (as on ID)', kyc_id_number: 'ID number',
  kyc_id_type: 'ID type', kyc_submitted: 'Verification submitted for review.',
  kyc_upload_id: 'Upload ID', kyc_upload_selfie: 'Upload selfie',
  most_rated: 'Top rated', no_replies: 'No replies yet.', notification_deleted: 'Notification deleted.',
  otp_expires_note: 'OTP expires after 15 minutes.', otp_hand_to_buyer: 'Hand the item to the buyer, then request the OTP.',
  own_only: 'You can only delete your own.', pay_ok: 'Payment complete!', pay_push_note: 'USSD sent to your phone — pay and enter PIN.',
  pay_total: 'Amount to pay', product: 'Product', sales_30d: 'Sales last 30 days',
  seller_set_ship: 'Set shipping cost', ship_notes: 'Shipping notes (optional)',
  ship_notes_ph: 'E.g.: Tomorrow morning Dar', stats_completed: 'Completed', stats_gmv: 'Total sales (GMV)',
  tracking: 'Tracking number', trending: 'Trending', upload_ok: 'Uploaded!',
  wallet_earned: 'Earned', wallet_empty: 'No transactions yet.', wallet_frozen: 'Frozen amount',
  wallet_history: 'Wallet history', wallet_note: 'Funds stay in escrow until payment is verified.',
  wallet_pending: 'Pending', withdrawn: 'Withdrawn',
});
/* ---- Phase 1 redesign strings (sw) ---- */
Object.assign(SV_T.sw, {
  sv_kicker: 'Soko la Tanzania', soldout_ov: 'IMEISHA',
  sv_hero_title: 'Nunua vyema. Uza haraka. Lipa salama.',
  sv_hero_sub: 'Bidhaa halisi kutoka kwa wauzaji waliothibitishwa. Malipo ya TZS kwa escrow kupitia ClickPesa.',
  sv_cta_buy: 'Nunua Sasa', sv_cta_sell: 'Uza Sasa',
  sv_categories: 'Vinjari Kategoria', sv_categories_sub: 'Pata unachokihitaji haraka',
  sv_items: 'bidhaa', sv_deals: 'Bei Nzuri', sv_deals_sub: 'Zinazoangaziwa na punguzo',
  sv_view_all: 'Ona Zote', sv_sellers: 'Wauzaji Waliothibitishwa', sv_sellers_sub: 'Wahakikiwa na timu ya Soko Vibe',
  sv_customize_t: 'Tengeneza Duka', sv_customize_sub: 'Rangi ya duka', sv_customize_reset: 'Rudisha Default',
  sv_trust_escrow_p: 'Malipo yakishikiliwa hadi upokee bidhaa',
  sv_trust_verified_p: 'KYC ya kibanda huthibitishwa',
  sv_trust_clickpesa_p: 'Malipo ya TZS kwenye simu',
  sv_trust_delivery_p: 'Tanzania nzima',
  sv_seller_cta_t: 'Una kitu cha kuuza?',
  sv_seller_cta_p: 'Anza kibanda chako leo - hakuna ada ya jukwaa. Wateja walipie kwa escrow.',
  sv_seller_cta_btn: 'Anza Kibanda', out_stock: 'Zimeisha',
  sv_items_found: 'bidhaa zimepatikana', sv_all_bidhaa: 'Bidhaa Zote',
  sv_filter: 'Chuja', sv_f_cats: 'Kategoria', sv_f_brand: 'Chapa',
  sv_f_price: 'Bei (TZS)', sv_f_min: 'Kuanzia', sv_f_max: 'Hadi', sv_f_go: 'Weka',
  sv_f_cond: 'Hali', sv_cond_new: 'Mpya', sv_cond_used: 'Imetumika', sv_cond_refurb: 'Imekarabatiwa',
  sv_f_rating: 'Uhakiki', sv_f_ver: 'Wauzaji waliothibitishwa', sv_f_ws: 'Kwa jumla',
  sv_f_disc: 'Zilizopunguzwa bei', sv_f_clear: 'Futa vyote', sv_f_remove: 'Ondoa kichujio',
  sv_sort: 'Panga', sv_sort_rel: 'Zinazohusiana', sv_sort_newest: 'Mpya kabisa',
  sv_sort_price_up: 'Bei: Chini kwenda Juu', sv_sort_price_dn: 'Bei: Juu kwenda Chini',
  sv_sort_rating: 'Uhakiki wa juu', sv_sort_sold: 'Zilizouzwa zaidi',
  sv_sort_disc: 'Punguzo kubwa', sv_sort_name: 'Jina A-Z',
  sv_view_grid: 'Gridi', sv_view_list: 'Orodha', sv_did_you_mean: 'Ulikusudia',
sv_no_results: 'Hakuna bidhaa zinazolingana',
  sv_try_diff: 'Jaribu maneno mengine au ondoa vichujio ili kuona bidhaa zaidi.',
  sv_ver_seller: 'Muuzaji aliyethibitishwa', sv_items: 'bidhaa', sv_msg_seller: 'Mpe Ujumbe',
  sv_store_products: 'Bidhaa za Kibanda', sv_no_products: 'Hakuna bidhaa bado', sv_store: 'Kibanda',
sv_back_home: 'Rudi kwenye Bidhaa Zote', sv_recent: 'Ulitafuta',
  sv_products: 'Bidhaa', sv_clear: 'Futa historia', sv_sugg_hint: 'Anza kuandika...',
  sv_crumb_search: 'Utafutaji',
  sv_continue: 'Endelea Kununua', sv_group_subtotal: 'Jumla ya muuzaji',
  sv_buy: 'Nunua', sv_boosted: 'Imetangazwa',
  sv_promo_t: 'Gundua bidhaa kutoka kwa wauzaji wanaoaminika kote Tanzania.',
  sv_promo_p: 'Nunua kutoka maduka yaliyothibitishwa, lipa kwa escrow salama, usafirishaji kote Tanzania.',
  sv_cta_deals: 'Nunua Sasa', sv_cta_cats: 'Chunguza Kategoria', sv_best: 'Zinauzwa Zaidi', sv_new: 'Mpya Kwenye Soko',
  sv_recently_viewed: 'Umetazama Hivi Karibuni', cannot_buy_own: 'Huwezi kununua bidhaa yako mwenyewe',
  sv_more_seller: 'Zaidi kutoka kwa muuzaji huyu', sv_price_dropped: 'Bei imeshuka', sv_refresh: 'Pakia upya', sv_since: 'Tangu', sv_no_following: 'Hufuati muuzaji yeyote bado', sv_followed_sellers: 'Wauzaji unaowafuata', sv_result_sellers: 'Wauzaji kwenye matokeo',
  sv_related: 'Bidhaa Zinazohusiana', sv_del_ests: 'Uwasilishaji: siku 1–4 za kazi',
  cart_items: 'Vipengee', cart_fee: 'Ada ya huduma',
});

/* ---- Phase 1 redesign strings (en) ---- */
Object.assign(SV_T.en, {
  sv_kicker: 'Tanzania marketplace', soldout_ov: 'SOLD OUT',
  sv_hero_title: 'Shop well. Sell fast. Pay safe.',
  sv_hero_sub: 'Real products from verified sellers. TZS payments held in escrow via ClickPesa.',
  sv_cta_buy: 'Shop Now', sv_cta_sell: 'Sell Now',
  sv_categories: 'Browse Categories', sv_categories_sub: 'Find what you need fast',
  sv_items: 'items', sv_deals: 'Great Prices', sv_deals_sub: 'Featured and discounted',
  sv_view_all: 'View All', sv_sellers: 'Verified Sellers', sv_sellers_sub: 'Checked by the Soko Vibe team',
  sv_customize_t: 'Customize Shop', sv_customize_sub: 'Shop accent color', sv_customize_reset: 'Reset to default',
  sv_trust_escrow_p: 'Payment held until you receive the item',
  sv_trust_verified_p: 'Store KYC is verified',
  sv_trust_clickpesa_p: 'TZS payments on your phone',
  sv_trust_delivery_p: 'Across Tanzania',
  sv_seller_cta_t: 'Got something to sell?',
  sv_seller_cta_p: 'Start your store today - no platform fee. Buyers pay through escrow.',
  sv_seller_cta_btn: 'Start Selling', out_stock: 'Out of stock',
  sv_items_found: 'products found', sv_all_bidhaa: 'All Products',
  sv_filter: 'Filter', sv_f_cats: 'Categories', sv_f_brand: 'Brand',
  sv_f_price: 'Price (TZS)', sv_f_min: 'From', sv_f_max: 'To', sv_f_go: 'Apply',
  sv_f_cond: 'Condition', sv_cond_new: 'New', sv_cond_used: 'Used', sv_cond_refurb: 'Refurbished',
  sv_f_rating: 'Rating', sv_f_ver: 'Verified sellers', sv_f_ws: 'Wholesale' , sv_f_disc: 'Discounted',
  sv_f_clear: 'Clear all', sv_f_remove: 'Remove filter',
  sv_sort: 'Sort', sv_sort_rel: 'Relevance', sv_sort_newest: 'Newest',
sv_sort_price_up: 'Price: Low to High', sv_sort_price_dn: 'Price: High to Low',
  sv_sort_rating: 'Top rated', sv_sort_sold: 'Best selling',
 sv_sort_disc: 'Biggest discount', sv_sort_name: 'Name A-Z',
  sv_view_grid: 'Grid', sv_view_list: 'List', sv_did_you_mean: 'Did you mean',
  sv_no_results: 'No matching products',
  sv_try_diff: 'Try different keywords or remove filters to see more products.',
  sv_ver_seller: 'Verified seller', sv_items: 'items', sv_msg_seller: 'Message Seller',
  sv_store_products: 'Store Products', sv_no_products: 'No products yet', sv_store: 'Seller Store',
  sv_offline: 'You are offline — you can still browse cached content, but actions need internet',
  dismiss: 'Dismiss', sv_all_orders: 'Zote', sv_active: 'In Progress', sv_completed: 'Completed', sv_cancelled: 'Cancelled',
  sv_back_home: 'Back to All Products', sv_recent: 'Recent searches',
  sv_products: 'Products', sv_clear: 'Clear history', sv_sugg_hint: 'Start typing...',
  sv_crumb_search: 'Search',
  sv_continue: 'Continue Shopping', sv_group_subtotal: 'Seller subtotal',
  sv_buy: 'Buy Now', sv_boosted: 'Boosted',
  sv_promo_t: 'Discover products from trusted sellers across Tanzania.',
  sv_promo_p: 'Shop from verified stores, pay safely through escrow, delivered across Tanzania.',
  sv_cta_deals: 'Shop Now', sv_cta_cats: 'Explore Categories', sv_best: 'Best Sellers', sv_new: 'New Arrivals',
  sv_recently_viewed: 'Recently Viewed', cannot_buy_own: 'You cannot buy your own product',
  sv_more_seller: 'More from this seller', sv_price_dropped: 'Price dropped', sv_refresh: 'Refresh', sv_since: 'Since', sv_no_following: 'You are not following any seller yet', sv_followed_sellers: 'Sellers you follow', sv_result_sellers: 'Sellers in results',
  sv_related: 'Related Products', sv_del_ests: 'Delivery: 1–4 working days',
  cart_items: 'Items', cart_fee: 'Service fee',
});
