// Soko Vibe Duka — static data: categories, regions/districts, labels.
// Regions + districts generated from lib/constants/tanzania_districts.dart
// (CC-BY-4.0 open-admin-data, 31 regions). Labels are sw default + en.

const SV_CATEGORIES = [
  'Phones & Tablets', 'Electronics', 'Fashion & Clothing', 'Home & Garden',
  'Vehicles & Spare Parts', 'Health & Beauty', 'Sports & Outdoors',
  'Toys & Games', 'Books & Stationery', 'Supermarket', 'Agriculture', 'Services',
];

// Sub-category menus for the left mega nav, mirroring how the app groups
// products by category + subcategory fields.
const SV_SUBCATS = {
  'Phones & Tablets': ['Smartphones', 'Feature Phones', 'Tablets', 'Phone Accessories', 'Phone Cases'],
  'Electronics': ['TVs & Audio', 'Computers & Laptops', 'Cameras', 'Gaming', 'Home Appliances'],
  'Fashion & Clothing': ["Men's Fashion", "Women's Fashion", "Kids Fashion", 'Shoes', 'Bags & Accessories'],
  'Home & Garden': ['Furniture', 'Kitchen', 'Decor', 'Garden & Outdoor'],
  'Vehicles & Spare Parts': ['Cars', 'Motorbikes', 'Bicycles', 'Spare Parts'],
  'Health & Beauty': ['Cosmetics', 'Personal Care', 'Fragrances', 'Supplements'],
  'Sports & Outdoors': ['Fitness', 'Sportswear', 'Camping', 'Fishing'],
  'Toys & Games': ['Kids Toys', 'Remote Control', 'Board Games'],
  'Books & Stationery': ['Books', 'Stationery', 'Office Supplies'],
  'Supermarket': ['Food & Beverages', 'Household', 'Personal Care', 'Fresh'],
  'Agriculture': ['Farm Produce', 'Livestock', 'Machinery', 'Seeds & Fertilizer'],
  'Services': ['Delivery & Transport', 'Repairs', 'Rental', 'Professional'],
};

const SV_REGIONS = ["Arusha","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi","Manyara","Mara","Mbeya","Mjini Magharibi","Morogoro","Mtwara","Mwanza","Njombe","Pwani","Rukwa","Ruvuma","Shinyanga","Simiyu","Singida","Songwe","Tabora","Tanga","Kaskazini Pemba","Kusini Pemba","Kaskazini Unguja","Kusini Unguja"];

const SV_DISTRICTS = {"Rukwa":["Kalambo","Nkasi","Sumbawanga City","Sumbawanga"],"Songwe":["Ileje","Mbozi","Momba","Songwe","Tunduma"],"Kilimanjaro":["Hai","Moshi City","Moshi","Mwanga","Rombo","Same","Siha"],"Mtwara":["Masasi City","Masasi","Mtwara City","Mtwara","Nanyumbu","Newala City","Newala","Tandahimba"],"Kaskazini Unguja":["Kaskazini A","Kaskazini B"],"Kagera":["Biharamulo","Bukoba City","Bukoba","Karagwe","Kyerwa","Missenyi","Muleba","Ngara"],"Mjini Magharibi":["Magharibi","Mjini"],"Kaskazini Pemba":["Wete","Micheweni"],"Pwani":["Bagamoyo","Chalinze","Kibaha City","Kibaha","Kisarawe","Mafia","Mkuranga","Rufiji"],"Simiyu":["Bariadi","Busega","Itilima","Maswa","Meatu"],"Dar es Salaam":["Ilala","Kigamboni","Kinondoni","Temeke","Ubungo"],"Shinyanga":["Kahama City","Kahama","Kishapu","Msalala","Shinyanga City","Shinyanga","Ushetu"],"Manyara":["Babati City","Babati","Hanang","Kiteto","Mbulu","Simanjiro"],"Mara":["Bunda","Butiama","Musoma City","Musoma","Rorya","Serengeti","Tarime"],"Tanga":["Bumbuli","Handeni City","Handeni","Kilindi","Korogwe City","Korogwe","Lushoto","Mkinga","Muheza","Pangani","Tanga City"],"Morogoro":["Gairo","Ifakara","Kilombero","Kilosa","Malinyi","Morogoro City","Morogoro","Mvomero","Ulanga"],"Kusini Pemba":["Chake Chake","Mkoani"],"Dodoma":["Bahi","Chamwino","Chemba","Dodoma City","Kongwa","Kondoa","Mpwapwa"],"Singida":["Ikungi","Iramba","Itigi","Manyoni","Mkalama","Singida City","Singida"],"Ruvuma":["Mbinga","Namtumbo","Nyasa","Songea City","Songea","Tunduru"],"Kusini Unguja":["Kati","Kusini"],"Katavi":["Mlele","Mpanda","Mpimbwe","Tanganyika"],"Lindi":["Kilwa","Lindi City","Lindi","Liwale","Nachingwea","Ruangwa"],"Geita":["Bukombe","Chato","Geita","Mbogwe","Nyang'hwale"],"Tabora":["Igunga","Kaliua","Nzega","Sikonge","Tabora City","Urambo","Uyui"],"Arusha":["Arusha City","Arusha","Karatu","Longido","Meru","Monduli","Ngorongoro"],"Iringa":["Iringa City","Iringa","Kilolo","Mufindi"],"Kigoma":["Buhigwe","Kakonko","Kasulu City","Kasulu","Kibondo","Kigoma City","Kigoma","Uvinza"],"Mbeya":["Busokelo","Chunya","Kyela","Mbarali","Mbeya City","Mbeya","Rungwe"],"Mwanza":["Bukoba City","Buchosa","Kwimba","Magu","Misungwi","Nyamagana","Sengerema","Ukerewe"]};

const SV_T = {
  sw: {
    nav_home: 'Nyumbani', nav_categories: 'Kategoria', nav_orders: 'Agizo Zangu',
    nav_account: 'Akaunti', nav_signin: 'Ingia', search_ph: 'Tafuta bidhaa...',
    splash_p: 'Hujambo! Duka la Soko Vibe linapakia bidhaa zako.',
    home_hero_kicker: 'Soko la Tanzania', home_hero_title: 'Nunua na kuuza popote Tanzania.',
    home_hero_sub: 'Malipo salama kupitia ClickPesa na escrow — bidhaa unayoipata ndiyo unayolipia.',
    home_new: 'Bidhaa mpya', home_browse: 'Vinjari', featured: 'Zinazoangaziwa',
    feed_all: 'Bidhaa Zote', feed_new: 'Bidhaa Mpya', trust_escrow: 'Escrow Protected',
    trust_verified: 'Verified Sellers', trust_clickpesa: 'ClickPesa Secured', trust_delivery: 'Nationwide Delivery',
    checkout_step_addr: 'Anwani', checkout_step_pay: 'Malipo', checkout_step_done: 'Uthibitisho',
    addr_heading: 'Anwani ya Ununuzi', summary_heading: 'Muhtasari wa Agizo',
    escrow_note: 'Malipo yanashikiliwa kwa escrow kupitia ClickPesa hadi uthibitishe kupokea.',
    step_back: 'Rudi nyuma', step_next: 'Endelea', confirm_title: 'Agizo Limepokelewa',
    confirm_sub: 'Malipo yameingia escrow. Muuzaji ataanza kukusanyia bidhaa yako.',
    view_orders: 'Angalia Agizo Zangu', back_home: 'Endelea Kununua',
    categories: 'Kategoria', all: 'Zote', load_more: 'Pakia zaidi',
    empty: 'Hakuna bidhaa', empty_filter: 'Hakuna bidhaa zinazolingana',
    view_detail: 'Angalia', add_cart: 'Ongeza kwenye kikapu', buy_now: 'Nunua Sasa',
    in_stock: 'Zipo', out_stock: 'Zimeisha', qty: 'Idadi', add_to_cart_ok: 'Imeongezwa kwenye kikapu',
    cart_title: 'Kikapu', cart_empty: 'Kikapu chako kipo tupu.', cart_browse: 'Vinjari bidhaa',
    cart_seller: 'Muuzaji', remove: 'Ondoa', cart_total: 'Jumla', cart_checkout: 'Tengeneza oda',
    back: 'Rudi', seller: 'Muuzaji', condition: 'Hali', location: 'Mahali',
    description: 'Maelezo', attributes: 'Sifa nyingine', variants: 'Vitokezi',
    checkout_title: 'Malipo', checkout_addr: 'Anwani ya ununuzi',
    region: 'Mkoa', district: 'Wilaya', ward: 'Kata', street: 'Mtaa / barabara',
    landmarks: 'Alama za kipekee (si lazima)', phone: 'Namba ya simu (kwa USSD)',
    delivery: 'Namna ya kupokea', deliver_local: 'Ndani ya jiji / senioribu',
    fee_note: 'Ukomo wa mfumo (3.5%) + shipping unahesabiwa upande wa muuzaji',
    place_order: 'Tengeneza Oda na Ulipa', processing: 'Inachakata...',
    pay_wait: 'Tumekutumia USSD prompt kwenye simu yako. Lipa uone "Lipa" na weka PIN.',
    pay_status_pending: 'Inasubiri malipo...', pay_status_paid: 'Malipo yametambuliwa!',
    pay_done: 'Agizo limekamilishwa — escrow imeanzishwa.', pay_failed: 'Malipo hayajafika.',
    pay_new: 'Tuma USSD tena', order_created: 'Agizo limeanzishwa.',
    need_auth: 'Ingia kwanza ili kuendelea.', signin_title: 'Ingia',
    signup_title: 'Sajili akaunti', name: 'Jina kamili', email: 'Barua pepe',
    password: 'Nenosiri', have_account: 'Una akaunti?', no_account: 'Huna akaunti?',
    submit_signin: 'Ingia', submit_signup: 'Sajili', signout: 'Ondoka',
    profile: 'Akaunti yako', orders_my: 'Agizo Zangu', my_orders_empty: 'Huna agizo bado.',
    order_statuses: { pending: 'Inafanyiwa kazi', quoted: 'Imehifadhiwa kimasaa', paid: 'Imelipwa', escrow_hold: 'Escrow imeanzishwa', escrow_held: 'Escrow imeanzishwa', dispatched: 'Imesafirishwa', confirmed: 'Imetolewa', completed: 'Imekamilika', cancelled: 'Imeghairiwa', disputed: 'Kuna mzozo', refunded: 'Imerudishiwa', failed: 'Imeshindikana' },
    status_label: 'Hali', order_total: 'Jumla', order_date: 'Tarehe', order_id: 'Oda #', wa_cta: 'Wasiliana kwa WhatsApp',
    price: 'Bei', wait_fetch: 'Inapakia...', err_generic: 'Kuna tatizo. Jaribu tena.',
    theme_light: 'Mchana', theme_dark: 'Usiku', lang_label: 'Lugha', to_top: 'Juu',
    nav_wish: 'Unavyovipenda', nav_seller: 'Muuzaji', nav_seller_page: 'Kibanda changu',
    seller_become: 'Kuwa muuzaji', seller_you: 'Wewe ni muuzaji', sell_signup: 'Nina bidhaa za kuuza — kuwa muuzaji',
    seller_overview: 'Muhtasari', seller_products: 'Bidhaa zangu', seller_orders: 'Oda za kibanda', seller_wallet: 'Mlipo',
    stats_products: 'Bidhaa', stats_active: 'Zimechapishwa', stats_sold: 'Zimeuzwa', stats_orders: 'Oda', stats_pending_orders: 'Oda zinazosubiri',
    not_seller: 'Bado huuzi hapa. Fungua kibanda chako kisha uweke bidhaa zako.', seller_balance_lbl: 'Salio lako',
    new_product: 'Ongeza bidhaa', edit_product: 'Hariri', save_product: 'Hifadhi bidhaa',
    publish: 'Chapisha', unpublish: 'Ficha', delete_product: 'Futa', del_confirm: 'Una uhakika kufuta bidhaa hii?',
    product_name: 'Jina la bidhaa', product_price: 'Bei (TZS)', product_stock: 'Idadi (stock)', product_cond: 'Hali',
    product_cat: 'Kategoria', product_subcat: 'Subcategory (si lazima)', product_desc: 'Maelezo',
    product_imgs: 'Picha (URL, tenga kwa koma)', product_loc: 'Mahali (Mkoa, Wilaya)',
    ws_toggle: 'Uza jumla (wholesale)', ws_min: 'Idadi (min)', ws_price: 'Bei kwa kipande', jumla_tbl: 'Jumla (wholesale)',
    cond_new: 'Mpya', cond_used: 'Imetumika', cond_refurbished: 'Refurbished',
    sold: 'imeuzwa', wish_title: 'Unavyovipenda', wish_hint: 'Bidhaa ulizoziweka', wish_empty: 'Huna bidhaa zozote hapa bado. Tumia kipini cha moyo kwenye bidhaa.',
    wish_saved: 'Imehifadhiwa kwenye wishlist', wish_removed: 'Imetolewa kwenye wishlist',
    reviews: 'Tathmini', no_reviews: 'Hakuna tathmini bado.', write_review: 'Andika tathmini',
    your_rating: 'Alama zako', your_comment: 'Maoni', submit_review: 'Tuma tathmini', review_ok: 'Tathmini imetumwa — asante!',
    share: 'Shiriki', copy_link: 'Nakili kiungo', copied: 'Imenakiliwa', soldout_ov: 'ZIMEISHA',
    guest_note: 'Unununua bila akaunti: oda yako inafungwa kwenye namba ya simu uliyoiweka. USSD utatumwa kwenye namba hiyo.',
    guest_name: 'Jina lako', need_name_phone: 'Andika jina na namba ya simu kikamilifu.',
    withdraw: 'Toa fedha', withdraw_amt: 'Kiasi (TZS)', withdraw_phone: 'Namba ya simu ya ClickPesa',
    withdraw_ok: 'Ulipokelewa! Fedha zinachakatwa.', min_withdraw: 'Kiwango cha chini ni TZS 10,000.',
    feat_until: 'Inaangaziwa', notchr: 'Tanzania', sold_by: 'Kiuza',
  },
  en: {
    nav_home: 'Home', nav_categories: 'Categories', nav_orders: 'My Orders',
    nav_account: 'Account', nav_signin: 'Sign in', search_ph: 'Search products...',
    splash_p: 'Hi! The Soko Vibe shop is loading your products.',
    home_hero_kicker: 'Tanzania\'s marketplace', home_hero_title: 'Buy and sell anywhere in Tanzania.',
    home_hero_sub: 'Secure ClickPesa payments and escrow — pay only for what you receive.',
    home_new: 'New arrivals', home_browse: 'Browse', featured: 'Featured',
    feed_all: 'All Products', feed_new: 'New Arrivals', trust_escrow: 'Escrow Protected',
    trust_verified: 'Verified Sellers', trust_clickpesa: 'ClickPesa Secured', trust_delivery: 'Nationwide Delivery',
    checkout_step_addr: 'Address', checkout_step_pay: 'Payment', checkout_step_done: 'Confirmation',
    addr_heading: 'Delivery address', summary_heading: 'Order summary',
    escrow_note: 'Payment is held in escrow by ClickPesa until you confirm receipt.',
    step_back: 'Go back', step_next: 'Continue', confirm_title: 'Order Received',
    confirm_sub: 'Payment reached escrow. The seller will start preparing your order.',
    view_orders: 'View my orders', back_home: 'Keep shopping',
    categories: 'Categories', all: 'All', load_more: 'Load more',
    empty: 'No products', empty_filter: 'No matching products',
    view_detail: 'View', add_cart: 'Add to cart', buy_now: 'Buy now',
    in_stock: 'In stock', out_stock: 'Out of stock', qty: 'Qty',
    add_to_cart_ok: 'Added to cart', cart_title: 'Cart', cart_empty: 'Your cart is empty.',
    cart_browse: 'Browse products', cart_seller: 'Seller', remove: 'Remove',
    cart_total: 'Total', cart_checkout: 'Place order', back: 'Back',
    seller: 'Seller', condition: 'Condition', location: 'Location',
    description: 'Description', attributes: 'More info', variants: 'Variants',
    checkout_title: 'Checkout', checkout_addr: 'Delivery address',
    region: 'Region', district: 'District', ward: 'Ward', street: 'Street / road',
    landmarks: 'Landmarks (optional)', phone: 'Phone number (for USSD)',
    delivery: 'Delivery', deliver_local: 'Local delivery',
    fee_note: 'Platform fee (3.5%) + shipping are computed by the seller end',
    place_order: 'Place order & Pay', processing: 'Processing...',
    pay_wait: 'We sent a USSD prompt to your phone. Confirm, enter your PIN, pay.',
    pay_status_pending: 'Waiting for payment...', pay_status_paid: 'Payment received!',
    pay_done: 'Order complete — escrow activated.', pay_failed: 'Payment not received.',
    pay_new: 'Send USSD again', order_created: 'Order created.',
    need_auth: 'Sign in to continue.', signin_title: 'Sign in',
    signup_title: 'Create account', name: 'Full name', email: 'Email',
    password: 'Password', have_account: 'Have an account?', no_account: 'No account yet?',
    submit_signin: 'Sign in', submit_signup: 'Sign up', signout: 'Sign out',
    profile: 'Your account', orders_my: 'My Orders', my_orders_empty: 'No orders yet.',
    order_statuses: { pending: 'Pending', quoted: 'Price quoted', paid: 'Paid', escrow_hold: 'Escrow active', escrow_held: 'Escrow active', dispatched: 'Dispatched', confirmed: 'Released', completed: 'Completed', cancelled: 'Cancelled', disputed: 'Disputed', refunded: 'Refunded', failed: 'Failed' },
    status_label: 'Status', order_total: 'Total', order_date: 'Date', order_id: 'Order #',
    wa_cta: 'Chat on WhatsApp', price: 'Price', wait_fetch: 'Loading...',
    err_generic: 'Something went wrong. Try again.',
    theme_light: 'Light', theme_dark: 'Dark', lang_label: 'Language', to_top: 'Top',
    nav_wish: 'Wishlist', nav_seller: 'Seller', nav_seller_page: 'My store',
    seller_become: 'Become a seller', seller_you: 'You are a seller', sell_signup: 'I have products to sell — become a seller',
    seller_overview: 'Overview', seller_products: 'My products', seller_orders: 'Store orders', seller_wallet: 'Wallet',
    stats_products: 'Products', stats_active: 'Published', stats_sold: 'Sold', stats_orders: 'Orders', stats_pending_orders: 'Pending orders',
    not_seller: 'You are not selling here yet. Open your store, then list your products.', seller_balance_lbl: 'Your balance',
    new_product: 'Add product', edit_product: 'Edit', save_product: 'Save product',
    publish: 'Publish', unpublish: 'Unpublish', delete_product: 'Delete', del_confirm: 'Delete this product? Are you sure?',
    product_name: 'Product name', product_price: 'Price (TZS)', product_stock: 'Stock', product_cond: 'Condition',
    product_cat: 'Category', product_subcat: 'Subcategory (optional)', product_desc: 'Description',
    product_imgs: 'Images (URLs, comma-separated)', product_loc: 'Location (Region, District)',
    ws_toggle: 'Wholesale', ws_min: 'Min qty', ws_price: 'Unit price', jumla_tbl: 'Wholesale',
    cond_new: 'New', cond_used: 'Used', cond_refurbished: 'Refurbished',
    sold: 'sold', wish_title: 'Wishlist', wish_hint: 'Products you saved', wish_empty: 'No saved products yet. Tap the heart on any product.',
    wish_saved: 'Saved to wishlist', wish_removed: 'Removed from wishlist',
    reviews: 'Reviews', no_reviews: 'No reviews yet.', write_review: 'Write a review',
    your_rating: 'Your rating', your_comment: 'Comment', submit_review: 'Submit review', review_ok: 'Review submitted — thanks!',
    share: 'Share', copy_link: 'Copy link', copied: 'Copied', soldout_ov: 'OUT OF STOCK',
    guest_note: 'Checking out without an account: your order is tied to the phone number you enter. The USSD prompt goes to that number.',
    guest_name: 'Your name', need_name_phone: 'Enter your name and a valid phone number.',
    withdraw: 'Withdraw', withdraw_amt: 'Amount (TZS)', withdraw_phone: 'ClickPesa phone number',
    withdraw_ok: 'Request received! Funds are processing.', min_withdraw: 'Minimum withdrawal is TZS 10,000.',
    feat_until: 'Featured', notchr: 'Tanzania', sold_by: 'Seller',
  },
};

const SV_STATUS_ORDER = [
  'pending', 'quoted', 'paid', 'escrow_hold', 'escrow_held', 'dispatched',
  'confirmed', 'completed', 'disputed', 'refunded', 'cancelled', 'failed',
];