/// Tanzania regions, districts, and wards (kata).
///
/// District and ward data generated from the open-admin-data
/// tanzania-administrative-divisions dataset (31 regions, 170
/// districts, 3643 wards), licensed CC-BY-4.0, updated 2026-06-01.
/// Mainland district lists kept as curated council names (verified
/// against official 2022 council lists); Zanzibar districts added from the dataset.
const List<String> kRegions = [
  'Arusha',
  'Dar es Salaam',
  'Dodoma',
  'Geita',
  'Iringa',
  'Kagera',
  'Katavi',
  'Kigoma',
  'Kilimanjaro',
  'Lindi',
  'Manyara',
  'Mara',
  'Mbeya',
  'Mjini Magharibi',
  'Morogoro',
  'Mtwara',
  'Mwanza',
  'Njombe',
  'Pwani',
  'Rukwa',
  'Ruvuma',
  'Shinyanga',
  'Simiyu',
  'Singida',
  'Songwe',
  'Tabora',
  'Tanga',
  'Kaskazini Pemba',
  'Kusini Pemba',
  'Kaskazini Unguja',
  'Kusini Unguja',
];

const Map<String, List<String>> kRegionDistricts = {
  'Arusha': [
    'Arusha City',
    'Arusha',
    'Karatu',
    'Longido',
    'Meru',
    'Monduli',
    'Ngorongoro',
  ],
  'Dar es Salaam': ['Ilala', 'Kigamboni', 'Kinondoni', 'Temeke', 'Ubungo'],
  'Dodoma': [
    'Bahi',
    'Chamwino',
    'Chemba',
    'Dodoma City',
    'Kongwa',
    'Kondoa',
    'Mpwapwa',
  ],
  'Geita': ['Bukombe', 'Chato', 'Geita', 'Mbogwe', 'Nyang\'hwale'],
  'Iringa': ['Iringa City', 'Iringa', 'Kilolo', 'Mufindi'],
  'Kagera': [
    'Biharamulo',
    'Bukoba City',
    'Bukoba',
    'Karagwe',
    'Kyerwa',
    'Missenyi',
    'Muleba',
    'Ngara',
  ],
  'Katavi': ['Mlele', 'Mpanda', 'Mpimbwe', 'Tanganyika'],
  'Kigoma': [
    'Buhigwe',
    'Kakonko',
    'Kasulu City',
    'Kasulu',
    'Kibondo',
    'Kigoma City',
    'Kigoma',
    'Uvinza',
  ],
  'Kilimanjaro': [
    'Hai',
    'Moshi City',
    'Moshi',
    'Mwanga',
    'Rombo',
    'Same',
    'Siha',
  ],
  'Lindi': ['Kilwa', 'Lindi City', 'Lindi', 'Liwale', 'Nachingwea', 'Ruangwa'],
  'Manyara': [
    'Babati City',
    'Babati',
    'Hanang',
    'Kiteto',
    'Mbulu',
    'Simanjiro',
  ],
  'Mara': [
    'Bunda',
    'Butiama',
    'Musoma City',
    'Musoma',
    'Rorya',
    'Serengeti',
    'Tarime',
  ],
  'Mbeya': [
    'Busokelo',
    'Chunya',
    'Kyela',
    'Mbarali',
    'Mbeya City',
    'Mbeya',
    'Rungwe',
  ],
  'Mjini Magharibi': ['Magharibi', 'Mjini'],
  'Morogoro': [
    'Gairo',
    'Ifakara',
    'Kilombero',
    'Kilosa',
    'Malinyi',
    'Morogoro City',
    'Morogoro',
    'Mvomero',
    'Ulanga',
  ],
  'Mtwara': [
    'Masasi City',
    'Masasi',
    'Mtwara City',
    'Mtwara',
    'Nanyumbu',
    'Newala City',
    'Newala',
    'Tandahimba',
  ],
  'Mwanza': [
    'Buchosa',
    'Ilemela',
    'Kwimba',
    'Magu',
    'Misungwi',
    'Mwanza City',
    'Nyamagana',
    'Sengerema',
    'Ukerewe',
  ],
  'Njombe': [
    'Ludewa',
    'Makambako',
    'Makete',
    'Njombe City',
    'Njombe',
    'Wanging\'ombe',
  ],
  'Pwani': [
    'Bagamoyo',
    'Chalinze',
    'Kibaha City',
    'Kibaha',
    'Kisarawe',
    'Mafia',
    'Mkuranga',
    'Rufiji',
  ],
  'Rukwa': ['Kalambo', 'Nkasi', 'Sumbawanga City', 'Sumbawanga'],
  'Ruvuma': ['Mbinga', 'Namtumbo', 'Nyasa', 'Songea City', 'Songea', 'Tunduru'],
  'Shinyanga': [
    'Kahama City',
    'Kahama',
    'Kishapu',
    'Msalala',
    'Shinyanga City',
    'Shinyanga',
    'Ushetu',
  ],
  'Simiyu': ['Bariadi', 'Busega', 'Itilima', 'Maswa', 'Meatu'],
  'Singida': [
    'Ikungi',
    'Iramba',
    'Itigi',
    'Manyoni',
    'Mkalama',
    'Singida City',
    'Singida',
  ],
  'Songwe': ['Ileje', 'Mbozi', 'Momba', 'Songwe', 'Tunduma'],
  'Tabora': [
    'Igunga',
    'Kaliua',
    'Nzega',
    'Sikonge',
    'Tabora City',
    'Tabora',
    'Urambo',
    'Uyui',
  ],
  'Tanga': [
    'Bumbuli',
    'Handeni City',
    'Handeni',
    'Kilindi',
    'Korogwe City',
    'Korogwe',
    'Lushoto',
    'Mkinga',
    'Muheza',
    'Pangani',
    'Tanga City',
  ],
  'Kaskazini Pemba': ['Wete', 'Micheweni'],
  'Kusini Pemba': ['Chake Chake', 'Mkoani'],
  'Kaskazini Unguja': ['Kaskazini A', 'Kaskazini B'],
  'Kusini Unguja': ['Kati', 'Kusini'],
};

/// Kata (wards) per district, from the 2026 administrative dataset.
/// Districts without an entry have no kata data; the checkout screen
/// hides the kata dropdown for those and keeps the street field required.
const Map<String, List<String>> kDistrictWards = {
  'Arusha': [
    'Bangata',
    'Bwawani',
    'Ilkiding\'a',
    'Kimnyaki',
    'Kiranyi',
    'Kisongo',
    'Mateves',
    'Mlangarini',
    'Moivo',
    'Mussa',
    'Mwandeti',
    'Nduruma',
    'Oldonyosambu',
    'Oljoro',
    'Olkokola',
    'Olmotonyi',
    'Olorieni',
    'Oltoroto',
    'Oltrumet',
    'Sambasha',
    'Sokon II',
  ],
  'Arusha City': [
    'Baraa',
    'Daraja Mbili',
    'Elerai',
    'Engutoto',
    'Kaloleni',
    'Kati',
    'Kimandolu',
    'Lemara',
    'Levolosi',
    'Moshono',
    'Ngarenaro',
    'Olasiti',
    'Oloirieni',
    'Sekei',
    'Sokoni I',
    'Sombetini',
    'Terrat',
    'Themi',
    'Unga Ltd',
  ],
  'Babati': [
    'Arri',
    'Ayasanda',
    'Bashneti',
    'Boay',
    'Dabil',
    'Dareda',
    'Duru',
    'Endokise',
    'Galapo',
    'Gidas',
    'Kiru',
    'Madunga',
    'Magara',
    'Magugu',
    'Mamire',
    'Mwada',
    'Nar',
    'Nkaiti',
    'Qashi',
    'Riroda',
    'Ufana',
  ],
  'Babati City': [
    'Babati',
    'Bagara',
    'Bonga',
    'Maisaka',
    'Mutuka',
    'Nangara',
    'Sigino',
    'Singe',
  ],
  'Bagamoyo': [
    'Bwilingu',
    'Dunda',
    'Fukayose',
    'Kerege',
    'Kibindu',
    'Kimange',
    'Kiromo',
    'Kiwangwa',
    'Lugoba',
    'Magomeni',
    'Mandera',
    'Mbwewe',
    'Miono',
    'Mkange',
    'Msata',
    'Msoga',
    'Pera',
    'Talawanda',
    'Ubenazomozi',
    'Vigwaza',
    'Yombo',
    'Zinga',
  ],
  'Bahi': [
    'Babayu',
    'Bahi',
    'Chali',
    'Chibelela',
    'Chikola',
    'Chipanga',
    'Ibihwa',
    'Ibugule',
    'Ilindi',
    'Kigwe',
    'Lamaiti',
    'Makanda',
    'Mpalanga',
    'Mpamantwa',
    'Msisi',
    'Mtitaa',
    'Mundemu',
    'Mwitikira',
    'Nondwa',
    'Zanka',
  ],
  'Bariadi': [
    'Bariadi',
    'Bunamhala',
    'Dutwa',
    'Gambosi',
    'Gilya',
    'Guduwi',
    'Ikungulyabashashi',
    'Isanga',
    'Kasoli',
    'Kilalo',
    'Madobana',
    'Malambo',
    'Matongo',
    'Mhango',
    'Mwaubinge',
    'Mwaumatondo',
    'Ngulyati',
    'Nkindwabiye',
    'Nkololo',
    'Nyakabindi',
    'Nyangokolwa',
    'Sakwe',
    'Sapiwi',
    'Sima',
    'Somanda',
  ],
  'Biharamulo': [
    'Biharamulo Mjini',
    'Bisibo',
    'Kabindi',
    'Kalenge',
    'Kaniha',
    'Lusahunga',
    'Nemba',
    'Nyabusozi',
    'Nyakahura',
    'Nyamahanga',
    'Nyamigogo',
    'Nyantakara',
    'Nyarubungo',
    'Runazi',
    'Ruziba',
  ],
  'Buhigwe': [
    'Biharu',
    'Buhigwe',
    'Janda',
    'Kajana',
    'Kibande',
    'Kilelema',
    'Mugera',
    'Muhinda',
    'Munanila',
    'Munyegera',
    'Munzeze',
    'Muyama',
    'Mwayaya',
    'Nyamugali',
    'Rusaba',
  ],
  'Bukoba': [
    'Buhendangabo',
    'Bujugo',
    'Butelankuzi',
    'Butulage',
    'Ibwera',
    'Izimbya',
    'Kaagya',
    'Kaibanja',
    'Kanyangereko',
    'Karabagaine',
    'Kasharu',
    'Katerero',
    'Katoma',
    'Katoro',
    'Kemondo',
    'Kibirizi',
    'Kikomero',
    'Kishanje',
    'Kishogo',
    'Kyamulaile',
    'Maruku',
    'Mikoni',
    'Mugajwale',
    'Nyakato',
    'Nyakibimbili',
    'Rubafu',
    'Rubale',
    'Ruhunga',
    'Rukoma',
  ],
  'Bukoba City': [
    'Bakoba',
    'Bilele',
    'Buhemba',
    'Hamugembe',
    'Ijuganyondo',
    'Kagondo',
    'Kahororo',
    'Kashai',
    'Kibeta',
    'Kitendaguro',
    'Miembeni',
    'Nshambya',
    'Nyanga',
    'Rwamishenye',
  ],
  'Bukombe': [
    'Bugelenga',
    'Bukombe',
    'Busonzo',
    'Butinzya',
    'Igulwa',
    'Iyogelo',
    'Lyambamgongo',
    'Namonge',
    'Ng\'anzo',
    'Runzewe Magharibi',
    'Runzewe Mashariki',
    'Ushirombo',
    'Uyovu',
  ],
  'Bunda': [
    'Balili',
    'Bunda Mjini',
    'Bunda Stoo',
    'Butimba',
    'Chitengule',
    'Guta',
    'Hunyari',
    'Igundu',
    'Iramba',
    'Kabasa',
    'Kasuguti',
    'Ketare',
    'Kibara',
    'Kisorya',
    'Kunzugu',
    'Mcharo',
    'Mihingo',
    'Mugeta',
    'Namhula',
    'Nampindi',
    'Nansimo',
    'Neruma',
    'Nyamang\'uta',
    'Nyamuswa',
    'Nyasura',
    'Salama',
    'Sazira',
    'Wariku',
  ],
  'Busega': [
    'Badugu',
    'Igalukilo',
    'Kabita',
    'Kalemela',
    'Kiloleli',
    'Lamadi',
    'Lutubiga',
    'Malili',
    'Mkula',
    'Mwamanyili',
    'Ngasamo',
    'Nyaluhande',
    'Shigala',
  ],
  'Butiama': [
    'Bisumwa',
    'Buhemba',
    'Bukabwa',
    'Buruma',
    'Busegwe',
    'Buswahili',
    'Butiama',
    'Butuguri',
    'Bwiregi',
    'Etaro',
    'Kukirango',
    'Kyanyari',
    'Masaba',
    'Mirwa',
    'Muriaza',
    'Nyakatende',
    'Nyamimange',
    'Nyankanga',
    'Nyegina',
    'Sirorisimba',
  ],
  'Chake Chake': [
    'Chachani',
    'Chanjaani',
    'Chonga',
    'Dodo',
    'Kibokoni',
    'Kichungwani',
    'Kilindi',
    'Kwale',
    'Madungu',
    'Matale',
    'Mbuzini',
    'Mfikiwa',
    'Mgelema',
    'Mgogoni',
    'Michungwani',
    'Mkoroshoni',
    'Msingini',
    'Mvumoni',
    'Ndagoni',
    'Ng\'ambwa',
    'Pujini',
    'Shungi',
    'Tibirinzi',
    'Uwandani',
    'Vitongoji',
    'Wara',
    'Wawi',
    'Wesha',
    'Ziwani',
  ],
  'Chamwino': [
    'Buigiri',
    'Chiboli',
    'Chilonwa',
    'Chinugulu',
    'Dabalo',
    'Fufu',
    'Handali',
    'Haneti',
    'Huzi',
    'Idifu',
    'Igandu',
    'Ikowa',
    'Iringamvumi',
    'Itiso',
    'Loje',
    'Majeleko',
    'Makang\'wa',
    'Manchali',
    'Manda',
    'Manzase',
    'Membe',
    'Mlowa Bwawani',
    'Mpwayungu',
    'Msamalo',
    'Msanga',
    'Muungano',
    'Mvumi Makulu',
    'Mvumi Mission',
    'Nghambaku',
    'Nhinhi',
    'Segala',
    'Zajilwa',
  ],
  'Chato': [
    'Bukome',
    'Buseresere',
    'Butengorumasa',
    'Buziku',
    'Bwanga',
    'Bwera',
    'Bwina',
    'Bwongera',
    'Chato',
    'Ichwankima',
    'Ilemela',
    'Ilyamchele',
    'Iparamasa',
    'Kachwamba',
    'Kasenga',
    'Katende',
    'Kigongo',
    'Makurugusi',
    'Muganza',
    'Muungano',
    'Nyamirembe',
    'Nyarutembo',
  ],
  'Chemba': [
    'Chandama',
    'Chemba',
    'Churuku',
    'Dalai',
    'Farkwa',
    'Goima',
    'Gwandi',
    'Jangalo',
    'Kimaha',
    'Kwamtoro',
    'Lalta',
    'Makorongo',
    'Mondo',
    'Mpendo',
    'Mrijo',
    'Msaada',
    'Ovada',
    'Paranga',
    'Sanzawa',
    'Songoro',
  ],
  'Chunya': [
    'Chalangwa',
    'Chokaa',
    'Ifumbo',
    'Itewe',
    'Kambikatoto',
    'Lupatingatinga',
    'Luwalaje',
    'Mafyeko',
    'Makongorosi',
    'Mamba',
    'Matundasi',
    'Matwiga',
    'Mbugani',
    'Mkola',
    'Mtanila',
    'Sangambi',
  ],
  'Dodoma City': [
    'Chahwa',
    'Chamwino',
    'Chang\'ombe',
    'Chigongwe',
    'Chihanga',
    'Dom-Makulu',
    'Hazina',
    'Hombolo',
    'Ipagala',
    'Ipala',
    'Iyumbu',
    'Kikombo',
    'Kikuyu Kaskazini',
    'Kikuyu Kusini',
    'Kilimani',
    'Kiwanja cha ndege',
    'Kizota',
    'Madukani',
    'Majengo',
    'Makole',
    'Makutupora',
    'Mbabala',
    'Mbalawala',
    'Miyuji',
    'Mkonze',
    'Mnadani',
    'Mpunguzi',
    'Msalato',
    'Mtumba',
    'Nala',
    'Ngh\'ongh\'onha',
    'Ntyuka',
    'Nzuguni',
    'Tambukareli',
    'Uhuru',
    'Viwandani',
    'Zuzu',
  ],
  'Gairo': [
    'Chagongwe',
    'Chakwale',
    'Chanjale',
    'Gairo',
    'Idibo',
    'Iyogwe',
    'Kibedya',
    'Mandege',
    'Msingisi',
    'Nongwe',
    'Rubeho',
  ],
  'Geita': [
    'Bugalama',
    'Bugulula',
    'Bujula',
    'Bukoli',
    'Bukondo',
    'Bulela',
    'Bung\'wangoko',
    'Busanda',
    'Butobela',
    'Chigunga',
    'Ihanamilo',
    'Isulwabutunde',
    'Kagu',
    'Kakubilo',
    'Kalangalala',
    'Kamena',
    'Kamhanga',
    'Kasamwa',
    'Kaseme',
    'Katoma',
    'Katoro',
    'Lubanga',
    'Lwamgasa',
    'Lwezera',
    'Mtakuja',
    'Nkome',
    'Nyachiluluma',
    'Nyakagomba',
    'Nyakamwaga',
    'Nyamalimbe',
    'Nyamigota',
    'Nyanguku',
    'Nyarugusu',
    'Nzera',
    'Senga',
  ],
  'Hai': [
    'Hai Mjini',
    'KIA',
    'Machame Kaskazini',
    'Machame Kusini',
    'Machame Magharibi',
    'Machame Mashariki',
    'Machame Narumu',
    'Machame Uroki',
    'Machame Weruweru',
    'Masama Kati',
    'Masama Kusini',
    'Masama Magharibi',
    'Masama Mashariki',
    'Masama Rundugai',
  ],
  'Hanang': [
    'Balagidalalu',
    'Bassodesh',
    'Bassotu',
    'Dirma',
    'Endasak',
    'Endasiwold',
    'Ganana',
    'Gehandu',
    'Gendabi',
    'Getanuwas',
    'Gidahababieg',
    'Gisambalang',
    'Giting',
    'Hidet',
    'Hirbadaw',
    'Katesh',
    'Laghanga',
    'Lalaji',
    'Masakta',
    'Maskron',
    'Masqaroda',
    'Mogitu',
    'Nangwa',
    'Simbay',
    'Sirop',
  ],
  'Handeni': [
    'Kabuku',
    'Kabuku ndani',
    'Kang\'ata',
    'Kiva',
    'Komkonga',
    'Kwachaga',
    'Kwaluguru',
    'Kwamatuku',
    'Kwamgwe',
    'Kwamkonje',
    'Kwamsisi',
    'Kwasunga',
    'Kwedizinga',
    'Mazingara',
    'Mgambo',
    'Misima',
    'Mkata',
    'Ndolwa',
    'Segera',
    'Sindeni',
  ],
  'Handeni City': [
    'Chanika',
    'Kideleko',
    'Konje',
    'Kwamagome',
    'Kwediyamba',
    'Kwenjugo',
    'Mabanda',
    'Malezi',
    'Mdoe',
    'Mlimani',
    'Msasa',
    'Vibaoni',
  ],
  'Igunga': [
    'Bukoko',
    'Chabutwa',
    'Choma',
    'Igowero',
    'Igunga',
    'Igurubi',
    'Isakamaliwa',
    'Itumba',
    'Itunduru',
    'Kining\'inila',
    'Kinungu',
    'Mbutu',
    'Mwamashiga',
    'Mwamashimba',
    'Mwashiku',
    'Mwisi',
    'Nanga',
    'Ndembezi',
    'Ngulu',
    'Nguvumoja',
    'Nkinga',
    'Ntobo',
    'Nyandekwa',
    'Simbo',
    'Sungwizi',
    'Ziba',
  ],
  'Ikungi': [
    'Dung\'unyi',
    'Ighombwe',
    'Iglansoni',
    'Ihanja',
    'Ikungi',
    'Irisya',
    'Iseke',
    'Issuna',
    'Iyumbu',
    'Kikio',
    'Kituntu',
    'Lighwa',
    'Mang\'onyi',
    'Mgungira',
    'Minyughe',
    'Misughaa',
    'Mkiwa',
    'Mtunduru',
    'Muhintiri',
    'Mungaa',
    'Mwaru',
    'Ntuntu',
    'Puma',
    'Sepuka',
    'Siuyu',
    'Unyahati',
  ],
  'Ilala': [
    'Buguruni',
    'Chanika',
    'Gerezani',
    'Gongolamboto',
    'Ilala',
    'Jangwani',
    'Kariakoo',
    'Kimanga',
    'Kinyerezi',
    'Kipawa',
    'Kisutu',
    'Kitunda',
    'Kivukoni',
    'Kivule',
    'Kiwalani',
    'Majohe',
    'Mchafukoge',
    'Mchikichini',
    'Msongola',
    'Pugu',
    'Segerea',
    'Tabata',
    'Ukonga',
    'Upanga Magharibi',
    'Upanga Mashariki',
    'Vingunguti',
  ],
  'Ileje': [
    'Bupigu',
    'Chitete',
    'Ibaba',
    'Ikinga',
    'Isongole',
    'Itale',
    'Itumba',
    'Kafule',
    'Kalembo',
    'Lubanda',
    'Luswisi',
    'Malangali',
    'Mbebe',
    'Mlale',
    'Ndola',
    'Ngulilo',
    'Ngulugulu',
    'Sange',
  ],
  'Ilemela': [
    'Bugogwa',
    'Buswelu',
    'Ilemela',
    'Kirumba',
    'Kitangiri',
    'Nyakato',
    'Nyamanoro',
    'Pasiansi',
    'Sangabuye',
  ],
  'Iramba': [
    'Kaselya',
    'Kidaru',
    'Kinampanda',
    'Kiomboi',
    'Kisiriri',
    'Kyengege',
    'Mbelekese',
    'Mgongo',
    'Mtekente',
    'Mtoa',
    'Ndago',
    'Ndulungu',
    'Ntwike',
    'Shelui',
    'Tulya',
    'Ulemo',
    'Urughu',
  ],
  'Iringa': [
    'Idodi',
    'Ifunda',
    'Ilolo Mpya',
    'Itunundu',
    'Izazi',
    'Kalenga',
    'Kihorogota',
    'Kiwere',
    'Luhota',
    'Lumuli',
    'Lyamgungwe',
    'Maboga',
    'Maguliwa',
    'Mahuninga',
    'Malenga Makali',
    'Mgama',
    'Migoli',
    'Mlenge',
    'Mlowa',
    'Mseke',
    'Nduli',
    'Nyang\'oro',
    'Nzihi',
    'Ulanda',
    'Wasa',
  ],
  'Iringa City': [
    'Gangilonga',
    'Ilala',
    'Isakalilo',
    'Kihesa',
    'Kitanzini',
    'Kitwiru',
    'Kwakilosa',
    'Makorongoni',
    'Mivinjeni',
    'Mkwawa',
    'Mlandege',
    'Mshindo',
    'Mtwivila',
    'Mwangata',
    'Nduli',
    'Ruaha',
  ],
  'Itilima': [
    'Budalabujiga',
    'Bumera',
    'Chinamili',
    'Ikindiro',
    'Kinang\'weli',
    'Lagangabilili',
    'Lugulu',
    'Mbita',
    'Mhunze',
    'Migato',
    'Mwalushu',
    'Mwamapalala',
    'Mwamtani',
    'Mwaswale',
    'Ndolelezi',
    'Nhobora',
    'Nkoma',
    'Nkuyu',
    'Nyamalapa',
    'Sagata',
    'Sawida',
    'Zagayu',
  ],
  'Kahama': [
    'Bugarama',
    'Bukomela',
    'Bulige',
    'Bulungwa',
    'Bulyanhulu',
    'Busangi',
    'Chambo',
    'Chela',
    'Chona',
    'Idahina',
    'Igunda',
    'Igwamanoni',
    'Isaka',
    'Jana',
    'Kashishi',
    'Kinamapula',
    'Kisuke',
    'Lunguya',
    'Mapamba',
    'Mega',
    'Mpunze',
    'Mwalugulu',
    'Mwanase',
    'Ngaya',
    'Ntobo',
    'Nyankende',
    'Sabasabini',
    'Segese',
    'Shilela',
    'Ubagwe',
    'Ukune',
    'Ulewe',
    'Ulowa',
    'Ushetu',
    'Uyogo',
  ],
  'Kahama City': [
    'Busoka',
    'Isagehe',
    'Iyenze',
    'Kagongwa',
    'Kahama Mjini',
    'Kilago',
    'Kinaga',
    'Majengo',
    'Malunga',
    'Mhongolo',
    'Mhungula',
    'Mondo',
    'Mwendakulima',
    'Ngogwa',
    'Nyahanga',
    'Nyandekwa',
    'Nyasubi',
    'Nyihogo',
    'Wendele',
    'Zongomera',
  ],
  'Kakonko': [
    'Gwamumpu',
    'Kakonko',
    'Kasanda',
    'Kasunga',
    'Katanga',
    'Kiziguzigu',
    'Mugunzu',
    'Muhange',
    'Nyabibuye',
    'Nyamtukuza',
    'Rugenge',
  ],
  'Kalambo': [
    'Kasanga',
    'Katazi',
    'Katete',
    'Kilesha',
    'Kisumba',
    'Legeza Mwendo',
    'Mabwekenya',
    'Matai',
    'Mkali',
    'Mkowe',
    'Mnamba',
    'Msanzi',
    'Mwazye',
    'Mwembenkoswe',
    'Mwimbi',
    'Sopa',
    'Ulumi',
  ],
  'Kaliua': [
    'Ichemba',
    'Igagala',
    'Igombe Mkulu',
    'Igwisi',
    'Kaliua',
    'Kamsekwa',
    'Kanindo',
    'Kanoge',
    'Kashishi',
    'Kazaroho',
    'Milambo',
    'Mwongozo',
    'Sasu',
    'Seleli',
    'Silambo',
    'Ugunga',
    'Ukumbi Siganga',
    'Ushokola',
    'Usinge',
    'Uyowa',
    'Zugimlole',
  ],
  'Karagwe': [
    'Bugene',
    'Bweranyange',
    'Chanika',
    'Chonyonyo',
    'Igurwa',
    'Ihanda',
    'Ihembe',
    'Kanoni',
    'Kayanga',
    'Kibondo',
    'Kihanga',
    'Kiruruma',
    'Kituntu',
    'Ndama',
    'Nyabiyonza',
    'Nyaishozi',
    'Nyakabanga',
    'Nyakahanga',
    'Nyakakika',
    'Nyakasimbi',
    'Rugera',
    'Rugu',
  ],
  'Karatu': [
    'Baray',
    'Buger',
    'Daa',
    'Endabash',
    'Endamaghang',
    'Endamarariek',
    'Ganako',
    'Kansay',
    'Karatu',
    'Mang\'ola',
    'Mbulumbulu',
    'Oldean',
    'Qurus',
    'Rhotia',
  ],
  'Kaskazini A': [
    'Bandamaji',
    'Bwereu',
    'Chaani Kubwa',
    'Chaani Masingini',
    'Chutama',
    'Fukuchani',
    'Gamba',
    'Jongowe',
    'Kandwi',
    'Kibeni',
    'Kidombo',
    'Kidoti',
    'Kigomani',
    'Kigunda',
    'Kijini',
    'Kikobweni',
    'Kilimani',
    'Kilindi',
    'Kinyasini',
    'Kisongoni',
    'Kivunge',
    'Matemwe',
    'Mcheza Shauri',
    'Mkokotoni',
    'Mkwajuni',
    'Moga',
    'Mto wa Pwani',
    'Muwange',
    'Nungwi',
    'Pale',
    'Pitanazako',
    'Potowa',
    'Pwani Mchangani',
    'Tazari',
    'Tumbatu Gomani',
    'Uvivini',
  ],
  'Kaskazini B': [
    'Donge  Mchangani',
    'Donge Karange',
    'Donge Kipange',
    'Donge Mbiji',
    'Donge Mtambile',
    'Donge Vijibweni',
    'Fujoni',
    'Kidanzini',
    'Kilombero',
    'Kinduni',
    'Kiomba Mvua',
    'Kitope',
    'Kiwengwa',
    'Mafufuni',
    'Mahonda',
    'Makoba',
    'Mangapwani',
    'Matetema',
    'Mbaleni',
    'Mgambo',
    'Misufini',
    'Mkadini',
    'Mkataleni',
    'Mnyimbi',
    'Muwanda',
    'Njia ya Mtoni',
    'Pangeni',
    'Upenja',
    'Zingwe Zingwe',
  ],
  'Kasulu': [
    'Asante Nyerere',
    'Bugaga',
    'Buhoro',
    'Heru Shingo',
    'Kagerankanda',
    'Kigembe',
    'Kitagata',
    'Kitanga',
    'Kurugongo',
    'Kwaga',
    'Muzye',
    'Nyachenda',
    'Nyakitonto',
    'Nyamidaho',
    'Nyamnyusi',
    'Rungwe Mpya',
    'Rusesa',
    'Shunguliba',
    'Titye',
  ],
  'Kasulu City': [
    'Kasulu Mjini',
    'Kigondo',
    'Msambara',
    'Muganza',
    'Muhunga',
    'Murufiti',
    'Nyansha',
    'Nyumbigwa',
    'Ruhita',
  ],
  'Kati': [
    'Bambi',
    'Binguni',
    'Bungi',
    'Charawe',
    'Cheju',
    'Chwaka',
    'Dunga Bweni',
    'Dunga Kiembeni',
    'Ghana',
    'Jendele',
    'Jumbi',
    'Kiboje Mkwajuni',
    'Kiboje Muembeshauri',
    'Kidimni',
    'Kikungwi',
    'Koani',
    'Machui',
    'Marumbi',
    'Mchangani',
    'Mgeni Haji',
    'Michamvi',
    'Mitakawani',
    'Miwani',
    'Mpapa',
    'Ndijani Mseweni',
    'Ndijani Muembe Punda',
    'Ng\'ambwa',
    'Pagali',
    'Pongwe',
    'Tindini',
    'Tunduni',
    'Tunguu',
    'Ubago',
    'Ukongoroni',
    'Umbuji',
    'Unguja Ukuu Kaebona',
    'Unguja Ukuu Kaepwani',
    'Uroa',
    'Uzi',
    'Uzini',
  ],
  'Kibaha': [
    'Bokomnemela',
    'Dutumi',
    'Gwata',
    'Janga',
    'Kikongo',
    'Kilangalanga',
    'Kwala',
    'Magindu',
    'Mlandizi',
    'Ruvu',
    'Soga',
  ],
  'Kibaha City': [
    'Kibaha',
    'Kongowe',
    'Mailimoja',
    'Mbwawa',
    'Misugusugu',
    'Mkuza',
    'Msangani',
    'Pangani',
    'Picha ya Ndege',
    'Tumbi',
    'Visiga',
  ],
  'Kibondo': [
    'Bitare',
    'Bunyambo',
    'Busagara',
    'Busunzu',
    'Itaba',
    'Kibondo',
    'Kitahana',
    'Kizazi',
    'Kumsenga',
    'Mabamba',
    'Misezero',
    'Murungu',
    'Rugongwe',
  ],
  'Kigoma': [
    'Bitale',
    'Kagongo',
    'Kagunga',
    'Kalinzi',
    'Mahembe',
    'Matendo',
    'Mkigo',
    'Mkongoro',
    'Mungonya',
    'Mwamgongo',
    'Mwandiga',
  ],
  'Kigoma City': [
    'Bangwe',
    'Buhanda',
    'Businde',
    'Buzebazeba',
    'Gungu',
    'Kagera',
    'Kasimbu',
    'Kasingirima',
    'Katubuka',
    'Kibirizi',
    'Kigoma',
    'Kipampa',
    'Kitongoni',
    'Machinjioni',
    'Majengo',
    'Mwanga Kaskazini',
    'Mwanga Kusini',
    'Rubuga',
    'Rusimbi',
  ],
  'Kilindi': [
    'Jaila',
    'Kibirashi',
    'Kikunde',
    'Kilindi',
    'Kilwa',
    'Kimbe',
    'Kisangasa',
    'Kwediboma',
    'Kwekivu',
    'Lwande',
    'Mabalanga',
    'Masagalu',
    'Mkindi',
    'Msanja',
    'Mvungwe',
    'Negero',
    'Pagwi',
    'Saunyi',
    'Songe',
    'Tunguli',
  ],
  'Kilolo': [
    'Boma la Ng\'ombe',
    'Dabaga',
    'Ibumu',
    'Idete',
    'Ihimbo',
    'Ilula',
    'Image',
    'Irole',
    'Kimala',
    'Lugalo',
    'Mahenge',
    'Masisiwe',
    'Mlafu',
    'Mtitu',
    'Ng\'ang\'ange',
    'Ng\'uruhe',
    'Nyalumbu',
    'Ruaha Mbuyuni',
    'Udekwa',
    'Uhambingeto',
    'Ukumbi',
    'Ukwega',
  ],
  'Kilombero': [
    'Chisano',
    'Chita',
    'Idete',
    'Ifakara',
    'Kibaoni',
    'Kiberege',
    'Kidatu',
    'Kisawasawa',
    'Lumemo',
    'Mang\'ula',
    'Masagati',
    'Mbingu',
    'Mchombe',
    'Mkula',
    'Mlimba',
    'Mofu',
    'Sanje',
    'Uchindile',
    'Utengule',
  ],
  'Kilosa': [
    'Berega',
    'Chanzulu',
    'Dumila',
    'Kasiki',
    'Kidete',
    'Kidodi',
    'Kilangali',
    'Kimamba \' B \'',
    'Kimamba \'A\'',
    'Kisanga',
    'Kitete',
    'Lumbiji',
    'Lumuma',
    'Mabula',
    'Mabwerebwere',
    'Madoto',
    'Magole',
    'Magomeni',
    'Magubike',
    'Maguha',
    'Malolo',
    'Mamboya',
    'Masanze',
    'Mbumi',
    'Mikumi',
    'Mkwatani',
    'Msowero',
    'Ruaha',
    'Rudewa',
    'Ruhembe',
    'Tindiga',
    'Ulaya',
    'Uleling\'ombe',
    'Vidunda',
    'Zombo',
  ],
  'Kilwa': [
    'Chumo',
    'Kandawale',
    'Kibata',
    'Kikole',
    'Kinjumbi',
    'Kipatimu',
    'Kirnjernje',
    'Kivinjesingino',
    'Lihimalyao',
    'Likawage',
    'Mandawa',
    'Masoko',
    'Miguruwe',
    'Mingumbi',
    'Miteja',
    'Mitole',
    'Nanjirinji',
    'Njinjo',
    'Pande',
    'Songosongo',
    'Tingi',
  ],
  'Kinondoni': [
    'Bunju',
    'Goba',
    'Hananasifu',
    'Kawe',
    'Kibamba',
    'Kigogo',
    'Kijitonyama',
    'Kimara',
    'Kinondoni',
    'Kunduchi',
    'Kwembe',
    'Mabibo',
    'Mabwepande',
    'Magomeni',
    'Makongo',
    'Makuburi',
    'Makumbusho',
    'Makurumla',
    'Manzese',
    'Mbezi',
    'Mbezi Juu',
    'Mburahati',
    'Mbweni',
    'Mikocheni',
    'Msasani',
    'Msigani',
    'Mwananyamala',
    'Mzimuni',
    'Ndugumbi',
    'Saranga',
    'Sinza',
    'Tandale',
    'Ubungo',
    'Wazo',
  ],
  'Kisarawe': [
    'Cholesamvula',
    'Kibuta',
    'Kiluvya',
    'Kisarawe',
    'Kurui',
    'Mafizi',
    'Maneromango',
    'Marui',
    'Marumbo',
    'Masaki',
    'Msanga',
    'Msimbu',
    'Mzenga',
    'Vihingo',
    'Vikumbulu',
  ],
  'Kishapu': [
    'Bubiki',
    'Bunambiyu',
    'Itilima',
    'Kiloleli',
    'Kishapu',
    'Lagana',
    'Masanga',
    'Mondo',
    'Mwadui Lohumbo',
    'Mwakipoya',
    'Mwamalasa',
    'Mwamashele',
    'Ngofila',
    'Seke Bugoro',
    'Shagihilu',
    'Somagedi',
    'Songwa',
    'Talaga',
    'Uchunga',
    'Ukenyenge',
  ],
  'Kiteto': [
    'Bwagamoyo',
    'Chapakazi',
    'Dongo',
    'Dosidosi',
    'Engusero',
    'Kibaya',
    'Kijungu',
    'Lengatei',
    'Loolera',
    'Magungu',
    'Makame',
    'Matui',
    'Namelock',
    'Ndedo',
    'Njoro',
    'Olboroti',
    'Partimbo',
    'Songambele',
    'Sunya',
  ],
  'Kondoa': [
    'Bereko',
    'Bolisa',
    'Bumbuta',
    'Busi',
    'Changaa',
    'Chemchem',
    'Haubi',
    'Hondo mairo',
    'Itaswi',
    'Itololo',
    'Kalamba',
    'Kikilo',
    'Kikore',
    'Kilimani',
    'Kingale',
    'Kinyasi',
    'Kisese',
    'Kolo',
    'Kondoa mjini',
    'Kwadelo',
    'Masange',
    'Mnenia',
    'Pahi',
    'Salanka',
    'Serya',
    'Soera',
    'Suruke',
    'Thawi',
  ],
  'Kongwa': [
    'Chamkoroma',
    'Chitego',
    'Chiwe',
    'Hogoro',
    'Iduo',
    'Kibaigwa',
    'Kongwa',
    'Lenjulu',
    'Makawa',
    'Matongoro',
    'Mkoka',
    'Mlali',
    'Mtanana',
    'Nghumbi',
    'Ngomai',
    'Njoge',
    'Pandambili',
    'Sagara',
    'Sejeli',
    'Songambele',
    'Ugogoni',
    'Zoissa',
  ],
  'Korogwe': [
    'Bungu',
    'Chekelei',
    'Dindira',
    'Kerenge',
    'Kizara',
    'Kwagunda',
    'Kwashemshi',
    'Lutindi',
    'Magamba Kwalukonge',
    'Magoma',
    'Makuyuni',
    'Mashewa',
    'Mazinde',
    'Mkalamo',
    'Mkomazi',
    'Mnyuzi',
    'Mombo',
    'Mpale',
    'Mswaha',
    'Vugiri',
  ],
  'Korogwe City': [
    'Kilole',
    'Kwamndolwa',
    'Kwamsisi',
    'Magunga',
    'Manundu',
    'Mtonga',
    'Ngombezi',
    'Old Korogwe',
  ],
  'Kusini': [
    'Bwejuu',
    'Dongwe',
    'Jambiani Kibigija',
    'Jambiani Kikadini',
    'Kajengwa',
    'Kibuteni',
    'Kijini',
    'Kiongoni',
    'Kitogani',
    'Kizimkazi Dimbani',
    'Kizimkazi Mkunguni',
    'Mtende',
    'Muungoni',
    'Muyuni A',
    'Muyuni B',
    'Muyuni C',
    'Mzuri',
    'Nganani',
    'Paje',
    'Pete',
    'Tasani',
  ],
  'Kwimba': [
    'Bugando',
    'Bungulwa',
    'Bupamwa',
    'Fukalo',
    'Hungumalwa',
    'Igongwa',
    'Ilula',
    'Iseni',
    'Kikubiji',
    'Lyoma',
    'Maligisu',
    'Malya',
    'Mantare',
    'Mhande',
    'Mwabomba',
    'Mwagi',
    'Mwakilambiti',
    'Mwamala',
    'Mwandu',
    'Mwang\'halanga',
    'Mwankulwe',
    'Ng\'hundi',
    'Ngudu',
    'Ngulla',
    'Nkalalo',
    'Nyambiti',
    'Nyamilama',
    'Shilembo',
    'Sumve',
    'Walla',
  ],
  'Kyela': [
    'Bujonde',
    'Busale',
    'Ikama',
    'Ikimba',
    'Ikolo',
    'Ipande',
    'Ipinda',
    'Itope',
    'Kajunjumele',
    'Katumbasongwe',
    'Kyela',
    'Lusungo',
    'Makwale',
    'Matema',
    'Muungano',
    'Mwaya',
    'Ndobo',
    'Ngana',
    'Ngonga',
    'Talatala',
  ],
  'Kyerwa': [
    'Bugomora',
    'Businde',
    'Isingiro',
    'Kaisho',
    'Kamuli',
    'Kibale',
    'Kibingo',
    'Kikukuru',
    'Kimuli',
    'Kyerwa',
    'Mabira',
    'Murongo',
    'Nkwenda',
    'Nyakatuntu',
    'Rukuraijo',
    'Rutunguru',
    'Rwabwere',
    'Songambele',
  ],
  'Lindi': [
    'Chiponda',
    'Kilangala',
    'Kilolambwani',
    'Kitomanga',
    'Kiwalala',
    'Kiwawa',
    'Longa',
    'Majengo',
    'Mandwanga',
    'Matimba',
    'Mchinga',
    'Milola',
    'Mipingo',
    'Mnara',
    'Mnolela',
    'Mtama',
    'Mtua',
    'Mtumbya',
    'Nachunyu',
    'Nahukahuka',
    'Namangale',
    'Namupa',
    'Nangaru',
    'Navanga',
    'Nyangamara',
    'Nyangao',
    'Nyengedi',
    'Pangatena',
    'Rutamba',
    'Sudi',
  ],
  'Lindi City': [
    'Chikonji',
    'Jamhuri',
    'Makonde',
    'Matopeni',
    'Mbanja',
    'Mikumbi',
    'Mingoyo',
    'Mitandi',
    'Msinjahili',
    'Mtanda',
    'Mwenge',
    'Nachingwea',
    'Ndoro',
    'Ng\'apa',
    'Rahaleo',
    'Rasbura',
    'Tandangongoro',
    'Wailes',
  ],
  'Liwale': [
    'Barikiwa',
    'Kiangara',
    'Kibutuka',
    'Kichonda',
    'Kimambi',
    'Likongowele',
    'Lilombe',
    'Liwale \'B\'',
    'Liwale Mjini',
    'Makata',
    'Mangirikiti',
    'Mbaya',
    'Mihumo',
    'Mirui',
    'Mkutano',
    'Mlembwe',
    'Mpigamiti',
    'Nangando',
    'Nangano',
    'Ngongowele',
  ],
  'Longido': [
    'Eleng\'ata Dapash',
    'Engarenaibor',
    'Engikaret',
    'Gelai lumbwa',
    'Gelai Meirugoi',
    'Ilorienito',
    'Kamwanga',
    'Kimokouwa',
    'Kitumbeine',
    'Longido',
    'Matale',
    'Mundarara',
    'Namanga',
    'Olmolog',
    'Orbomba',
    'Tingatinga',
  ],
  'Ludewa': [
    'Ibumi',
    'Iwela',
    'Kilondo',
    'Lifuma',
    'Luana',
    'Ludende',
    'Ludewa',
    'Lugarawa',
    'Luilo',
    'Lumbila',
    'Lupanga',
    'Lupingu',
    'Madilu',
    'Madope',
    'Makonde',
    'Manda',
    'Masasi',
    'Mavanga',
    'Mawengi',
    'Milo',
    'Mkongobaki',
    'Mlangali',
    'Mundindi',
    'Nkomang\'ombe',
    'Ruhuhu',
  ],
  'Lushoto': [
    'Baga',
    'Bumbuli',
    'Dule "B"',
    'Dule "M"',
    'Funta',
    'Gare',
    'Hemtoye',
    'Kilole',
    'Kwai',
    'Kwekanga',
    'Kwemashai',
    'Kwemshasha',
    'Lukozi',
    'Lunguza',
    'Lushoto',
    'Maheza ngulu',
    'Makanya',
    'Malibwi',
    'Malindi',
    'Mamba',
    'Manolo',
    'Mayo',
    'Mbaramo',
    'Mbuzii',
    'Mgwashi',
    'Milingano',
    'Mlalo',
    'Mlola',
    'Mnazi',
    'Mng\'aro',
    'Mponde',
    'Mtae',
    'Mwangoi',
    'Ngulwi',
    'Ngwelo',
    'Nkongoi',
    'Rangwi',
    'Shume',
    'Soni',
    'Sunga',
    'Tamota',
    'Ubiri',
    'Usambara',
    'Vuga',
  ],
  'Mafia': [
    'Baleni',
    'Jibondo',
    'Kanga',
    'Kiegeani',
    'Kilindoni',
    'Kirongwe',
    'Miburani',
    'Ndagoni',
  ],
  'Magharibi': [
    'Bububu',
    'Bumbwisudi',
    'Bweleo',
    'Chuini',
    'Chukwani',
    'Dimani',
    'Dole',
    'Fumba',
    'Fuoni Kibondeni',
    'Fuoni Kijito Upele',
    'Kama',
    'Kianga',
    'Kibweni',
    'Kiembesamaki',
    'Kihinani',
    'Kinuni',
    'Kisauni',
    'Kizimbani',
    'Kombeni',
    'Magogoni',
    'Maungani',
    'Mbuzini',
    'Melinne',
    'Mfenesini',
    'Mombasa',
    'Mtoni',
    'Mtoni Kidatu',
    'Mtopepo',
    'Mtufaani',
    'Mwakaje',
    'Mwanakwerekwe',
    'Mwanyanya',
    'Mwera',
    'Nyamanzi',
    'Pangawe',
    'Shakani',
    'Sharifumsa',
    'Tomondo',
    'Welezo',
  ],
  'Magu': [
    'Bujashi',
    'Bukandwe',
    'Jinjimili',
    'Kahangara',
    'Kisesa',
    'Kitongo Sim',
    'Kongolo',
    'Lubugu',
    'Lutale',
    'Magu Mjini',
    'Mwamabanza',
    'Mwamanga',
    'Ng\'haya',
    'Nkungulu',
    'Nyanguge',
    'Nyigogo',
    'Shishani',
    'Sukuma',
  ],
  'Makambako': [
    'Kitandililo',
    'Lyamkena',
    'Mahongole',
    'Mjimwema',
    'Mlowa',
    'Mwembetogwa',
    'Ubena',
    'Utengule',
  ],
  'Makete': [
    'Bulongwa',
    'Ikuwo',
    'Iniho',
    'Ipelele',
    'Ipepo',
    'Isapulano',
    'Itundu',
    'Iwawa',
    'Kigala',
    'Kigulu',
    'Kipagalo',
    'Kitulo',
    'Lupalilo',
    'Lupila',
    'Luwumbu',
    'Mang\'oto',
    'Matamba',
    'Mbalatse',
    'Mfumbi',
    'Mlondwe',
    'Tandala',
    'Ukwama',
  ],
  'Manyoni': [
    'Aghondi',
    'Chikola',
    'Chikuyu',
    'Heka',
    'Idodyandole',
    'Ipande',
    'Isseke',
    'Itigi Majengo',
    'Itigi Mjini',
    'Kintinku',
    'Kitaraka',
    'Majiri',
    'Makanda',
    'Makuru',
    'Makutupora',
    'Manyoni',
    'Mgandu',
    'Mitundu',
    'Mkwese',
    'Muhalala',
    'Mvumi',
    'Mwamagembe',
    'Nkonko',
    'Rungwa',
    'Sanjaranda',
    'Sanza',
    'Saranda',
    'Sasajila',
    'Sasilo',
    'Solya',
  ],
  'Masasi': [
    'Chigugu',
    'Chikolopola',
    'Chiungutwa',
    'Chiwale',
    'Chiwata',
    'Lipumburu',
    'Lukuledi',
    'Lulindi',
    'Mbuyuni',
    'Mchauru',
    'Mkululu',
    'Mkundi',
    'Mlingula',
    'Mnavira',
    'Mpanyani',
    'Mwena',
    'Namajani',
    'Namalenga',
    'Namatutwe',
    'Nanganga',
    'Nanjota',
    'Sindano',
  ],
  'Masasi City': [
    'Jida',
    'Marika',
    'Migongo',
    'Mkomaindo',
    'Mkuti',
    'Mpindimbi',
    'Mtandi',
    'Mwenge',
    'Mwenge Mtapika',
    'Nyasa',
    'Sululu',
    'Temeke',
  ],
  'Maswa': [
    'Badi',
    'Binza',
    'Buchambi',
    'Budekwa',
    'Busilili',
    'Dakama',
    'Ipililo',
    'Isanga',
    'Kadoto',
    'Kulimi',
    'Lalago',
    'Malampaka',
    'Masela',
    'Mpindo',
    'Mwamanenge',
    'Mwamashimba',
    'Mwang\'honoli',
    'Nguliguli',
    'Ng\'wigwa',
    'Nyabubinza',
    'Nyalikungu',
    'Senani',
    'Sengwa',
    'Shishiyu',
    'Sukuma',
    'Zanzui',
  ],
  'Mbarali': [
    'Chimala',
    'Igava',
    'Igurusi',
    'Ihahi',
    'Imalilosongwe',
    'Ipwani',
    'Itambaleo',
    'Kongolo',
    'Lugelele',
    'Luhanga',
    'Madibira',
    'Mahongole',
    'Mapogoro',
    'Mawindi',
    'Miyombweni',
    'Mwatenga',
    'Ruiwa',
    'Rujewa',
    'Ubaruku',
    'Utengule Usangu',
  ],
  'Mbeya': [
    'Bonde la Songwe',
    'Igale',
    'Igoma',
    'Ihango',
    'Ijombe',
    'Ikukwa',
    'Ilembo',
    'Ilungu',
    'Inyala',
    'Isuto',
    'Itawa',
    'Itewe',
    'Iwiji',
    'Iwindi',
    'Iyunga Mapinduzi',
    'Lwanjiro',
    'Maendeleo',
    'Masoko',
    'Mshewe',
    'Nsalala',
    'Santilya',
    'Swaya',
    'Tembela',
    'Ulenje',
    'Utengule Usongwe',
  ],
  'Mbeya City': [
    'Forest',
    'Ghana',
    'Iduda',
    'Iganjo',
    'Iganzo',
    'Igawilo',
    'Ilemi',
    'Ilomba',
    'Isanga',
    'Isyesye',
    'Itagano',
    'Itende',
    'Itezi',
    'Itiji',
    'Iwambi',
    'Iyela',
    'Iyunga',
    'Iziwa',
    'Kalobe',
    'Maanga',
    'Mabatini',
    'Maendeleo',
    'Majengo',
    'Mbalizi RD',
    'Mwakibete',
    'Mwansekwa',
    'Mwasanga',
    'Nonde',
    'Nsalaga',
    'Nsoho',
    'Nzovwe',
    'Ruanda',
    'Sinde',
    'Sisimba',
    'Tembela',
    'Uyole',
  ],
  'Mbinga': [
    'Kambarage',
    'Kigonsera',
    'Kihangi Mahuka',
    'Kihungu',
    'Kikolo',
    'Kilimani',
    'Kipapa',
    'Kipololo',
    'Kitanda',
    'Kitumbalomo',
    'Kitura',
    'Langiro',
    'Linda',
    'Litembo',
    'Litumbandyosi',
    'Luwaita',
    'Maguu',
    'Mapera',
    'Matiri',
    'Mbangamao',
    'Mbinga Mjini',
    'Mbuji',
    'Mikalanga',
    'Mkako',
    'Mkumbi',
    'Mpapa',
    'Mpepai',
    'Myangayanga',
    'Namswea',
    'Ngima',
    'Nyoni',
    'Ruanda',
    'Ukata',
    'Utiri',
  ],
  'Mbogwe': [
    'Bukandwe',
    'Ikobe',
    'Ikunguigazi',
    'Ilolangulu',
    'Iponya',
    'Isebya',
    'Lugunga',
    'Lulembela',
    'Masumbwe',
    'Mbogwe',
    'Mgemo',
    'Nanda',
    'Ng\'homolwa',
    'Nyakafulu',
    'Nyasato',
    'Ushirika',
  ],
  'Mbozi': [
    'Bara',
    'Halungu',
    'Igamba',
    'Ihanda',
    'Ipunga',
    'Isandula',
    'Isansa',
    'Itaka',
    'Iyula',
    'Mlangali',
    'Mlowo',
    'Msia',
    'Myovizi',
    'Nambinzo',
    'Nanyala',
    'Nyambili',
    'Ruanda',
    'Vwawa',
  ],
  'Mbulu': [
    'Ayamaami',
    'Ayamohe',
    'Bargish',
    'Bashay',
    'Daudi',
    'Dinamu',
    'Dongobesh',
    'Endagikot',
    'Endamilay',
    'Eshkesh',
    'Gehandu',
    'Geterer',
    'Gidihim',
    'Gunyoda',
    'Hayderer',
    'Haydom',
    'Imboru',
    'Kainam',
    'Maghang',
    'Marang',
    'Maretadu',
    'Masieda',
    'Masqaroda',
    'Murray',
    'Nahasey',
    'Nambisi',
    'Sanu Baray',
    'Tlawi',
    'Tumati',
    'Uhuru',
    'Yaeda Ampa',
    'Yaeda Chini',
  ],
  'Meatu': [
    'Bukundi',
    'Imalaseko',
    'Itinje',
    'Kimali',
    'Kisesa',
    'Lingeka',
    'Lubiga',
    'Mwabuma',
    'Mwabusalu',
    'Mwabuzo',
    'Mwakisandu',
    'Mwamalole',
    'Mwamanimba',
    'Mwamanongu',
    'Mwamishali',
    'Mwandoya',
    'Mwangundo',
    'Mwanhuzi',
    'Mwanjolo',
    'Mwanyahina',
    'Mwasengela',
    'Nghoboko',
    'Nkoma',
    'Sakasaka',
    'Tindabuligi',
  ],
  'Meru': [
    'Akheri',
    'Kikatiti',
    'Kikwe',
    'King\'ori',
    'Leguruki',
    'Maji ya chai',
    'Makiba',
    'Maroroni',
    'Mbuguni',
    'Ngarenanyuki',
    'Nkoanrua',
    'Nkoaranga',
    'Nkoarisambu',
    'Poli',
    'Seela Sing\'isi',
    'Songoro',
    'Usariver',
  ],
  'Micheweni': [
    'Chimba',
    'Finya',
    'Kifundi',
    'Kinowe',
    'Kinyasini',
    'Kiuyu Mbuyuni',
    'Konde',
    'Majenzi',
    'Makangale',
    'Maziwa Ng\'ombe',
    'Mgogoni',
    'Micheweni',
    'Mihogoni',
    'Mjini Wingwi',
    'Mlindo',
    'Msuka Magharibi',
    'Msuka Mashariki',
    'Mtemani',
    'Shumba Mjini',
    'Shumba Viamboni',
    'Sizini',
    'Tondooni',
    'Tumbe Magharibi',
    'Tumbe Mashariki',
    'Wingwi Mapofu',
    'Wingwi Mjananza',
    'Wingwi Njuguni',
  ],
  'Missenyi': [
    'Bugandika',
    'Bugorora',
    'Buyango',
    'Bwanjai',
    'Gera',
    'Ishozi',
    'Ishunju',
    'Kakunyu',
    'Kanyigo',
    'Kashenye',
    'Kassambya',
    'Kilimilil',
    'Kitobo',
    'Kyaka',
    'Mabale',
    'Minziro',
    'Mushasha',
    'Mutukula',
    'Nsunga',
    'Ruzinga',
  ],
  'Misungwi': [
    'Buhingo',
    'Bulemeji',
    'Busongo',
    'Fella',
    'Gulumungu',
    'Idetemya',
    'Igokelo',
    'Ilalambogo',
    'Ilujamate',
    'Isesa',
    'Kanyelele',
    'Kasololo',
    'Kijima',
    'Koromije',
    'Lubili',
    'Mabuki',
    'Mamaye',
    'Masasi',
    'Mbarika',
    'Misungwi',
    'Mondo',
    'Mwaniko',
    'Nhundulu',
    'Shilalo',
    'Sumbugu',
    'Ukiriguru',
    'Usagara',
  ],
  'Mjini': [
    'Amani',
    'Chumbuni',
    'Gulioni',
    'Jang\'ombe',
    'Karakana',
    'Kidongo Chekundu',
    'Kikwajuni Bondeni',
    'Kikwajuni Juu',
    'Kilimahewa Bondeni',
    'Kilimahewa Juu',
    'Kilimani',
    'Kiponda',
    'Kisima Majongoo',
    'Kisiwandui',
    'Kwa Wazee',
    'Kwaalimsha',
    'Kwaalinatu',
    'Kwahani',
    'Kwamtipura',
    'Magomeni',
    'Makadara',
    'Malindi',
    'Matarumbeta',
    'Mchangani',
    'Meya',
    'Miembeni',
    'Migombani',
    'Mikunguni',
    'Mkele',
    'Mkunazini',
    'Mlandege',
    'Mpendae',
    'Muembeshauri',
    'Muembetanga',
    'Muungano',
    'Mwembe Makumbi',
    'Mwembeladu',
    'Nyerere',
    'Rahaleo',
    'Sebleni',
    'Shangani',
    'Shaurimoyo',
    'Sogea',
    'Urusi',
    'Vikokotoni',
  ],
  'Mkalama': [
    'Gumanga',
    'Ibaga',
    'Iguguno',
    'Ilunda',
    'Kikhonda',
    'Kinyangiri',
    'Matongo',
    'Miganga',
    'Mpambala',
    'Msingi',
    'Mwanga',
    'Mwangeza',
    'Nduguti',
    'Nkinto',
  ],
  'Mkinga': [
    'Boma',
    'Bosha',
    'Bwiti',
    'Daluni',
    'Doda',
    'Duga',
    'Gombero',
    'Kigongoi',
    'Kwale',
    'Manza',
    'Mapatano',
    'Maramba',
    'Mayomboni',
    'Mhinduro',
    'Mkinga',
    'Mnyenzani',
    'Moa',
    'Mtimbwani',
    'Mwakijembe',
    'Parungu Kasera',
    'Sigaya',
  ],
  'Mkoani': [
    'Chambani',
    'Changaweni',
    'Chokocho',
    'Chumbageni',
    'Jombwe',
    'Kangani',
    'Kendwa',
    'Kengeja',
    'Kisiwa Panza',
    'Kiwani',
    'Kuukuu',
    'Makombeni',
    'Makoongwe',
    'Mbuguani',
    'Mbuyuni',
    'Mgagadu',
    'Michenzani',
    'Minazini',
    'Mizingani',
    'Mjimbini',
    'Mkanyageni',
    'Mkungu',
    'Mtambile',
    'Mtangani',
    'Muambe',
    'Ng\'ombeni',
    'Ngwachani',
    'Shamiani',
    'Shidi',
    'Stahabu',
    'Ukutini',
    'Uweleni',
    'Wambaa',
  ],
  'Mkuranga': [
    'Bupu',
    'Kimanzichana',
    'Kiparang\'anda',
    'Kisiju',
    'Kitomondo',
    'Lukanga',
    'Magawa',
    'Mbezi',
    'Mkamba',
    'Mkuranga',
    'Mwarusembe',
    'Njia nne',
    'Nyamato',
    'Panzuo',
    'Shungubweni',
    'Tambani',
    'Vianzi',
    'Vikindu',
  ],
  'Mlele': [
    'Ikuba',
    'Ilela',
    'Ilunde',
    'Inyonga',
    'Itenka',
    'Kapalala',
    'Kasansa',
    'Kasokola',
    'Kibaoni',
    'Litapunga',
    'Machimboni',
    'Magamba',
    'Majimoto',
    'Mamba',
    'Mbede',
    'Mtapenda',
    'Mwamapuli',
    'Nsenkwa',
    'Nsimbo',
    'Sitalike',
    'Ugala',
    'Urwira',
    'Usevya',
    'Utende',
  ],
  'Momba': [
    'Chilulumo',
    'Chitete',
    'Chiwezi',
    'Ivuna',
    'Kamsamba',
    'Kapele',
    'Mkulwe',
    'Mpapa',
    'Msangano',
    'Myunga',
    'Ndalembo',
    'Nkangamo',
    'Nzoka',
  ],
  'Monduli': [
    'Engaruka',
    'Engutoto',
    'Esilalei',
    'Lepurko',
    'Lolkisale',
    'Majengo',
    'Makuyuni',
    'Meserani',
    'Moita',
    'Monduli juu',
    'Monduli Mjini',
    'Mswakini',
    'Mto wa Mbu',
    'Selela',
    'Sepeko',
  ],
  'Morogoro': [
    'Bungu',
    'Bwaki la Chini',
    'Bwakila Juu',
    'Gwata',
    'Kasanga',
    'Kibogwa',
    'Kibungo Juu',
    'Kidugalo',
    'Kinole',
    'Kiroka',
    'Kisaki',
    'Kisemu',
    'Kolero',
    'Konde',
    'Lundi',
    'Matuli',
    'Mikese',
    'Mkambarani',
    'Mkulazi',
    'Mkuyuni',
    'Mngazi',
    'Mtombozi',
    'Mvuha',
    'Ngerengere',
    'Selembala',
    'Singisa',
    'Tawa',
    'Tegetero',
    'Tununguo',
  ],
  'Morogoro City': [
    'Bigwa',
    'Boma',
    'Kichangani',
    'Kihonda',
    'Kilakala',
    'Kingo',
    'Kingolwira',
    'Kiwanja Cha Ndege',
    'Mafiga',
    'Mazimbu',
    'Mbuyuni',
    'Mji Mkuu',
    'Mji Mpya',
    'Mlimani',
    'Mwembesongo',
    'Mzinga',
    'Sabasaba',
    'Sultan Area',
    'Uwanja wa Taifa',
  ],
  'Moshi': [
    'Arusha Chini',
    'Kahe',
    'Kahe Mashariki',
    'Kibosho Kati',
    'Kibosho Magharibi',
    'Kibosho Mashariki',
    'Kilema Kaskazini',
    'Kilema Kati',
    'Kilema Kusini',
    'Kimochi',
    'Kindi',
    'Kirima',
    'KiruaVunjo Kusini',
    'KiruaVunjo Magharibi',
    'KiruaVunjo Mashariki',
    'Mabogini',
    'Makuyuni',
    'Mamba Kaskazini',
    'Mamba Kusini',
    'Marangu Magharibi',
    'Marangu Mashariki',
    'Mbokomu',
    'Mwika Kusini',
    'MwikaKaskazini',
    'Okaoni',
    'Old Moshi Magharibi',
    'Old Moshi Mashariki',
    'Uru Kaskazini',
    'Uru Kusini',
    'Uru Mashariki',
    'Uru Shimbwe',
  ],
  'Moshi City': [
    'Boma Mbuzi',
    'Bondeni',
    'Kaloleni',
    'Karanga',
    'Kiboriloni',
    'Kilimanjaro',
    'Kiusa',
    'Korongoni',
    'Longuo B',
    'Majengo',
    'Mawenzi',
    'Mfumuni',
    'Miembeni',
    'Mji Mpya',
    'Msaranga',
    'Ng\'ambo',
    'Njoro',
    'Pasua',
    'Rau',
    'Shirimatunda',
    'Soweto',
  ],
  'Mpanda': [
    'Ikola',
    'Kabungu',
    'Kapalamsenga',
    'Karema',
    'Katuma',
    'Mishamo',
    'Mpanda Ndogo',
    'Mwese',
    'Sibwesa',
  ],
  'Mpwapwa': [
    'Berege',
    'Chipogoro',
    'Chitemo',
    'Chunyu',
    'Galigali',
    'Godegode',
    'Gulwe',
    'Ipera',
    'Iwondo',
    'Kibakwe',
    'Kimagai',
    'Kingiti',
    'Lufu',
    'Luhundwa',
    'Lumuma',
    'Lupeta',
    'Malolo',
    'Massa',
    'Matomondo',
    'Mazae',
    'Mbuga',
    'Mima',
    'Mlunduzi',
    'Mpwapwa',
    'Mtera',
    'Nghambi',
    'Pwaga',
    'Rudi',
    'Vingh\'awe',
    'Wotta',
  ],
  'Mtwara': [
    'Chawi',
    'Dihimba',
    'Kiromba',
    'Kitaya',
    'Kitere',
    'Kiyanga',
    'Libobe',
    'Madimba',
    'Mahurunga',
    'Mayanga',
    'Mbawala',
    'Mbembaleo',
    'Milango Minne',
    'Mnima',
    'Mpapura',
    'Msanga Mkuu',
    'Mtimbwilimbwi',
    'Mtiniko',
    'Muungano',
    'Namtumbuka',
    'Nanguruwe',
    'Nanyamba',
    'Naumbu',
    'Ndumbwe',
    'Nitekela',
    'Njengwa',
    'Tangazo',
    'Ziwani',
  ],
  'Mtwara City': [
    'Chikongola',
    'Chuno',
    'Jangwani',
    'Kisungule',
    'Likombe',
    'Magengeni',
    'Majengo',
    'Mitengo',
    'Mtonya',
    'Naliendele',
    'Rahaleo',
    'Railway',
    'Shangani',
    'Ufukoni',
    'Vigaeni',
  ],
  'Mufindi': [
    'Bumilayinga',
    'Idunda',
    'Ifwagi',
    'Igombavanu',
    'Igowole',
    'Ihalimba',
    'Ihanu',
    'Ihowanza',
    'Ikweha',
    'Isalavanu',
    'Itandula',
    'Kasanga',
    'Kibengu',
    'Kiyowela',
    'Luhanga',
    'Makungu',
    'Malangali',
    'Mapanda',
    'Mbalamaziwa',
    'Mdabulo',
    'Mninga',
    'Mpanga',
    'Mtambula',
    'Mtwango',
    'Nyololo',
    'Rungemba',
    'Sadani',
  ],
  'Muheza': [
    'Amani',
    'Bwembwera',
    'Genge',
    'Kicheba',
    'Kigombe',
    'Kilulu',
    'Kisiwani',
    'Kwafungo',
    'Kwakifua',
    'Kwemkabala',
    'Lusanga',
    'Magila',
    'Magoroto',
    'Majengo',
    'Masuguru',
    'Mbaramo',
    'Mbomole',
    'Mhamba',
    'Misalai',
    'Misozwe',
    'Mkuzi',
    'Mlingano',
    'Mpapayu',
    'Mtindiro',
    'Ngomeni',
    'Nkumba',
    'Pande Darajani',
    'Potwe',
    'Songa',
    'Tanganyika',
    'Tingeni',
    'Tongwe',
    'Zirai',
  ],
  'Muleba': [
    'Biirabo',
    'Bisheke',
    'Buganguzi',
    'Buhangaza',
    'Bulyakashaju',
    'Bumbire',
    'Bureza',
    'Burungura',
    'Goziba',
    'Gwanseli',
    'Ibuga',
    'Ijumbi',
    'Ikondo',
    'Ikuza',
    'Izigo',
    'Kabirizi',
    'Kagoma',
    'Kamachumu',
    'Karambi',
    'Kasharunga',
    'Kashasha',
    'Katoke',
    'Kerebe',
    'Kibanga',
    'Kikuku',
    'Kimwani',
    'Kishanda',
    'Kyebitembe',
    'Mafumbo',
    'Magata (Karutanga)',
    'Mayondwe',
    'Mazinga',
    'Mubunda',
    'Muhutwe',
    'Muleba',
    'Mushabago',
    'Ngenge',
    'Nshamba',
    'Nyakabango',
    'Nyakatanga',
    'Ruhanga',
    'Rulanda',
    'Rutoro',
  ],
  'Musoma': [
    'Bugwema',
    'Bukima',
    'Bukumi',
    'Bulinga',
    'Busambara',
    'Bwasi',
    'Kiriba',
    'Makojo',
    'Mugango',
    'Murangi',
    'Nyambono',
    'Nyamrandirira',
    'Suguti',
    'Tegeruka',
  ],
  'Musoma City': [
    'Buhare',
    'Bweri',
    'Iringo',
    'Kamunyonge',
    'Kigera',
    'Kitaji',
    'Makoko',
    'Mukendo',
    'Mwigobero',
    'Mwisenge',
    'Nyakato',
    'Nyamatare',
    'Nyasho',
  ],
  'Mvomero': [
    'Bunduki',
    'Diongoya',
    'Doma',
    'Hembeti',
    'Kanga',
    'Kibati',
    'Kikeo',
    'Langali',
    'Maskati',
    'Melela',
    'Mhonda',
    'Mlali',
    'Mtibwa',
    'Mvomero',
    'Mzumbe',
    'Sungaji',
    'Tchenzema',
  ],
  'Mwanga': [
    'Chomvu',
    'Jipe',
    'Kifula',
    'Kighare',
    'Kigoningoni',
    'Kileo',
    'Kilomeni',
    'Kirongwe',
    'Kirya',
    'Kivisini',
    'Kwakoa',
    'Lang\'ata',
    'Lembeni',
    'Mgagao',
    'Msangeni',
    'Mwanga',
    'Mwaniko',
    'Ngujini',
    'Shighatini',
    'Toloha',
  ],
  'Nachingwea': [
    'Chiola',
    'Kiegei',
    'Kilima Rondo',
    'Kilimanihewa',
    'Kipara Mnero',
    'Lionja',
    'Marambo',
    'Matekwe',
    'Mbondo',
    'Minero Miembeni',
    'Minerongongo',
    'Mkoka',
    'Mkotokuyana',
    'Mpiruka',
    'Mtua',
    'Naipanga',
    'Naipingo',
    'Namapwia',
    'Namatula',
    'Nambambo',
    'Namikango',
    'Nangowe',
    'Nditi',
    'Ndomoni',
    'Ruponda',
    'Stesheni',
  ],
  'Namtumbo': [
    'Hanga',
    'Kitanda',
    'Ligera',
    'Likuyuseka',
    'Limamu',
    'Litola',
    'Luchili',
    'Luegu',
    'Lusewa',
    'Magazini',
    'Mchomoro',
    'Mgombasi',
    'Mkongo',
    'Mputa',
    'Msindo',
    'Namabengo',
    'Namtumbo',
    'Rwinga',
  ],
  'Nanyumbu': [
    'Chipuputa',
    'Likokona',
    'Lumesule',
    'Mangaka',
    'Maratani',
    'Masuguru',
    'Mikangaula',
    'Mkonona',
    'Mnanje',
    'Nandete',
    'Nangomba',
    'Nanyumbu',
    'Napacho',
    'Sengenya',
  ],
  'Newala': [
    'Chihangu',
    'Chilangala',
    'Chitekete',
    'Chiwonga',
    'Kitangari',
    'Luchindu',
    'Makonga',
    'Makote',
    'Makukwe',
    'Malatu',
    'Maputi',
    'Mchemo',
    'Mcholi I',
    'Mcholi II',
    'Mdimba MpeleMpele',
    'Mkoma II',
    'Mkunya',
    'Mkwedu',
    'Mnekachi',
    'Mnyambe',
    'Mtonya',
    'Mtopwa',
    'Mtunguru',
    'Nakahako',
    'Nambali',
    'Namiyonga',
    'Nandwahi',
    'Nanguruwe',
  ],
  'Ngara': [
    'Bugarama',
    'Bukiriro',
    'Kabanga',
    'Kanazi',
    'Kasulo',
    'Keza',
    'Kibimba',
    'Kirushya',
    'Mabawe',
    'Mbuba',
    'Muganza',
    'Mugoma',
    'Murukulazo',
    'Murusagamba',
    'Ngara Mjini',
    'Ntobeye',
    'Nyakisasa',
    'Nyamiyaga',
    'Rulenge',
    'Rusumo',
  ],
  'Ngorongoro': [
    'Alailelai',
    'Arash',
    'Digodigo',
    'Endulen',
    'Engusero Sambu',
    'Kakesio',
    'Maalon',
    'Malambo',
    'Nainokanoka',
    'Naiyobi',
    'Ngorongoro',
    'Olbalbal',
    'Oldonyo Sambu',
    'Oloipiri',
    'Oloirien',
    'Ololosokwan',
    'Orgosorok',
    'Pinyinyi',
    'Sale',
    'Samunge',
    'Soitsambu',
  ],
  'Njombe': [
    'Idamba',
    'Igongolo',
    'Ikondo',
    'Ikuna',
    'Kichiwa',
    'Kidegembye',
    'Lupembe',
    'Matembwe',
    'Mfriga',
    'Mtwango',
    'Ninga',
  ],
  'Njombe City': [
    'Ihanga',
    'Iwungilo',
    'Kifanya',
    'Lugenge',
    'Luponde',
    'Makowo',
    'Matola',
    'Mjimwema',
    'Njombe Mjini',
    'Ramadhani',
    'Utalingolo',
    'Uwemba',
    'Yakobi',
  ],
  'Nkasi': [
    'Chala',
    'Isale',
    'Kabwe',
    'Kala',
    'Kate',
    'Kipande',
    'Kipili',
    'Kirando',
    'Korongwe',
    'Mkwamba',
    'Mtenga',
    'Namanyere',
    'Ninde',
    'Nkandasi',
    'Nkomolo',
    'Sintali',
    'Wampembe',
  ],
  'Nyamagana': [
    'Buhongwa',
    'Butimba',
    'Igogo',
    'Igoma',
    'Isamilo',
    'Mahina',
    'Mbugani',
    'Mirongo',
    'Mkolani',
    'Mkuyuni',
    'Nyamagana',
    'Pamba',
  ],
  'Nyang\'hwale': [
    'Bukwimba',
    'Busolwa',
    'Izunya',
    'Kafita',
    'Kakura',
    'Kharumwa',
    'Mwingiro',
    'Nyabulanda',
    'Nyang\'hwale',
    'Nyijundu',
    'Nyugwa',
    'Shabaka',
  ],
  'Nyasa': [
    'Chiwanda',
    'Kihagara',
    'Kilosa',
    'Kingerikiti',
    'Liparamba',
    'Lipingo',
    'Lituhi',
    'Liuli',
    'Liwundi',
    'Luhangarasi',
    'Mbaha',
    'Mbambabay',
    'Mtipwili',
    'Ngumbo',
    'Tingi',
  ],
  'Nzega': [
    'Budushi',
    'Bukene',
    'Igusule',
    'Ijanija',
    'Ikindwa',
    'Isagenhe',
    'Isanzu',
    'Itilo',
    'Itobo',
    'Kahamanhalanga',
    'Karitu',
    'Kasela',
    'Lusu',
    'Magengati',
    'Mambali',
    'Mbogwe',
    'Miguwa',
    'Milambo Itobo',
    'Mizibaziba',
    'Mogwa',
    'Muhugi',
    'Mwakashanhala',
    'Mwamala',
    'Mwangoye',
    'Nata',
    'Ndala',
    'Nkiniziwa',
    'Nzega Mjini',
    'Nzegandogo',
    'Puge',
    'Semembela',
    'Shigamba',
    'Sigili',
    'Tongi',
    'Uduka',
    'Utwigu',
    'Wela',
  ],
  'Pangani': [
    'Bushiri',
    'Bweni',
    'Kimang\'a',
    'Kipumbwi',
    'Madanga',
    'Mikunguni',
    'Mkalamo',
    'Mkwaja',
    'Mwera',
    'Pangani Magharibi',
    'Pangani Mashariki',
    'Tungamaa',
    'Ubangaa',
  ],
  'Rombo': [
    'Aleni',
    'Holili',
    'Katangara Mrere',
    'Kelamfua Mokala',
    'Keni Mengeni',
    'Kirongo Samanga',
    'Kirwa Keni',
    'Kisale Msaranga',
    'Kitirima Kingachi',
    'Mahida',
    'Makiidi',
    'Mamsera',
    'Manda',
    'Marangu Kitowo',
    'Mengwe',
    'Motamburu Kitendeni',
    'Mrao Keryo',
    'Nanjara Reha',
    'Ngoyoni',
    'Olele',
    'Shimbi',
    'Tarakea Motamburu',
    'Ubetu Kahe',
    'Ushiri Ikuini',
  ],
  'Rorya': [
    'Bukura',
    'Bukwe',
    'Goribe',
    'Ikoma',
    'Kigunga',
    'Kirogo',
    'Kisumwa',
    'Kitembe',
    'Komuge',
    'Koryo',
    'Kyang\'ombe',
    'Mirare',
    'Mkoma',
    'Nyahongo',
    'Nyamagaro',
    'Nyamtinga',
    'Nyamunga',
    'Nyathorogo',
    'Rabour',
    'Roche',
    'Tai',
  ],
  'Ruangwa': [
    'Chibula',
    'Chienjele',
    'Chinongwe',
    'Chunyu',
    'Likunja',
    'Luchelegwa',
    'Makanjiro',
    'Malolo',
    'Mandarawe',
    'Mandawa',
    'Matambarale',
    'Mbekenyera',
    'Mnacho',
    'Nachingwea',
    'Nambilanje',
    'Namichiga',
    'Nandagala',
    'Nanganga',
    'Narung\'ombe',
    'Nkowe',
    'Ruangwa',
  ],
  'Rufiji': [
    'Bungu',
    'Chemchem',
    'Chumbi',
    'Dimani',
    'Ikwiriri',
    'Kibiti',
    'Kiongoroni',
    'Mahege',
    'Maparoni',
    'Mbuchi',
    'Mbwara',
    'Mchukwi',
    'Mgomba',
    'Mjawa',
    'Mkongo',
    'Mlanzi',
    'Mtawanya',
    'Mtunda',
    'Mwambao',
    'Mwaseni',
    'Ngarambe',
    'Ngorongo',
    'Ruaruke',
    'Salale',
    'Umwe',
    'Utete',
  ],
  'Rungwe': [
    'Bagamoyo',
    'Bujela',
    'Bulyaga',
    'Ibighi',
    'Ikama',
    'Ikuti',
    'Ilima',
    'Isange',
    'Isongole',
    'Itete',
    'Kabula',
    'Kambasegela',
    'Kandete',
    'Kawetele',
    'Kikole',
    'Kinyala',
    'Kisegese',
    'Kisiba',
    'Kisondela',
    'Kiwira',
    'Kyimo',
    'Lufilyo',
    'Lufingo',
    'Lupata',
    'Luteba',
    'Lwangwa',
    'Makandana',
    'Malindo',
    'Masebe',
    'Masoko',
    'Masukulu',
    'Mpombo',
    'Mpuguso',
    'Msasani',
    'Nkunga',
    'Suma',
    'Swaya',
  ],
  'Same': [
    'Bendera',
    'Bombo',
    'Bwambo',
    'Chome',
    'Hedaru',
    'Kalemawe',
    'Kihurio',
    'Kirangare',
    'Kisima',
    'Kisiwani',
    'Lugulu',
    'Mabilioni',
    'Makanya',
    'Maore',
    'Mhezi',
    'Mpinji',
    'Mshewa',
    'Msindo',
    'Mtii',
    'Mwembe',
    'Myamba',
    'Ndungu',
    'Njoro',
    'Ruvu',
    'Same',
    'Stesheni',
    'Suji',
    'Vudee',
    'Vuje',
    'Vumari',
    'Vunta',
  ],
  'Sengerema': [
    'Bulyaheke',
    'Bupandwa',
    'Busisi',
    'Buyagu',
    'Buzilasoga',
    'Chifumfu',
    'Ibisabageni',
    'Igalula',
    'Igulumuki',
    'Irenza',
    'Kafunzo',
    'Kagunga',
    'Kalebezo',
    'Kasenyi',
    'Kasungamile',
    'Katunguru',
    'Katwe',
    'Kazunzu',
    'Kishinda',
    'Lugata',
    'Maisome',
    'Mwambului',
    'Nyakaliro',
    'Nyakasasa',
    'Nyakasunga',
    'Nyamatongo',
    'Nyamazugo',
    'Nyampande',
    'Nyampulukano',
    'Nyanzenda',
    'Nyatukala',
    'Nyehunge',
    'Sima',
    'Tabaruka',
  ],
  'Serengeti': [
    'Busawe',
    'Geitasamo',
    'Ikoma',
    'Issenye',
    'Kebanchabancha',
    'Kenyamonta',
    'Kisaka',
    'Kisangura',
    'Kyambahi',
    'Machochwe',
    'Magange',
    'Majimoto',
    'Manchira',
    'Mbalibali',
    'Morotonga',
    'Mosongo',
    'Mugumu',
    'Natta',
    'Nyamatare',
    'Nyambureti',
    'Nyamoko',
    'Nyansurura',
    'Rigicha',
    'Ring\'wani',
    'Rung\'abure',
    'Sedeco',
    'Stendi Kuu',
    'Uwanja wa Ndege',
  ],
  'Shinyanga': [
    'Bukene',
    'Didia',
    'Ilola',
    'Imesela',
    'Iselamagazi',
    'Itwangi',
    'Lyabukande',
    'Lyabusalu',
    'Lyamidati',
    'Masengwa',
    'Mwakitolyoo',
    'Mwalukwa',
    'Mwamala',
    'Mwantini',
    'Mwenge',
    'Nsalala',
    'Nyamalogo',
    'Nyida',
    'Pandagichiza',
    'Puni',
    'Salawe',
    'Samuye',
    'Solwa',
    'Tinde',
    'Usanda',
    'Usule',
  ],
  'Shinyanga City': [
    'Chamaguha',
    'Chibe',
    'Ibadakuli',
    'Ibinzamata',
    'Kambarage',
    'Kitangili',
    'Kizumbi',
    'Kolandoto',
    'Lubaga',
    'Masekelo',
    'Mwamalili',
    'Mwawaza',
    'Ndala',
    'Ndembezi',
    'Ngokolo',
    'Old Shinyanga',
    'Shinyanga Mjini',
  ],
  'Siha': [
    'Biriri',
    'Gararagua',
    'Ivaeny',
    'Karansi',
    'Kashisha',
    'Livishi',
    'Makiwaru',
    'Nasai',
    'Ndumeti',
    'Ngarenairobi',
    'Olkolili',
    'Sanya Juu',
  ],
  'Sikonge': [
    'Chabutwa',
    'Igigwa',
    'Ipole',
    'Kaloleli',
    'Kiloli',
    'Kipanga',
    'Kipili',
    'Kisanga',
    'Kitunda',
    'Misheni',
    'Mole',
    'Mpombwe',
    'Ngoywa',
    'Pangale',
    'Sikonge',
    'Tutuo',
    'Usunga',
  ],
  'Simanjiro': [
    'Emboreet',
    'Endiantu',
    'Endonyongijape',
    'Kitwai',
    'Komolo',
    'Liborsoit',
    'Loiborsiret',
    'Mererani',
    'Msitu wa Tembo',
    'Naberera',
    'Naisinyai',
    'Ngorika',
    'Oljoro  No. 5',
    'Orkesmet',
    'Ruvu Remiti',
    'Shambarai',
    'Terrat',
  ],
  'Singida': [
    'Ikhanoda',
    'Ilongero',
    'Itaja',
    'Kijota',
    'Kinyagigi',
    'Kinyeto',
    'Maghojoa',
    'Makuro',
    'Merya',
    'Mgori',
    'Mrama',
    'Msange',
    'Msisi',
    'Mtinko',
    'Mudida',
    'Mughamo',
    'Mughunga',
    'Mwasauya',
    'Ngimu',
    'Ntonge',
    'Ughandi',
  ],
  'Singida City': [
    'Ipembe',
    'Kindai',
    'Majengo',
    'Mandewa',
    'Minga',
    'Misuna',
    'Mitunduru',
    'Mtamaa',
    'Mtipa',
    'Mughanga',
    'Mungu maji',
    'Mwankoko',
    'Uhamaka',
    'Umyambwa',
    'Unyamikumbi',
    'Utemini',
  ],
  'Songea': [
    'Gumbiro',
    'Kilagano',
    'Litisha',
    'Magagura',
    'Mahanje',
    'Maposeni',
    'Matimira',
    'Matumbi',
    'Mbinga Mhalule',
    'Mkongotema',
    'Mpandangino',
    'Mpitimbi',
    'Mtyangimbole',
    'Muhuruku',
    'Ndongosi',
    'Peramiho',
    'Wino',
  ],
  'Songea City': [
    'Bombambili',
    'Lilambo',
    'Lizaboni',
    'Majengo',
    'Matarawe',
    'Mateka',
    'Matogoro',
    'Mfaranyaki',
    'Misufini',
    'Mjimwema',
    'Mjini',
    'Mletele',
    'Msamala',
    'Mshangano',
    'Mwengemshindo',
    'Ndilimalitembo',
    'Ruhuwiko',
    'Ruvuma',
    'Seedfarm',
    'Subira',
    'Tanga',
  ],
  'Songwe': [
    'Galula',
    'Gua',
    'Ifyenkenya',
    'Kanga',
    'Kapalala',
    'Magamba',
    'Mbangala',
    'Mbuyuni',
    'Mkwajuni',
    'Mwambani',
    'Namkukwe',
    'Ngwala',
    'Saza',
    'Totowe',
  ],
  'Sumbawanga': [
    'Ilemba',
    'Kaengesa',
    'Kalambanzite',
    'Kaoze',
    'Kipeta',
    'Laela',
    'Lusaka',
    'Mfinga',
    'Miangalua',
    'Milepa',
    'Mpui',
    'Msanda Muungano',
    'Mtowisa',
    'Muze',
    'Sandulula',
  ],
  'Sumbawanga City': [
    'Chanji',
    'Izia',
    'Kasense',
    'Katandala',
    'Kizwite',
    'Majengo',
    'Malangali',
    'Matanga',
    'Mazwi',
    'Milanzi',
    'Mollo',
    'Ntendo',
    'Old Sumbawanga',
    'Pito',
    'Senga',
  ],
  'Tabora City': [
    'Chemchem',
    'Cheyo',
    'Gongoni',
    'Ifucha',
    'Ikomwa',
    'Ipuli',
    'Isevya',
    'Itetemia',
    'Itonjanda',
    'Kabila',
    'Kakola',
    'Kalunde',
    'Kanyenye',
    'Kiloleni',
    'Kitete',
    'Malolo',
    'Mbugani',
    'Misha',
    'Mtendeni',
    'Ndevelwa',
    'Ng`ambo',
    'Ntalikwa',
    'Tambukareli',
    'Tumbi',
    'Uyui',
  ],
  'Tandahimba': [
    'Chaume',
    'Chikongola',
    'Chingungwe',
    'Dinduma',
    'Kitama',
    'Kwanyama',
    'Litehu',
    'Luagala',
    'Lukokoda',
    'Lyenje',
    'Mahuta',
    'Maundo',
    'Mchichira',
    'Mdimba Mnyoma',
    'Mdumbwe',
    'Michenjele',
    'Mihambwe',
    'Milongodi',
    'Miuta',
    'Mkonjowano',
    'Mkoreha',
    'Mkundi',
    'Mkwiti',
    'Mnyawa',
    'Nambahu',
    'Namikupa',
    'Nanhyanga',
    'Naputa',
    'Ngunja',
    'Tandahimba',
  ],
  'Tanga City': [
    'Central',
    'Chongoleani',
    'Chumbageni',
    'Duga',
    'Kiomoni',
    'Kirare',
    'Mabawa',
    'Mabokweni',
    'Majengo',
    'Makorora',
    'Marungu',
    'Maweni',
    'Msambweni',
    'Mwanzange',
    'Mzingani',
    'Mzizima',
    'Ngamiani Kaskazini',
    'Ngamiani Kati',
    'Ngamiani Kusini',
    'Nguvumali',
    'Pongwe',
    'Tangasisi',
    'Tongoni',
    'Usagara',
  ],
  'Tarime': [
    'Binagi',
    'Bomani',
    'Bumera',
    'Genyange',
    'Gorong\'a',
    'Itiryo',
    'Kemambo',
    'Kentare',
    'Kibasuka',
    'Kiore',
    'Komaswa',
    'Manga',
    'Matongo',
    'Mbogi',
    'Muriba',
    'Mwema',
    'Nyakonga',
    'Nyamaranga',
    'Nyamisangura',
    'Nyamwaga',
    'Nyandoto',
    'Nyansicha',
    'Nyanungu',
    'Nyarero',
    'Nyarokoba',
    'Pemba',
    'Sabasaba',
    'Sirari',
    'Susuni',
    'Turwa',
  ],
  'Temeke': [
    'Azimio',
    'Buza',
    'Chamazi',
    'Chang\'ombe',
    'Charambe',
    'Keko',
    'Kibada',
    'Kiburugwa',
    'Kigamboni',
    'Kijichi',
    'Kilakala',
    'Kimbiji',
    'Kisarawe II',
    'Kurasini',
    'Makangarawe',
    'Mbagala',
    'Mbagala Kuu',
    'Mianzini',
    'Miburani',
    'Mjimwema',
    'Mtoni',
    'Pemba Mnazi',
    'Sandali',
    'Somangila',
    'Tandika',
    'Temeke',
    'Toangoma',
    'Tungi',
    'Vijibweni',
    'Yombo Vituka',
  ],
  'Tunduma': ['Tunduma'],
  'Tunduru': [
    'Jakika',
    'Kalulu',
    'Kidodoma',
    'Ligoma',
    'Ligunga',
    'Lukumbule',
    'Majengo',
    'Marumba',
    'Masonya',
    'Matemanga',
    'Mbati',
    'Mbesa',
    'Mchangani',
    'Mchesi',
    'Mchoteka',
    'Mchuluka',
    'Mindu',
    'Misechela',
    'Mlingoti  Magharibi',
    'Mlingoti  Mashariki',
    'Mtina',
    'Muhuwesi',
    'Nakapanya',
    'Nakayaya',
    'Nalasi Mashariki',
    'Nalasi-Magharibi',
    'Namasakata',
    'Namiungo',
    'Nampungu',
    'Namwinyu',
    'Nandembo',
    'Nanjoka',
    'Ngapa',
    'Sisikwasisi',
    'Tuwemacho',
  ],
  'Ukerewe': [
    'Bukanda',
    'Bukindo',
    'Bukiro',
    'Bukongo',
    'Bukungu',
    'Bwiro',
    'Bwisya',
    'Igala',
    'Ilangala',
    'Irugwa',
    'Kagera',
    'Kagunguli',
    'Kakerege',
    'Mukituntu',
    'Muriti',
    'Murutunguru',
    'Nakatunguru',
    'Namagondo',
    'Namilembe',
    'Nansio',
    'Nduruma',
    'Ngoma',
    'Nkilizya',
    'Nyamanga',
  ],
  'Ulanga': [
    'Biro',
    'Chirombola',
    'Euga',
    'Ilonga',
    'Iragua',
    'Isongo',
    'Itete',
    'Kichangani',
    'Kilosa kwa Mpepo',
    'Lukande',
    'Lupiro',
    'Mahenge',
    'Malinyi',
    'Mbuga',
    'Minepa',
    'Msogezi',
    'Mtimbira',
    'Mwaya',
    'Ngoheranga',
    'Ruaha',
    'Sali',
    'Sofi',
    'Usangule',
    'Vigoi',
  ],
  'Urambo': [
    'Imalamakoye',
    'Kapilula',
    'Kasisi',
    'Kiloleni',
    'Muungano',
    'Nsenda',
    'Songambele',
    'Ugalla',
    'Ukondamoyo',
    'Urambo',
    'Usisya',
    'Ussoke',
    'Utundu',
    'Uyogo',
    'Uyumbu',
    'Vumilia',
  ],
  'Uvinza': [
    'Buhingu',
    'Igalula',
    'Ilagala',
    'Itebula',
    'Kalya',
    'Kandaga',
    'Kazuramimba',
    'Mganza',
    'Mtego wa Noti',
    'Nguruka',
    'Sigunga',
    'Simbo',
    'Sunuka',
    'Uvinza',
  ],
  'Uyui': [
    'Bukumbi',
    'Goweko',
    'Ibelamilundi',
    'Ibiri',
    'Igalula',
    'Ikongolo',
    'Ilolanguru',
    'Isikizya',
    'Kigwa',
    'Kizengi',
    'Loya',
    'Lutende',
    'Mabama',
    'Magiri',
    'Miswaki',
    'Miyenze',
    'Ndono',
    'Nsimbo',
    'Nsololo',
    'Shitage',
    'Tura',
    'Ufuluma',
    'Upuge',
    'Usagari',
  ],
  'Wanging\'ombe': [
    'Igima',
    'Igosi',
    'Igwachanya',
    'Ilembula',
    'Imalinyi',
    'Kidugala',
    'Kijombe',
    'Kipengere',
    'Luduga',
    'Makoga',
    'Mdandu',
    'Saja',
    'Uhambule',
    'Ulembwe',
    'Usuka',
    'Wangama',
    'Wanging\'ombe',
  ],
  'Wete': [
    'Bopwe',
    'Chwale',
    'Fundo',
    'Gando',
    'Jadida',
    'Junguni',
    'Kambini',
    'Kangagani',
    'Kinyikani',
    'Kipangani',
    'Kisiwani',
    'Kiungoni',
    'Kiuyu Kigongoni',
    'Kiuyu Minungwini',
    'Kizimbani',
    'Kojani',
    'Limbani',
    'Maziwani',
    'Mchanga Mdogo',
    'Mjini Ole',
    'Mpambani',
    'Mtambwe Kaskazini',
    'Mtambwe Kusini',
    'Mzambarauni Takao',
    'Ole',
    'Pandani',
    'Pembeni',
    'Piki',
    'Selem',
    'Shengejuu',
    'Ukunjwi',
    'Utaani',
  ],
};
