/// Tanzania districts (official councils) grouped by region, matching the
/// region list used in the checkout screen.
const Map<String, List<String>> kRegionDistricts = {
  'Arusha': ['Arusha City', 'Arusha', 'Karatu', 'Longido', 'Meru', 'Monduli', 'Ngorongoro'],
  'Dar es Salaam': ['Ilala', 'Kigamboni', 'Kinondoni', 'Temeke', 'Ubungo'],
  'Dodoma': ['Bahi', 'Chamwino', 'Chemba', 'Dodoma City', 'Kongwa', 'Kondoa', 'Mpwapwa'],
  'Geita': ['Bukombe', 'Chato', 'Geita', 'Mbogwe', "Nyang'hwale"],
  'Iringa': ['Iringa City', 'Iringa', 'Kilolo', 'Mufindi'],
  'Kagera': ['Biharamulo', 'Bukoba City', 'Bukoba', 'Karagwe', 'Kyerwa', 'Missenyi', 'Muleba', 'Ngara'],
  'Katavi': ['Mlele', 'Mpanda', 'Mpimbwe', 'Tanganyika'],
  'Kigoma': ['Buhigwe', 'Kakonko', 'Kasulu City', 'Kasulu', 'Kibondo', 'Kigoma City', 'Kigoma', 'Uvinza'],
  'Kilimanjaro': ['Hai', 'Moshi City', 'Moshi', 'Mwanga', 'Rombo', 'Same', 'Siha'],
  'Lindi': ['Kilwa', 'Lindi City', 'Lindi', 'Liwale', 'Nachingwea', 'Ruangwa'],
  'Manyara': ['Babati City', 'Babati', 'Hanang', 'Kiteto', 'Mbulu', 'Simanjiro'],
  'Mara': ['Bunda', 'Butiama', 'Musoma City', 'Musoma', 'Rorya', 'Serengeti', 'Tarime'],
  'Mbeya': ['Busokelo', 'Chunya', 'Kyela', 'Mbarali', 'Mbeya City', 'Mbeya', 'Rungwe'],
  'Mjini Magharibi': ['Magharibi A', 'Magharibi B', 'Mjini'],
  'Morogoro': ['Gairo', 'Ifakara', 'Kilombero', 'Kilosa', 'Malinyi', 'Morogoro City', 'Morogoro', 'Mvomero', 'Ulanga'],
  'Mtwara': ['Masasi City', 'Masasi', 'Mtwara City', 'Mtwara', 'Nanyumbu', 'Newala City', 'Newala', 'Tandahimba'],
  'Mwanza': ['Buchosa', 'Ilemela', 'Kwimba', 'Magu', 'Misungwi', 'Mwanza City', 'Nyamagana', 'Sengerema', 'Ukerewe'],
  'Njombe': ['Ludewa', 'Makambako', 'Makete', 'Njombe City', 'Njombe', "Wanging'ombe"],
  'Pwani': ['Bagamoyo', 'Chalinze', 'Kibaha City', 'Kibaha', 'Kisarawe', 'Mafia', 'Mkuranga', 'Rufiji'],
  'Rukwa': ['Kalambo', 'Nkasi', 'Sumbawanga City', 'Sumbawanga'],
  'Ruvuma': ['Mbinga', 'Namtumbo', 'Nyasa', 'Songea City', 'Songea', 'Tunduru'],
  'Shinyanga': ['Kahama City', 'Kahama', 'Kishapu', 'Msalala', 'Shinyanga City', 'Shinyanga', 'Ushetu'],
  'Simiyu': ['Bariadi', 'Busega', 'Itilima', 'Maswa', 'Meatu'],
  'Singida': ['Ikungi', 'Iramba', 'Itigi', 'Manyoni', 'Mkalama', 'Singida City', 'Singida'],
  'Songwe': ['Ileje', 'Mbozi', 'Momba', 'Songwe', 'Tunduma'],
  'Tabora': ['Igunga', 'Kaliua', 'Nzega', 'Sikonge', 'Tabora City', 'Tabora', 'Urambo', 'Uyui'],
  'Tanga': ['Bumbuli', 'Handeni City', 'Handeni', 'Kilindi', 'Korogwe City', 'Korogwe', 'Lushoto', 'Mkinga', 'Muheza', 'Pangani', 'Tanga City'],
};
